USE `avrex`;
INSERT IGNORE INTO items (name, label, type, weight, premium, perm, image, description, data) VALUES
('ammo_airsoft','Ammo Airsoft','items',1,0,0,'items/ammo_airsoft.webp','Billes en plastique pour armes d''airsoft. Inoffensives mais rÃ©alistes.','{"type":"objects"}'),
('ammo_beanbag','Ammo Beanbag','items',1,0,0,'items/ammo_beanbag.webp','Cartouche non-lÃ©tale projetant un sac lestÃ©. UtilisÃ©e pour neutraliser sans blesser.','{"type":"objects"}'),
('ammo_flare','Ammo Flare','items',1,0,0,'items/ammo_flare.webp','Cartouche de dÃ©tresse tirant une fusÃ©e lumineuse pour signaler sa position.','{"type":"objects"}'),
('ammo_heavy','Ammo Heavy','items',1,0,0,'items/ammo_heavy.webp','Munitions lourdes pour mitrailleuses et armes de gros calibre.','{"type":"objects"}'),
('ammo_launcher','Ammo Launcher','items',1,0,0,'items/ammo_launcher.webp','Munitions pour lance-grenades et lance-roquettes. TrÃ¨s destructrices.','{"type":"objects"}'),
('ammo_musquet','Ammo Musquet','items',1,0,0,'items/ammo_musquet.webp','Balle ronde en plomb pour mousquet. UtilisÃ©e lors de la chasse.','{"type":"objects"}'),
('ammo_pistol','Ammo Pistol','items',1,0,0,'items/ammo_pistol.webp','Munitions lÃ©gÃ¨res pour pistolets et revolvers.','{"type":"objects"}'),
('ammo_rifle','Ammo Rifle','items',1,0,0,'items/ammo_rifle.webp','Munitions moyennes pour fusils d''assaut et carabines.','{"type":"objects"}'),
('ammo_rocket','Ammo Rocket','items',1,0,0,'items/ammo_rocket.webp','Roquette explosive pour lance-missiles. Usage militaire uniquement.','{"type":"objects"}'),
('ammo_shotgun','Ammo Shotgun','items',1,0,0,'items/ammo_shotgun.webp','Cartouches Ã  chevrotine pour fusils Ã  pompe.','{"type":"objects"}'),
('ammo_snip','Ammo Snip','items',1,0,0,'items/ammo_snip.webp','Cartouches de prÃ©cision pour fusils sniper.','{"type":"objects"}'),
('acier','Acier','items',100,0,0,'items/acier.webp','Lingot d''acier utilisÃ© dans la fabrication de plaques de protection et d''Ã©quipements.','{"type":"objects"}'),
('charcoal','Charcoal','items',100,0,0,'items/charcoal.webp','Charbon extrait des mines.','{"type":"objects"}'),
('charcoal_dirty','Charcoal Dirty','items',100,0,0,'items/charcoal_dirty.webp','Charbon sale rÃ©cupÃ©rÃ© en mine. NÃ©cessite un nettoyage.','{"type":"objects"}'),
('cuivre','Cuivre','items',100,0,0,'items/cuivre.webp','Cuivre raffinÃ©, matÃ©riau de base pour la fabrication de munitions.','{"type":"objects"}'),
('cuivre_dirty','Cuivre Dirty','items',100,0,0,'items/cuivre_dirty.webp','Cuivre brut extrait des mines. Doit Ãªtre nettoyÃ©.','{"type":"objects"}'),
('cuivre_gpb','Cuivre Gpb','items',100,0,0,'items/cuivre_gpb.webp','Cuivre de qualitÃ© supÃ©rieure utilisÃ© dans la fabrication d''item illÃ©gal.','{"type":"objects"}'),
('gold','Gold','items',100,0,0,'items/gold.webp','Or pur extrait des mines. TrÃ¨s prÃ©cieux.','{"type":"objects"}'),
('gold_bar','Gold Bar','items',100,0,0,'items/gold_bar.webp','Lingot d''or massif. Objet de trÃ¨s grande valeur.','{"type":"objects"}'),
('gold_dirty','Gold Dirty','items',100,0,0,'items/gold_dirty.webp','Or brut non raffinÃ©, rÃ©cupÃ©rÃ© en mine. Doit Ãªtre nettoyÃ©.','{"type":"objects"}'),
('papier','Papier','items',100,0,0,'items/papier.webp','Feuilles de papier utilisables pour diverses utilitÃ©s.','{"type":"objects"}'),
('poudre_noir','Poudre Noir','items',100,0,0,'items/poudre_noir.webp','Poudre noire explosive, ingrÃ©dient essentiel pour fabriquer des munitions.','{"type":"objects"}'),
('rawwood','Rawwood','items',100,0,0,'items/rawwood.webp','BÃ»che de bois brut rÃ©coltÃ©e. Peut Ãªtre transformÃ©e en planches.','{"type":"objects"}'),
('tissu','Tissu','items',100,0,0,'items/tissu.webp','Rouleau de tissu utilisÃ© dans la fabrication de gilets pare-balles et vÃªtements.','{"type":"objects"}'),
('vis','Vis','items',100,0,0,'items/vis.webp','Vis mÃ©talliques utilisÃ©es comme composant de crafting.','{"type":"objects"}'),
('wooden_plank','Wooden Plank','items',100,0,0,'items/wooden_plank.webp','Planche de bois dÃ©coupÃ©e, utilisÃ©e dans la construction et le crafting.','{"type":"objects"}'),
('cordes','Cordes','items',100,0,0,'items/cordes.webp','Corde solide permettant d''attacher un vÃ©hicule pour le dÃ©panner.','{"type":"objects"}'),
('pieces_arme','Pieces Arme','items',100,0,0,'items/pieces_arme.webp','PiÃ¨ces dÃ©tachÃ©es d''armes Ã  feu, nÃ©cessaires pour le crafting d''armes illÃ©gales.','{"type":"objects"}'),
('armor_plate_heavy','Armor Plate Heavy','items',100,0,0,'items/armor_plate_heavy.webp','Plaque de blindage lourde offrant une protection maximale (100%).','{"type":"objects"}'),
('armor_plate_light','Armor Plate Light','items',100,0,0,'items/armor_plate_light.webp','Plaque de blindage lÃ©gÃ¨re offrant une protection basique (30%).','{"type":"objects"}'),
('armor_plate_medium','Armor Plate Medium','items',100,0,0,'items/armor_plate_medium.webp','Plaque de blindage moyenne offrant une bonne protection (60%).','{"type":"objects"}'),
('gpb','Gpb','items',100,0,0,'items/gpb.webp','Gilet pare-balles Ã©quipable. Accepte des plaques de protection (lÃ©gÃ¨re, moyenne ou lourde).','{"type":"objects"}'),
('blueprint_petoire','Blueprint Petoire','items',100,0,0,'items/blueprint_petoire.webp','Plan de fabrication pour un PÃ©toire (HK PM710). NÃ©cessaire pour le craft illÃ©gal.','{"type":"objects"}'),
('blueprint_microsmg','Blueprint Microsmg','items',100,0,0,'items/blueprint_microsmg.webp','Plan de fabrication pour un Micro SMG. NÃ©cessaire pour le craft illÃ©gal.','{"type":"objects"}'),
('blueprint_tec9','Blueprint Tec9','items',100,0,0,'items/blueprint_tec9.webp','Plan de fabrication pour un TEC-9. NÃ©cessaire pour le craft illÃ©gal.','{"type":"objects"}'),
('blueprint_pistol','Blueprint Pistol','items',100,0,0,'items/blueprint_pistol.webp','Plan de fabrication pour un Beretta 92 FS. NÃ©cessaire pour le craft illÃ©gal.','{"type":"objects"}'),
('blueprint_pistol50','Blueprint Pistol50','items',100,0,0,'items/blueprint_pistol50.webp','Plan de fabrication pour un Desert Eagle .50. NÃ©cessaire pour le craft illÃ©gal.','{"type":"objects"}'),
('blueprint_pumpshotgun','Blueprint Pumpshotgun','items',100,0,0,'items/blueprint_pumpshotgun.webp','Plan de fabrication pour un Remington 870. NÃ©cessaire pour le craft illÃ©gal.','{"type":"objects"}'),
('blueprint_sawnoffshotgun','Blueprint Sawnoffshotgun','items',100,0,0,'items/blueprint_sawnoffshotgun.webp','Plan de fabrication pour un fusil Ã  canon sciÃ©. NÃ©cessaire pour le craft illÃ©gal.','{"type":"objects"}'),
('blueprint_smg','Blueprint Smg','items',100,0,0,'items/blueprint_smg.webp','Plan de fabrication pour un MP5. NÃ©cessaire pour le craft illÃ©gal.','{"type":"objects"}'),
('wcomponent_clip_default_pistol','Wcomponent Clip Default Pistol','items',100,0,0,'items/wcomponent_clip_default_pistol.webp','Chargeur standard pour pistolet. CapacitÃ© de base.','{"type":"objects"}'),
('wcomponent_clip_default_smg','Wcomponent Clip Default Smg','items',100,0,0,'items/wcomponent_clip_default_smg.webp','Chargeur standard pour mitraillette. CapacitÃ© de base.','{"type":"objects"}'),
('wcomponent_clip_default_rifle','Wcomponent Clip Default Rifle','items',100,0,0,'items/wcomponent_clip_default_rifle.webp','Chargeur standard pour fusil d''assaut. CapacitÃ© de base.','{"type":"objects"}'),
('wcomponent_clip_default_mg','Wcomponent Clip Default Mg','items',100,0,0,'items/wcomponent_clip_default_mg.webp','Chargeur standard pour mitrailleuse. CapacitÃ© de base.','{"type":"objects"}'),
('wcomponent_clip_default_shotgun','Wcomponent Clip Default Shotgun','items',100,0,0,'items/wcomponent_clip_default_shotgun.webp','Tube de chargement standard pour fusil Ã  pompe.','{"type":"objects"}'),
('wcomponent_clip_default_sniper','Wcomponent Clip Default Sniper','items',100,0,0,'items/wcomponent_clip_default_sniper.webp','Chargeur standard pour fusil de prÃ©cision.','{"type":"objects"}'),
('wcomponent_clip_extended_pistol','Wcomponent Clip Extended Pistol','items',100,0,0,'items/wcomponent_clip_extended_pistol.webp','Chargeur allongÃ© pour pistolet. CapacitÃ© augmentÃ©e.','{"type":"objects"}'),
('wcomponent_clip_extended_smg','Wcomponent Clip Extended Smg','items',100,0,0,'items/wcomponent_clip_extended_smg.webp','Chargeur allongÃ© pour mitraillette. CapacitÃ© augmentÃ©e.','{"type":"objects"}'),
('wcomponent_clip_extended_rifle','Wcomponent Clip Extended Rifle','items',100,0,0,'items/wcomponent_clip_extended_rifle.webp','Chargeur allongÃ© pour fusil d''assaut. CapacitÃ© augmentÃ©e.','{"type":"objects"}'),
('wcomponent_clip_extended_mg','Wcomponent Clip Extended Mg','items',100,0,0,'items/wcomponent_clip_extended_mg.webp','Chargeur allongÃ© pour mitrailleuse. CapacitÃ© augmentÃ©e.','{"type":"objects"}'),
('wcomponent_clip_extended_shotgun','Wcomponent Clip Extended Shotgun','items',100,0,0,'items/wcomponent_clip_extended_shotgun.webp','Chargeur allongÃ© pour fusil Ã  pompe. CapacitÃ© augmentÃ©e.','{"type":"objects"}'),
('wcomponent_clip_extended_sniper','Wcomponent Clip Extended Sniper','items',100,0,0,'items/wcomponent_clip_extended_sniper.webp','Chargeur allongÃ© pour fusil sniper. CapacitÃ© augmentÃ©e.','{"type":"objects"}'),
('wcomponent_clip_drum_smg','Wcomponent Clip Drum Smg','items',100,0,0,'items/wcomponent_clip_drum_smg.webp','Chargeur tambour pour mitraillette. Grande capacitÃ© de munitions.','{"type":"objects"}'),
('wcomponent_clip_drum_rifle','Wcomponent Clip Drum Rifle','items',100,0,0,'items/wcomponent_clip_drum_rifle.webp','Chargeur tambour pour fusil. Grande capacitÃ© de munitions.','{"type":"objects"}'),
('wcomponent_clip_drum_shotgun','Wcomponent Clip Drum Shotgun','items',100,0,0,'items/wcomponent_clip_drum_shotgun.webp','Chargeur tambour pour fusil Ã  pompe. Grande capacitÃ©.','{"type":"objects"}'),
('wcomponent_clip_box_rifle','Wcomponent Clip Box Rifle','items',100,0,0,'items/wcomponent_clip_box_rifle.webp','Chargeur boÃ®te pour fusil. CapacitÃ© intermÃ©diaire.','{"type":"objects"}'),
('wcomponent_scope','Wcomponent Scope','items',100,0,0,'items/wcomponent_scope.webp','Lunette de visÃ©e basique amÃ©liorant la prÃ©cision Ã  moyenne distance.','{"type":"objects"}'),
('wcomponent_scope_small','Wcomponent Scope Small','items',100,0,0,'items/wcomponent_scope_small.webp','Petite lunette macro pour amÃ©liorer la visÃ©e rapprochÃ©e.','{"type":"objects"}'),
('wcomponent_scope_medium','Wcomponent Scope Medium','items',100,0,0,'items/wcomponent_scope_medium.webp','Lunette moyenne offrant un bon compromis portÃ©e/visibilitÃ©.','{"type":"objects"}'),
('wcomponent_scope_large','Wcomponent Scope Large','items',100,0,0,'items/wcomponent_scope_large.webp','Lunette longue portÃ©e pour le tir Ã  grande distance.','{"type":"objects"}'),
('wcomponent_scope_zoom','Wcomponent Scope Zoom','items',100,0,0,'items/wcomponent_scope_zoom.webp','Lunette Ã  zoom variable pour le tir de prÃ©cision.','{"type":"objects"}'),
('wcomponent_scope_advanced','Wcomponent Scope Advanced','items',100,0,0,'items/wcomponent_scope_advanced.webp','Lunette avancÃ©e avec rÃ©ticule amÃ©liorÃ© et zoom supÃ©rieur.','{"type":"objects"}'),
('wcomponent_scope_holo','Wcomponent Scope Holo','items',100,0,0,'items/wcomponent_scope_holo.webp','Viseur holographique pour une acquisition rapide de cible.','{"type":"objects"}'),
('wcomponent_scope_nightvision','Wcomponent Scope Nightvision','items',100,0,0,'items/wcomponent_scope_nightvision.webp','Lunette Ã  vision nocturne pour les opÃ©rations de nuit.','{"type":"objects"}'),
('wcomponent_scope_thermal','Wcomponent Scope Thermal','items',100,0,0,'items/wcomponent_scope_thermal.webp','Lunette thermique dÃ©tectant les signatures de chaleur.','{"type":"objects"}'),
('wcomponent_flashlight','Wcomponent Flashlight','items',100,0,0,'items/wcomponent_flashlight.webp','Lampe tactique montÃ©e sur rail pour Ã©clairer en situation de combat.','{"type":"objects"}'),
('wcomponent_suppressor','Wcomponent Suppressor','items',100,0,0,'items/wcomponent_suppressor.webp','Silencieux rÃ©duisant le bruit et la signature visuelle des tirs.','{"type":"objects"}'),
('wcomponent_compensator','Wcomponent Compensator','items',100,0,0,'items/wcomponent_compensator.webp','Compensateur de recul amÃ©liorant la stabilitÃ© lors du tir automatique.','{"type":"objects"}'),
('wcomponent_grip','Wcomponent Grip','items',100,0,0,'items/wcomponent_grip.webp','PoignÃ©e avant ergonomique rÃ©duisant le recul et amÃ©liorant le contrÃ´le.','{"type":"objects"}'),
('wcomponent_barrel_default','Wcomponent Barrel Default','items',100,0,0,'items/wcomponent_barrel_default.webp','Canon standard offrant des performances Ã©quilibrÃ©es.','{"type":"objects"}'),
('wcomponent_barrel_heavy','Wcomponent Barrel Heavy','items',100,0,0,'items/wcomponent_barrel_heavy.webp','Canon lourd amÃ©liorant la prÃ©cision au dÃ©triment de la mobilitÃ©.','{"type":"objects"}'),
('wcomponent_muzzle_bell','Wcomponent Muzzle Bell','items',100,0,0,'items/wcomponent_muzzle_bell.webp','Frein de bouche en cloche rÃ©duisant le relÃ¨vement du canon.','{"type":"objects"}'),
('wcomponent_muzzle_fat','Wcomponent Muzzle Fat','items',100,0,0,'items/wcomponent_muzzle_fat.webp','Frein de bouche large pour une rÃ©duction maximale du recul.','{"type":"objects"}'),
('wcomponent_muzzle_flat','Wcomponent Muzzle Flat','items',100,0,0,'items/wcomponent_muzzle_flat.webp','Frein de bouche plat offrant un bon contrÃ´le latÃ©ral.','{"type":"objects"}'),
('wcomponent_muzzle_heavy','Wcomponent Muzzle Heavy','items',100,0,0,'items/wcomponent_muzzle_heavy.webp','Frein de bouche lourd pour les armes Ã  fort recul.','{"type":"objects"}'),
('wcomponent_muzzle_precision','Wcomponent Muzzle Precision','items',100,0,0,'items/wcomponent_muzzle_precision.webp','Frein de bouche de prÃ©cision optimisÃ© pour le tir Ã  distance.','{"type":"objects"}'),
('wcomponent_muzzle_slanted','Wcomponent Muzzle Slanted','items',100,0,0,'items/wcomponent_muzzle_slanted.webp','Frein de bouche inclinÃ© compensant la dÃ©rive latÃ©rale.','{"type":"objects"}'),
('wcomponent_muzzle_split','Wcomponent Muzzle Split','items',100,0,0,'items/wcomponent_muzzle_split.webp','Frein de bouche divisÃ© rÃ©partissant les gaz de maniÃ¨re uniforme.','{"type":"objects"}'),
('wcomponent_muzzle_squared','Wcomponent Muzzle Squared','items',100,0,0,'items/wcomponent_muzzle_squared.webp','Frein de bouche carrÃ© offrant une rÃ©duction de recul polyvalente.','{"type":"objects"}'),
('wcomponent_muzzle_tactical','Wcomponent Muzzle Tactical','items',100,0,0,'items/wcomponent_muzzle_tactical.webp','Frein de bouche tactique pour un usage opÃ©rationnel.','{"type":"objects"}'),
('weapon_pistol','Beretta 92 FS','weapons',1500,0,0,'items/weapon_pistol.webp','Beretta 92 FS - Pistolet semi-automatique fiable et prÃ©cis. Craftable avec blueprint.','{"type":"objects"}'),
('weapon_combatpistol','Glock 17','weapons',1500,0,0,'items/weapon_combatpistol.webp','Glock 17 - Pistolet de combat robuste et polyvalent. Craftable avec blueprint.','{"type":"objects"}'),
('weapon_pistol50','Weapon Pistol50','weapons',1500,0,0,'items/weapon_pistol50.webp','Desert Eagle .50 - Pistolet surpuissant Ã  gros calibre. Craftable avec blueprint.','{"type":"objects"}'),
('weapon_heavypistol','Colt M45','weapons',1500,0,0,'items/weapon_heavypistol.webp','Colt M45 - Pistolet lourd Ã  fort pouvoir d''arrÃªt. Craft MC niveau C.','{"type":"objects"}'),
('weapon_snspistol','HK PM710','weapons',1500,0,0,'items/weapon_snspistol.webp','HK PM710 - Petit pistolet compact facilement dissimulable. Craft Mafia niveau B.','{"type":"objects"}'),
('weapon_snspistol_mk2','Weapon Snspistol Mk2','weapons',1500,0,0,'items/weapon_snspistol_mk2.webp','Version amÃ©liorÃ©e du HK PM710 avec performances supÃ©rieures.','{"type":"objects"}'),
('weapon_vintagepistol','FN 1922','weapons',1500,0,0,'items/weapon_vintagepistol.webp','FN 1922 - Pistolet vintage de collection au charme rÃ©tro.','{"type":"objects"}'),
('weapon_appistol','Weapon Appistol','weapons',1500,0,0,'items/weapon_appistol.webp','Pistolet automatique avec cadence de tir Ã©levÃ©e.','{"type":"objects"}'),
('weapon_ceramicpistol','Weapon Ceramicpistol','weapons',1500,0,0,'items/weapon_ceramicpistol.webp','Pistolet en cÃ©ramique indÃ©tectable aux portiques de sÃ©curitÃ©.','{"type":"objects"}'),
('weapon_gadgetpistol','Weapon Gadgetpistol','weapons',1500,0,0,'items/weapon_gadgetpistol.webp','Pistolet compact et discret, facile Ã  dissimuler.','{"type":"objects"}'),
('weapon_marksmanpistol','Weapon Marksmanpistol','weapons',1500,0,0,'items/weapon_marksmanpistol.webp','Pistolet de prÃ©cision Ã  un coup, trÃ¨s puissant mais lent.','{"type":"objects"}'),
('weapon_pistolxm3','Pistolet XM3','weapons',1500,0,0,'items/weapon_pistolxm3.webp','Pistolet XM3 - ModÃ¨le tactique moderne haute performance.','{"type":"objects"}'),
('weapon_pistol_mk2','Weapon Pistol Mk2','weapons',1500,0,0,'items/weapon_pistol_mk2.webp','Pistolet Beretta amÃ©liorÃ© avec accessoires MK2.','{"type":"objects"}'),
('weapon_machinepistol','TEC-9','weapons',1500,0,0,'items/weapon_machinepistol.webp','TEC-9 - Pistolet-mitrailleur compact Ã  haute cadence. Craft Orga niveau B.','{"type":"objects"}'),
('weapon_glock20','Glock 20','weapons',1500,0,0,'items/weapon_glock20.webp','Glock 20 - Pistolet calibre 10mm Ã  fort pouvoir d''arrÃªt.','{"type":"objects"}'),
('weapon_sig_saucer','Sig Sauer','weapons',1500,0,0,'items/weapon_sig_saucer.webp','Sig Sauer - Pistolet de prÃ©cision utilisÃ© par les forces spÃ©ciales.','{"type":"objects"}'),
('weapon_swmp9l','Smith & Wesson M&P9','weapons',1500,0,0,'items/weapon_swmp9l.webp','Smith & Wesson M&P9 - Pistolet moderne fiable et ergonomique.','{"type":"objects"}'),
('weapon_pdglock17','Weapon Pdglock17','weapons',1500,0,0,'items/weapon_pdglock17.webp','Glock 17 rÃ©servÃ© aux forces de l''ordre (PD).','{"type":"objects"}'),
('weapon_revolver','Taurus','weapons',1500,0,0,'items/weapon_revolver.webp','Taurus - Revolver puissant Ã  barillet. Craft Mafia niveau B.','{"type":"objects"}'),
('weapon_revolver_mk2','Weapon Revolver Mk2','weapons',1500,0,0,'items/weapon_revolver_mk2.webp','Revolver amÃ©liorÃ© avec performances MK2.','{"type":"objects"}'),
('weapon_doubleaction','Colt M1878','weapons',1500,0,0,'items/weapon_doubleaction.webp','Colt M1878 - Revolver double action classique. Craft MC niveau B.','{"type":"objects"}'),
('weapon_navyrevolver','Revolver Navy','weapons',1500,0,0,'items/weapon_navyrevolver.webp','Revolver Navy - Revolver historique de style militaire.','{"type":"objects"}'),
('weapon_microsmg','Mini Uzi','weapons',1500,0,0,'items/weapon_microsmg.webp','Mini Uzi - Micro-mitraillette compacte Ã  haute cadence. Craftable avec blueprint.','{"type":"objects"}'),
('weapon_smg','H&K MP5','weapons',1500,0,0,'items/weapon_smg.webp','H&K MP5 - Mitraillette polyvalente et prÃ©cise. Craftable avec blueprint.','{"type":"objects"}'),
('weapon_smg_mk2','Weapon Smg Mk2','weapons',1500,0,0,'items/weapon_smg_mk2.webp','MP5 amÃ©liorÃ©e avec accessoires MK2 et meilleures performances.','{"type":"objects"}'),
('weapon_minismg','Weapon Minismg','weapons',1500,0,0,'items/weapon_minismg.webp','Skorpion VZ.61 - Mini-mitraillette ultra-compacte. Craft MC niveau B.','{"type":"objects"}'),
('weapon_combatpdw','Weapon Combatpdw','weapons',1500,0,0,'items/weapon_combatpdw.webp','Mitraillette de combat PDW pour engagements rapprochÃ©s.','{"type":"objects"}'),
('weapon_assaultsmg','Weapon Assaultsmg','weapons',1500,0,0,'items/weapon_assaultsmg.webp','Mitraillette d''assaut Ã  fort taux de pÃ©nÃ©tration.','{"type":"objects"}'),
('weapon_gusenberg','Thompson M1928','weapons',1500,0,0,'items/weapon_gusenberg.webp','Thompson M1928 - Mitraillette historique ''Tommy Gun''. Craft Mafia niveau A.','{"type":"objects"}'),
('weapon_assaultrifle','AK-47','weapons',1500,0,0,'items/weapon_assaultrifle.webp','AK-47 - Fusil d''assaut emblÃ©matique, puissant et fiable. Craft Mafia/Orga niveau S.','{"type":"objects"}'),
('weapon_assaultrifle_mk2','Weapon Assaultrifle Mk2','weapons',1500,0,0,'items/weapon_assaultrifle_mk2.webp','AK-47 amÃ©liorÃ© avec accessoires MK2.','{"type":"objects"}'),
('weapon_carbinerifle','SIG MCX','weapons',1500,0,0,'items/weapon_carbinerifle.webp','SIG MCX - Carabine modulaire 5.56mm, version long barrel. PrÃ©cise et maniable.','{"type":"objects"}'),
('weapon_carbinerifle_mk2','Weapon Carbinerifle Mk2','weapons',1500,0,0,'items/weapon_carbinerifle_mk2.webp','SIG MCX amÃ©liorÃ©e avec accessoires MK2.','{"type":"objects"}'),
('weapon_advancedrifle','Weapon Advancedrifle','weapons',1500,0,0,'items/weapon_advancedrifle.webp','Fusil avancÃ© Ã  haute technologie avec grande cadence de tir.','{"type":"objects"}'),
('weapon_specialcarbine','G36C','weapons',1500,0,0,'items/weapon_specialcarbine.webp','G36C - Carabine spÃ©ciale compacte et maniable.','{"type":"objects"}'),
('weapon_specialcarbine_mk2','Weapon Specialcarbine Mk2','weapons',1500,0,0,'items/weapon_specialcarbine_mk2.webp','G36C amÃ©liorÃ©e avec accessoires MK2.','{"type":"objects"}'),
('weapon_bullpuprifle','Weapon Bullpuprifle','weapons',1500,0,0,'items/weapon_bullpuprifle.webp','Fusil bullpup compact avec chargeur derriÃ¨re la dÃ©tente.','{"type":"objects"}'),
('weapon_bullpuprifle_mk2','Weapon Bullpuprifle Mk2','weapons',1500,0,0,'items/weapon_bullpuprifle_mk2.webp','Fusil bullpup amÃ©liorÃ© avec accessoires MK2.','{"type":"objects"}'),
('weapon_compactrifle','Weapon Compactrifle','weapons',1500,0,0,'items/weapon_compactrifle.webp','Fusil compact adaptÃ© aux espaces restreints et vÃ©hicules.','{"type":"objects"}'),
('weapon_militaryrifle','AUG','weapons',1500,0,0,'items/weapon_militaryrifle.webp','AUG - Fusil militaire autrichien de haute prÃ©cision.','{"type":"objects"}'),
('weapon_heavyrifle','SCAR-H','weapons',1500,0,0,'items/weapon_heavyrifle.webp','SCAR-H - Fusil lourd Ã  fort pouvoir d''arrÃªt.','{"type":"objects"}'),
('weapon_tacticalrifle','M4 tactique','weapons',1500,0,0,'items/weapon_tacticalrifle.webp','M4 tactique - Fusil modulaire pour opÃ©rations spÃ©ciales.','{"type":"objects"}'),
('weapon_battlerifle','Weapon Battlerifle','weapons',1500,0,0,'items/weapon_battlerifle.webp','Fusil de bataille pour engagements Ã  moyenne et longue portÃ©e.','{"type":"objects"}'),
('weapon_ar15','Weapon Ar15','weapons',1500,0,0,'items/weapon_ar15.webp','AR-15 rÃ©servÃ© aux forces de l''ordre (PD).','{"type":"objects"}'),
('weapon_hk416','HK416','weapons',1500,0,0,'items/weapon_hk416.webp','HK416 - Fusil d''assaut de qualitÃ© militaire supÃ©rieure.','{"type":"objects"}'),
('weapon_m4a1cd','M4A1','weapons',1500,0,0,'items/weapon_m4a1cd.webp','M4A1 - Variante personnalisÃ©e haute performance.','{"type":"objects"}'),
('weapon_ks1','KAC KS-1','weapons',1500,0,0,'items/weapon_ks1.webp','KAC KS-1 - Carabine tactique compacte et lÃ©gÃ¨re.','{"type":"objects"}'),
('weapon_pumpshotgun','Remington 870','weapons',1500,0,0,'items/weapon_pumpshotgun.webp','Remington 870 - Fusil Ã  pompe classique et dÃ©vastateur. Craftable avec blueprint.','{"type":"objects"}'),
('weapon_pumpshotgun_mk2','Weapon Pumpshotgun Mk2','weapons',1500,0,0,'items/weapon_pumpshotgun_mk2.webp','Remington 870 amÃ©liorÃ© avec accessoires MK2.','{"type":"objects"}'),
('weapon_sawnoffshotgun','Mossberg 500 Ã  canon sciÃ©','weapons',1500,0,0,'items/weapon_sawnoffshotgun.webp','Mossberg 500 Ã  canon sciÃ© - Compact et destructeur. Craftable avec blueprint.','{"type":"objects"}'),
('weapon_assaultshotgun','UTS-15','weapons',1500,0,0,'items/weapon_assaultshotgun.webp','UTS-15 - Fusil Ã  pompe d''assaut semi-automatique.','{"type":"objects"}'),
('weapon_bullpupshotgun','Weapon Bullpupshotgun','weapons',1500,0,0,'items/weapon_bullpupshotgun.webp','Fusil Ã  pompe bullpup compact et maniable.','{"type":"objects"}'),
('weapon_heavyshotgun','Saiga','weapons',1500,0,0,'items/weapon_heavyshotgun.webp','Saiga - Fusil Ã  pompe lourd semi-automatique Ã  grande capacitÃ©.','{"type":"objects"}'),
('weapon_combatshotgun','SPAS-12','weapons',1500,0,0,'items/weapon_combatshotgun.webp','SPAS-12 - Fusil Ã  pompe de combat polyvalent. Craft MC niveau S.','{"type":"objects"}'),
('weapon_dbshotgun','Fusil Ã  double canon','weapons',1500,0,0,'items/weapon_dbshotgun.webp','Fusil Ã  double canon - Deux coups dÃ©vastateurs.','{"type":"objects"}'),
('weapon_autoshotgun','Striker','weapons',1500,0,0,'items/weapon_autoshotgun.webp','Striker - Fusil Ã  pompe automatique Ã  barillet rotatif.','{"type":"objects"}'),
('weapon_m870','M870','weapons',1500,0,0,'items/weapon_m870.webp','M870 - Fusil Ã  pompe tactique pour les forces de l''ordre.','{"type":"objects"}'),
('weapon_sniperrifle','L96','weapons',1500,0,0,'items/weapon_sniperrifle.webp','L96 - Fusil sniper bolt-action de haute prÃ©cision.','{"type":"objects"}'),
('weapon_heavysniper','Weapon Heavysniper','weapons',1500,0,0,'items/weapon_heavysniper.webp','Fusil sniper lourd anti-matÃ©riel Ã  trÃ¨s longue portÃ©e.','{"type":"objects"}'),
('weapon_heavysniper_mk2','Weapon Heavysniper Mk2','weapons',1500,0,0,'items/weapon_heavysniper_mk2.webp','Sniper lourd amÃ©liorÃ© avec munitions spÃ©ciales MK2.','{"type":"objects"}'),
('weapon_marksmanrifle','Weapon Marksmanrifle','weapons',1500,0,0,'items/weapon_marksmanrifle.webp','Fusil de tireur d''Ã©lite semi-automatique Ã  moyenne portÃ©e.','{"type":"objects"}'),
('weapon_marksmanrifle_mk2','Weapon Marksmanrifle Mk2','weapons',1500,0,0,'items/weapon_marksmanrifle_mk2.webp','Fusil de tireur amÃ©liorÃ© avec accessoires MK2.','{"type":"objects"}'),
('weapon_precisionrifle','Weapon Precisionrifle','weapons',1500,0,0,'items/weapon_precisionrifle.webp','Fusil de prÃ©cision bolt-action pour le tir Ã  trÃ¨s longue distance.','{"type":"objects"}'),
('weapon_pdpt700','Remington M700','weapons',1500,0,0,'items/weapon_pdpt700.webp','Remington M700 - Fusil de prÃ©cision rÃ©servÃ© aux forces de l''ordre (PD).','{"type":"objects"}'),
('weapon_mg','Weapon Mg','weapons',1500,0,0,'items/weapon_mg.webp','Mitrailleuse lÃ©gÃ¨re Ã  haute cadence de tir et grande capacitÃ©.','{"type":"objects"}'),
('weapon_combatmg','Weapon Combatmg','weapons',1500,0,0,'items/weapon_combatmg.webp','Mitrailleuse de combat avec bipied intÃ©grÃ© pour le tir soutenu.','{"type":"objects"}'),
('weapon_combatmg_mk2','Weapon Combatmg Mk2','weapons',1500,0,0,'items/weapon_combatmg_mk2.webp','Mitrailleuse de combat amÃ©liorÃ©e avec accessoires MK2.','{"type":"objects"}'),
('weapon_compactlauncher','Weapon Compactlauncher','weapons',1500,0,0,'items/weapon_compactlauncher.webp','Lance-grenades compact utilisable en vÃ©hicule.','{"type":"objects"}'),
('weapon_hominglauncher','Weapon Hominglauncher','weapons',1500,0,0,'items/weapon_hominglauncher.webp','Lance-missiles Ã  tÃªte chercheuse. Verrouillage automatique sur cible.','{"type":"objects"}'),
('weapon_firework','Weapon Firework','weapons',1500,0,0,'items/weapon_firework.webp','Lanceur pyrotechnique tirant des feux d''artifice festifs.','{"type":"objects"}'),
('weapon_lesslauncher','Weapon Lesslauncher','weapons',1500,0,0,'items/weapon_lesslauncher.webp','Lanceur 40mm non-lÃ©tal pour les forces de l''ordre.','{"type":"objects"}'),
('weapon_bat','Weapon Bat','weapons',1500,0,0,'items/weapon_bat.webp','Batte de baseball en bois. Arme de mÃªlÃ©e contondante.','{"type":"objects"}'),
('weapon_bottle','Weapon Bottle','weapons',1500,0,0,'items/weapon_bottle.webp','Bouteille cassÃ©e improvisÃ©e comme arme tranchante.','{"type":"objects"}'),
('weapon_crowbar','Weapon Crowbar','weapons',1500,0,0,'items/weapon_crowbar.webp','Pied de biche mÃ©tallique. Outil polyvalent et arme de mÃªlÃ©e.','{"type":"objects"}'),
('weapon_flashlight','Weapon Flashlight','weapons',1500,0,0,'items/weapon_flashlight.webp','Lampe torche Maglite utilisable comme arme contondante.','{"type":"objects"}'),
('weapon_golfclub','Weapon Golfclub','weapons',1500,0,0,'items/weapon_golfclub.webp','Club de golf dÃ©tournÃ© en arme de mÃªlÃ©e.','{"type":"objects"}'),
('weapon_hammer','Weapon Hammer','weapons',1500,0,0,'items/weapon_hammer.webp','Marteau de chantier. Outil et arme contondante.','{"type":"objects"}'),
('weapon_hatchet','Weapon Hatchet','weapons',1500,0,0,'items/weapon_hatchet.webp','Hachette compacte, utile pour couper et se dÃ©fendre.','{"type":"objects"}'),
('weapon_knife','Weapon Knife','weapons',1500,0,0,'items/weapon_knife.webp','Couteau de combat Ã  lame fixe. Arme de mÃªlÃ©e tranchante. Craft Gang niveau D.','{"type":"objects"}'),
('weapon_knuckle','Weapon Knuckle','weapons',1500,0,0,'items/weapon_knuckle.webp','Poing amÃ©ricain en mÃ©tal renforÃ§ant les coups de poing. Craft Gang niveau D.','{"type":"objects"}'),
('weapon_machete','Weapon Machete','weapons',1500,0,0,'items/weapon_machete.webp','Machette Ã  lame large pour le combat rapprochÃ©. Craft Gang niveau C.','{"type":"objects"}'),
('weapon_nightstick','Weapon Nightstick','weapons',1500,0,0,'items/weapon_nightstick.webp','Matraque de police pour le maintien de l''ordre.','{"type":"objects"}'),
('weapon_poolcue','Weapon Poolcue','weapons',1500,0,0,'items/weapon_poolcue.webp','Queue de billard dÃ©tournÃ©e en arme de mÃªlÃ©e.','{"type":"objects"}'),
('weapon_sledgehammer','Weapon Sledgehammer','weapons',1500,0,0,'items/weapon_sledgehammer.webp','Masse de dÃ©molition Ã  deux mains. TrÃ¨s lourde et puissante. Craft Gang niveau C.','{"type":"objects"}'),
('weapon_stone_hatchet','Weapon Stone Hatchet','weapons',1500,0,0,'items/weapon_stone_hatchet.webp','Hachette primitive en pierre. Arme de mÃªlÃ©e rustique.','{"type":"objects"}'),
('weapon_switchblade','Weapon Switchblade','weapons',1500,0,0,'items/weapon_switchblade.webp','Couteau Ã  cran d''arrÃªt, compact et dissimulable. Craft Gang niveau D.','{"type":"objects"}'),
('weapon_wrench','Weapon Wrench','weapons',1500,0,0,'items/weapon_wrench.webp','ClÃ© anglaise utilisable comme arme contondante.','{"type":"objects"}'),
('weapon_battleaxe','Weapon Battleaxe','weapons',1500,0,0,'items/weapon_battleaxe.webp','Hache de guerre mÃ©diÃ©vale Ã  deux tranchants.','{"type":"objects"}'),
('weapon_aspbaton','Weapon Aspbaton','weapons',1500,0,0,'items/weapon_aspbaton.webp','Matraque tÃ©lescopique ASP rÃ©servÃ©e aux forces de l''ordre.','{"type":"objects"}'),
('weapon_stungun','Weapon Stungun','weapons',1500,0,0,'items/weapon_stungun.webp','Taser standard des forces de l''ordre. Neutralise temporairement la personne visÃ©e.','{"type":"objects"}'),
('weapon_taserx','Taser X jaune','weapons',1500,0,0,'items/weapon_taserx.webp','Taser X jaune - Version amÃ©liorÃ©e du taser standard.','{"type":"objects"}'),
('weapon_gtaserx','Taser X vert','weapons',1500,0,0,'items/weapon_gtaserx.webp','Taser X vert - Variante verte du taser amÃ©liorÃ©.','{"type":"objects"}'),
('weapon_beanbag','Weapon Beanbag','weapons',1500,0,0,'items/weapon_beanbag.webp','Fusil Ã  beanbag non-lÃ©tal pour neutraliser sans tuer.','{"type":"objects"}'),
('weapon_beanbag2','Fusil Ã  beanbag orange','weapons',1500,0,0,'items/weapon_beanbag2.webp','Fusil Ã  beanbag orange - Variante non-lÃ©tale.','{"type":"objects"}'),
('weapon_bzgas','Weapon Bzgas','weapons',1500,0,0,'items/weapon_bzgas.webp','Grenade de gaz BZ incapacitant. Usage maintien de l''ordre.','{"type":"objects"}'),
('weapon_fireextinguisher','Weapon Fireextinguisher','weapons',1500,0,0,'items/weapon_fireextinguisher.webp','Extincteur utilisable pour Ã©teindre les incendies.','{"type":"objects"}'),
('weapon_petrolcan','Weapon Petrolcan','weapons',1500,0,0,'items/weapon_petrolcan.webp','Bidon d''essence permettant de ravitailler ou crÃ©er des traÃ®nÃ©es inflammables.','{"type":"objects"}'),
('weapon_flare','Weapon Flare','weapons',1500,0,0,'items/weapon_flare.webp','FusÃ©e de dÃ©tresse lumineuse pour signaler sa position.','{"type":"objects"}'),
('weapon_flaregun','Weapon Flaregun','weapons',1500,0,0,'items/weapon_flaregun.webp','Pistolet de dÃ©tresse tirant des fusÃ©es Ã©clairantes.','{"type":"objects"}'),
('weapon_railgun','Weapon Railgun','weapons',1500,0,0,'items/weapon_railgun.webp','Fusil de laser game pour les activitÃ©s rÃ©crÃ©atives.','{"type":"objects"}'),
('weapon_raycarbine','Weapon Raycarbine','weapons',1500,0,0,'items/weapon_raycarbine.webp','Carabine laser futuriste Ã  usage rÃ©crÃ©atif.','{"type":"objects"}'),
('weapon_rayminigun','Weapon Rayminigun','weapons',1500,0,0,'items/weapon_rayminigun.webp','Minigun laser futuriste Ã  usage rÃ©crÃ©atif.','{"type":"objects"}'),
('weapon_raypistol','Weapon Raypistol','weapons',1500,0,0,'items/weapon_raypistol.webp','Pistolet laser futuriste Ã  usage rÃ©crÃ©atif.','{"type":"objects"}'),
('weapon_musket','Weapon Musket','weapons',1500,0,0,'items/weapon_musket.webp','Mousquet Ã  poudre noire. Arme historique utilisÃ©e pour la chasse.','{"type":"objects"}'),
('weapon_grenade','Weapon Grenade','weapons',1500,0,0,'items/weapon_grenade.webp','Grenade Ã  fragmentation explosive avec dÃ©lai de dÃ©tonation.','{"type":"objects"}'),
('weapon_molotov','Weapon Molotov','weapons',1500,0,0,'items/weapon_molotov.webp','Cocktail Molotov incendiaire. CrÃ©e une zone de feu Ã  l''impact.','{"type":"objects"}'),
('weapon_pipebomb','Weapon Pipebomb','weapons',1500,0,0,'items/weapon_pipebomb.webp','Bombe artisanale fabriquÃ©e avec des matÃ©riaux de rÃ©cupÃ©ration.','{"type":"objects"}'),
('weapon_stickybomb','Weapon Stickybomb','weapons',1500,0,0,'items/weapon_stickybomb.webp','Bombe collante C4 dÃ©clenchable Ã  distance.','{"type":"objects"}'),
('weapon_ball','Weapon Ball','weapons',1500,0,0,'items/weapon_ball.webp','Balle de baseball. Projectile inoffensif.','{"type":"objects"}'),
('weapon_snowball','Weapon Snowball','weapons',1500,0,0,'items/weapon_snowball.webp','Boule de neige festive. Parfaitement inoffensive.','{"type":"objects"}'),
('weapon_airsoftburst','Weapon Airsoftburst','weapons',1500,0,0,'items/weapon_airsoftburst.webp','RÃ©plique airsoft en mode burst. Utilise des billes en plastique.','{"type":"objects"}'),
('weapon_airsoftc4a1','Weapon Airsoftc4a1','weapons',1500,0,0,'items/weapon_airsoftc4a1.webp','RÃ©plique airsoft C4A1. Fusil d''assaut pour le loisir.','{"type":"objects"}'),
('weapon_airsoftdrago','Weapon Airsoftdrago','weapons',1500,0,0,'items/weapon_airsoftdrago.webp','RÃ©plique airsoft Drago. Pistolet compact de loisir.','{"type":"objects"}'),
('weapon_airsoftfalcon57','Weapon Airsoftfalcon57','weapons',1500,0,0,'items/weapon_airsoftfalcon57.webp','RÃ©plique airsoft Falcon-57. Pistolet de loisir.','{"type":"objects"}'),
('weapon_airsoftgk36','Weapon Airsoftgk36','weapons',1500,0,0,'items/weapon_airsoftgk36.webp','RÃ©plique airsoft GK36. Fusil compact de loisir.','{"type":"objects"}'),
('weapon_airsoftkalash47','Weapon Airsoftkalash47','weapons',1500,0,0,'items/weapon_airsoftkalash47.webp','RÃ©plique airsoft Kalash-47. RÃ©plique AK pour le loisir.','{"type":"objects"}'),
('weapon_airsoftmq14','Weapon Airsoftmq14','weapons',1500,0,0,'items/weapon_airsoftmq14.webp','RÃ©plique airsoft MQ14. Fusil lourd de loisir.','{"type":"objects"}'),
('weapon_airsoftphantom5','Weapon Airsoftphantom5','weapons',1500,0,0,'items/weapon_airsoftphantom5.webp','RÃ©plique airsoft Phantom-5. SMG compact de loisir.','{"type":"objects"}'),
('weapon_airsoftpredator90','Weapon Airsoftpredator90','weapons',1500,0,0,'items/weapon_airsoftpredator90.webp','RÃ©plique airsoft Predator-90. Fusil Ã  pompe de loisir.','{"type":"objects"}'),
('weapon_airsoftr594','Weapon Airsoftr594','weapons',1500,0,0,'items/weapon_airsoftr594.webp','RÃ©plique airsoft R594. Mitrailleuse de loisir.','{"type":"objects"}'),
('weapon_airsoftstorm','Weapon Airsoftstorm','weapons',1500,0,0,'items/weapon_airsoftstorm.webp','RÃ©plique airsoft Storm. Fusil d''assaut de loisir.','{"type":"objects"}'),
('weapon_airsoftt870','Weapon Airsoftt870','weapons',1500,0,0,'items/weapon_airsoftt870.webp','RÃ©plique airsoft Tactical 870. Fusil Ã  pompe de loisir.','{"type":"objects"}'),
('weapon_airsofttitan','Weapon Airsofttitan','weapons',1500,0,0,'items/weapon_airsofttitan.webp','RÃ©plique airsoft Titan. Pistolet compact de loisir.','{"type":"objects"}'),
('weapon_airsoftviper','Weapon Airsoftviper','weapons',1500,0,0,'items/weapon_airsoftviper.webp','RÃ©plique airsoft Viper. SMG de loisir.','{"type":"objects"}'),
('weapon_airsoftxte','Weapon Airsoftxte','weapons',1500,0,0,'items/weapon_airsoftxte.webp','RÃ©plique airsoft XTE. Pistolet de loisir.','{"type":"objects"}'),
('burger_classic','Burger Classic','items',100,0,0,'items/burger_classic.webp','Burger classique du BurgerShot. Restaure 40% de faim. IngrÃ©dients : pain, steak, fromage, salade, sauce.','{"type":"consumable"}'),
('burger_epice','Burger Epice','items',100,0,0,'items/burger_epice.webp','Burger Ã©picÃ© du BurgerShot avec sauce piquante. Restaure 45% de faim.','{"type":"consumable"}'),
('burger_veggie','Burger Veggie','items',100,0,0,'items/burger_veggie.webp','Burger vÃ©gÃ©tarien du BurgerShot avec steak veggie. Restaure 35% de faim.','{"type":"consumable"}'),
('pain_burger','Pain Burger','items',100,0,0,'items/pain_burger.webp','Pain Ã  burger moelleux, base essentielle pour la prÃ©paration des burgers.','{"type":"objects"}'),
('steak_boeuf_cru','Steak Boeuf Cru','items',100,0,0,'items/steak_boeuf_cru.webp','Steak de boeuf cru Ã  cuire sur le grill du BurgerShot.','{"type":"objects"}'),
('steak_boeuf_cuit','Steak Boeuf Cuit','items',100,0,0,'items/steak_boeuf_cuit.webp','Steak de boeuf grillÃ©, prÃªt Ã  garnir un burger.','{"type":"objects"}'),
('steak_vegetarien_cru','Steak Vegetarien Cru','items',100,0,0,'items/steak_vegetarien_cru.webp','Steak vÃ©gÃ©tarien cru Ã  base de lÃ©gumes, Ã  cuire.','{"type":"objects"}'),
('steak_vegetarien','Steak Vegetarien','items',100,0,0,'items/steak_vegetarien.webp','Steak vÃ©gÃ©tarien cuit, alternative sans viande pour burgers.','{"type":"objects"}'),
('sauce_burgershot','Sauce Burgershot','items',100,0,0,'items/sauce_burgershot.webp','Sauce signature du BurgerShot pour garnir les burgers.','{"type":"objects"}'),
('sauce_epice','Sauce Epice','items',100,0,0,'items/sauce_epice.webp','Sauce Ã©picÃ©e piquante pour relever les plats.','{"type":"objects"}'),
('sac_burgershot','Sac Burgershot','items',100,0,0,'items/sac_burgershot.webp','Sac de livraison BurgerShot pour les commandes Ã  emporter.','{"type":"objects"}'),
('pizza_margherita','Pizza Margherita','items',100,0,0,'items/pizza_margherita.webp','Pizza Margherita classique cuite au four. Restaure 45% de faim.','{"type":"consumable"}'),
('pizza_margherita_crue','Pizza Margherita Crue','items',100,0,0,'items/pizza_margherita_crue.webp','Pizza Margherita crue prÃªte Ã  Ãªtre enfournÃ©e.','{"type":"objects"}'),
('pizza_pepperoni','Pizza Pepperoni','items',100,0,0,'items/pizza_pepperoni.webp','Pizza Pepperoni garnie de rondelles de pepperoni. Restaure 45% de faim.','{"type":"consumable"}'),
('pizza_pepperoni_crue','Pizza Pepperoni Crue','items',100,0,0,'items/pizza_pepperoni_crue.webp','Pizza Pepperoni crue prÃªte Ã  Ãªtre enfournÃ©e.','{"type":"objects"}'),
('pizza_champignon','Pizza Champignon','items',100,0,0,'items/pizza_champignon.webp','Pizza aux champignons frais. Restaure 40% de faim.','{"type":"consumable"}'),
('pizza_champignon_crue','Pizza Champignon Crue','items',100,0,0,'items/pizza_champignon_crue.webp','Pizza aux champignons crue prÃªte Ã  Ãªtre enfournÃ©e.','{"type":"objects"}'),
('pizza_4fromages','Pizza 4fromages','items',100,0,0,'items/pizza_4fromages.webp','Pizza 4 Fromages gratinÃ©e mozzarella, parmesan, gorgonzola et chÃ¨vre. Restaure 50% de faim.','{"type":"consumable"}'),
('pizza_4fromages_crue','Pizza 4fromages Crue','items',100,0,0,'items/pizza_4fromages_crue.webp','Pizza 4 Fromages crue prÃªte Ã  Ãªtre enfournÃ©e.','{"type":"objects"}'),
('pate_pizza','Pate Pizza','items',100,0,0,'items/pate_pizza.webp','PÃ¢te Ã  pizza fraÃ®che, base pour toutes les pizzas.','{"type":"objects"}'),
('sauce_tomate','Sauce Tomate','items',100,0,0,'items/sauce_tomate.webp','Sauce tomate maison pour garnir pizzas et plats.','{"type":"objects"}'),
('mozzarella','Mozzarella','items',100,0,0,'items/mozzarella.webp','Fromage mozzarella fondant pour les pizzas.','{"type":"objects"}'),
('parmesan','Parmesan','items',100,0,0,'items/parmesan.webp','Parmesan affinÃ© en copeaux, fromage italien savoureux.','{"type":"objects"}'),
('gorgonzola','Gorgonzola','items',100,0,0,'items/gorgonzola.webp','Gorgonzola crÃ©meux Ã  pÃ¢te persillÃ©e, fromage italien typÃ©.','{"type":"objects"}'),
('chevre','Chevre','items',100,0,0,'items/chevre.webp','Fromage de chÃ¨vre frais en rondelles, doux et crÃ©meux.','{"type":"objects"}'),
('pepperoni','Pepperoni','items',100,0,0,'items/pepperoni.webp','Rondelles de pepperoni Ã©picÃ© pour garnir les pizzas.','{"type":"objects"}'),
('basilic','Basilic','items',100,0,0,'items/basilic.webp','Feuilles de basilic frais, herbe aromatique pour la cuisine.','{"type":"objects"}'),
('origan','Origan','items',100,0,0,'items/origan.webp','Origan sÃ©chÃ©, Ã©pice aromatique pour les pizzas et plats italiens.','{"type":"objects"}'),
('champignons','Champignons','items',100,0,0,'items/champignons.webp','Champignons frais pour garnir pizzas et plats.','{"type":"objects"}'),
('ramen','Ramen','items',100,0,0,'items/ramen.webp','Bol de ramen japonais fumant avec nouilles, porc et oeuf. Restaure 50% de faim.','{"type":"consumable"}'),
('sushi','Sushi','items',100,0,0,'items/sushi.webp','Assortiment de sushis frais au saumon et riz vinaigrÃ©. Restaure 45% de faim.','{"type":"consumable"}'),
('pho','Pho','items',100,0,0,'items/pho.webp','Soupe Pho vietnamienne au boeuf et herbes fraÃ®ches. Restaure 45% de faim.','{"type":"consumable"}'),
('nouilles','Nouilles','items',100,0,0,'items/nouilles.webp','Nouilles cuites prÃªtes Ã  Ãªtre utilisÃ©es dans les recettes.','{"type":"objects"}'),
('nouilles_crues','Nouilles Crues','items',100,0,0,'items/nouilles_crues.webp','Nouilles crues Ã  cuire avant utilisation en cuisine.','{"type":"objects"}'),
('riz_cru','Riz Cru','items',100,0,0,'items/riz_cru.webp','Riz cru Ã  cuire, base pour sushis et accompagnements.','{"type":"objects"}'),
('riz_sushi','Riz Sushi','items',100,0,0,'items/riz_sushi.webp','Riz vinaigrÃ© prÃ©parÃ© pour confectionner des sushis.','{"type":"objects"}'),
('vinaigre_riz','Vinaigre Riz','items',100,0,0,'items/vinaigre_riz.webp','Vinaigre de riz pour assaisonner le riz Ã  sushi.','{"type":"objects"}'),
('algues_nori','Algues Nori','items',100,0,0,'items/algues_nori.webp','Feuilles d''algues nori pour envelopper les sushis.','{"type":"objects"}'),
('saumon_cru','Saumon Cru','items',100,0,0,'items/saumon_cru.webp','Filet de saumon cru frais pour la prÃ©paration de sushis.','{"type":"objects"}'),
('porc_chashu','Porc Chashu','items',100,0,0,'items/porc_chashu.webp','Porc Chashu braisÃ©, garniture traditionnelle du ramen.','{"type":"objects"}'),
('oeuf_marine','Oeuf Marine','items',100,0,0,'items/oeuf_marine.webp','Oeuf marinÃ© dans la sauce soja, accompagnement du ramen.','{"type":"objects"}'),
('oignon_vert','Oignon Vert','items',100,0,0,'items/oignon_vert.webp','Oignon vert frais Ã©mincÃ© pour garnir les plats asiatiques.','{"type":"objects"}'),
('bouillon_cru','Bouillon Cru','items',100,0,0,'items/bouillon_cru.webp','Bouillon brut non assaisonnÃ©, base pour les soupes.','{"type":"objects"}'),
('bouillon_parfume','Bouillon Parfume','items',100,0,0,'items/bouillon_parfume.webp','Bouillon parfumÃ© aux Ã©pices, prÃªt pour le pho.','{"type":"objects"}'),
('bouillon_soja','Bouillon Soja','items',100,0,0,'items/bouillon_soja.webp','Bouillon de soja savoureux, base pour le ramen.','{"type":"objects"}'),
('pousses_soja','Pousses Soja','items',100,0,0,'items/pousses_soja.webp','Pousses de soja croquantes pour garnir le pho.','{"type":"objects"}'),
('beignet','Beignet','items',100,0,0,'items/beignet.webp','Beignet dorÃ© et sucrÃ©. Restaure 30% de faim.','{"type":"consumable"}'),
('croissant','Croissant','items',100,0,0,'items/croissant.webp','Croissant au beurre frais et croustillant. Restaure 25% de faim.','{"type":"consumable"}'),
('donut','Donut','items',100,0,0,'items/donut.webp','Donut classique glacÃ©. Restaure 25% de faim.','{"type":"consumable"}'),
('donut_chocolat','Donut Chocolat','items',100,0,0,'items/donut_chocolat.webp','Donut au glaÃ§age chocolat. Restaure 25% de faim.','{"type":"consumable"}'),
('donut_framboise','Donut Framboise','items',100,0,0,'items/donut_framboise.webp','Donut au glaÃ§age framboise. Restaure 25% de faim.','{"type":"consumable"}'),
('pate_a_beignet','Pate A Beignet','items',100,0,0,'items/pate_a_beignet.webp','PÃ¢te Ã  beignet crue, prÃªte Ã  Ãªtre frite.','{"type":"objects"}'),
('pate_a_donut','Pate A Donut','items',100,0,0,'items/pate_a_donut.webp','PÃ¢te Ã  donut crue Ã  cuire et glacer.','{"type":"objects"}'),
('pate_feuilletee','Pate Feuilletee','items',100,0,0,'items/pate_feuilletee.webp','PÃ¢te feuilletÃ©e au beurre pour croissants et viennoiseries.','{"type":"objects"}'),
('glacage_chocolat','Glacage Chocolat','items',100,0,0,'items/glacage_chocolat.webp','GlaÃ§age au chocolat pour les donuts.','{"type":"objects"}'),
('glacage_framboise','Glacage Framboise','items',100,0,0,'items/glacage_framboise.webp','GlaÃ§age Ã  la framboise pour les donuts.','{"type":"objects"}'),
('sucre_glace','Sucre Glace','items',100,0,0,'items/sucre_glace.webp','Sucre glace fin pour saupoudrer les pÃ¢tisseries.','{"type":"objects"}'),
('truite_fumee','Truite Fumee','items',100,0,0,'items/truite_fumee.webp','Truite fumÃ©e grillÃ©e, plat savoureux et riche. Restaure 50% de faim.','{"type":"consumable"}'),
('truite_emballee','Truite Emballee','items',100,0,0,'items/truite_emballee.webp','Truite emballÃ©e fraÃ®che, prÃªte Ã  Ãªtre cuisinÃ©e.','{"type":"objects"}'),
('truite_de_mer','Truite De Mer','items',100,0,0,'items/truite_de_mer.webp','Truite de mer fraÃ®chement pÃªchÃ©e. Poisson de qualitÃ©.','{"type":"objects"}'),
('homard_bleu_cuit','Homard Bleu Cuit','items',100,0,0,'items/homard_bleu_cuit.webp','Homard bleu cuit, mets rare et dÃ©licat. Restaure 55% de faim.','{"type":"consumable"}'),
('homard_bleu_emballe','Homard Bleu Emballe','items',100,0,0,'items/homard_bleu_emballe.webp','Homard bleu emballÃ© frais, prÃªt Ã  Ãªtre cuisinÃ©.','{"type":"objects"}'),
('homard_orange_cuit','Homard Orange Cuit','items',100,0,0,'items/homard_orange_cuit.webp','Homard orange cuit, mets savoureux et gÃ©nÃ©reux. Restaure 55% de faim.','{"type":"consumable"}'),
('homard_orange_emballe','Homard Orange Emballe','items',100,0,0,'items/homard_orange_emballe.webp','Homard orange emballÃ© frais, prÃªt Ã  Ãªtre cuisinÃ©.','{"type":"objects"}'),
('frite','Frite','items',100,0,0,'items/frite.webp','Barquette de frites dorÃ©es et croustillantes. Restaure 15% de faim.','{"type":"consumable"}'),
('frite_crue','Frite Crue','items',100,0,0,'items/frite_crue.webp','Frites surgelÃ©es prÃªtes Ã  frire.','{"type":"objects"}'),
('bread','Bread','items',100,0,0,'items/bread.webp','Pain frais cuit au four, aliment de base nourrissant. Restaure 20% de faim.','{"type":"consumable"}'),
('chocolat_bar','Chocolat Bar','items',100,0,0,'items/chocolat_bar.webp','Barre chocolatÃ©e Ã©nergÃ©tique. Restaure 20% de faim.','{"type":"consumable"}'),
('chips_bowl','Chips Bowl','items',100,0,0,'items/chips_bowl.webp','Paquet de chips croustillantes. Restaure 20% de faim.','{"type":"consumable"}'),
('noisettes','Noisettes','items',100,0,0,'items/noisettes.webp','Noisettes grillÃ©es, en-cas sain et croquant.','{"type":"objects"}'),
('beurre','Beurre','items',100,0,0,'items/beurre.webp','Plaquette de beurre frais pour la cuisine et pÃ¢tisserie.','{"type":"objects"}'),
('fromage','Fromage','items',100,0,0,'items/fromage.webp','Fromage Ã  fondre pour garnir burgers et plats.','{"type":"objects"}'),
('salade','Salade','items',100,0,0,'items/salade.webp','Feuilles de salade fraÃ®che pour garnir les plats.','{"type":"objects"}'),
('oeuf','Oeuf','items',100,0,0,'items/oeuf.webp','Oeuf frais de poule, ingrÃ©dient polyvalent en cuisine.','{"type":"objects"}'),
('lait','Lait','items',100,0,0,'items/lait.webp','Bouteille de lait frais pour les boissons et la cuisine.','{"type":"objects"}'),
('huile_olive','Huile Olive','items',100,0,0,'items/huile_olive.webp','Huile d''olive vierge extra pour la cuisine mÃ©diterranÃ©enne.','{"type":"objects"}'),
('huile_friture','Huile Friture','items',100,0,0,'items/huile_friture.webp','Huile de friture pour la cuisson des frites et beignets.','{"type":"objects"}'),
('boeuf','Boeuf','items',100,0,0,'items/boeuf.webp','Morceau de boeuf cru pour la cuisine.','{"type":"objects"}'),
('meat_boar','Meat Boar','items',100,0,0,'items/meat_boar.webp','Viande de sanglier fraÃ®chement chassÃ©e. Gibier savoureux.','{"type":"objects"}'),
('meat_deer','Meat Deer','items',100,0,0,'items/meat_deer.webp','Viande de cerf tendre issue de la chasse. Gibier noble.','{"type":"objects"}'),
('meat_rabbit','Meat Rabbit','items',100,0,0,'items/meat_rabbit.webp','Viande de lapin chassÃ©. Gibier lÃ©ger et dÃ©licat.','{"type":"objects"}'),
('saumon','Saumon','items',100,0,0,'items/saumon.webp','Saumon frais pÃªchÃ© en mer. Poisson noble trÃ¨s apprÃ©ciÃ©.','{"type":"objects"}'),
('sardine','Sardine','items',100,0,0,'items/sardine.webp','Sardine fraÃ®che, petit poisson argentÃ© pÃªchÃ© en mer.','{"type":"objects"}'),
('anchois','Anchois','items',100,0,0,'items/anchois.webp','Anchois frais pÃªchÃ© en mer, petit poisson savoureux.','{"type":"objects"}'),
('dorade','Dorade','items',100,0,0,'items/dorade.webp','Dorade royale, poisson de qualitÃ© Ã  la chair fine.','{"type":"objects"}'),
('maquereau','Maquereau','items',100,0,0,'items/maquereau.webp','Maquereau frais, poisson gras riche en omÃ©ga-3.','{"type":"objects"}'),
('merlan','Merlan','items',100,0,0,'items/merlan.webp','Merlan, poisson blanc Ã  la chair dÃ©licate.','{"type":"objects"}'),
('bar','Bar','items',100,0,0,'items/bar.webp','Bar (loup de mer), poisson noble prisÃ© des pÃªcheurs.','{"type":"objects"}'),
('red_grapes','Red Grapes','items',100,0,0,'items/red_grapes.webp','Grappe de raisin rosÃ©, rÃ©coltÃ©e dans les vignes pour la production de vin.','{"type":"objects"}'),
('white_grapes','White Grapes','items',100,0,0,'items/white_grapes.webp','Grappe de raisin blanc, utilisÃ©e pour le vin blanc et le vin jaune.','{"type":"objects"}'),
('yellow_grapes','Yellow Grapes','items',100,0,0,'items/yellow_grapes.webp','Grappe de raisin jaune, variÃ©tÃ© spÃ©ciale pour le vin jaune.','{"type":"objects"}'),
('wine_red','Wine Red','items',100,0,0,'items/wine_red.webp','Bouteille de vin rosÃ© de qualitÃ©, issu des vignobles locaux.','{"type":"objects"}'),
('wine_white','Wine White','items',100,0,0,'items/wine_white.webp','Bouteille de vin blanc frais et fruitÃ©.','{"type":"objects"}'),
('wine_yellow','Wine Yellow','items',100,0,0,'items/wine_yellow.webp','Bouteille de vin jaune rare et caractÃ©ristique.','{"type":"objects"}'),
('coffee','Coffee','items',100,0,0,'items/coffee.webp','CafÃ© chaud classique pour un coup de boost. Restaure 15% de soif.','{"type":"consumable"}'),
('espresso_petit','Espresso Petit','items',100,0,0,'items/espresso_petit.webp','Petit espresso serrÃ© et corsÃ©. Restaure 15% de soif.','{"type":"consumable"}'),
('espresso_moyen','Espresso Moyen','items',100,0,0,'items/espresso_moyen.webp','Espresso moyen bien dosÃ©. Restaure 25% de soif.','{"type":"consumable"}'),
('espresso_grand','Espresso Grand','items',100,0,0,'items/espresso_grand.webp','Grand espresso pour les amateurs de cafÃ© fort. Restaure 35% de soif.','{"type":"consumable"}'),
('latte_petit','Latte Petit','items',100,0,0,'items/latte_petit.webp','Petit latte onctueux au lait mousseux. Restaure 15% de soif.','{"type":"consumable"}'),
('latte_moyen','Latte Moyen','items',100,0,0,'items/latte_moyen.webp','Latte moyen crÃ©meux et doux. Restaure 25% de soif.','{"type":"consumable"}'),
('latte_grand','Latte Grand','items',100,0,0,'items/latte_grand.webp','Grand latte gÃ©nÃ©reux pour une pause prolongÃ©e. Restaure 35% de soif.','{"type":"consumable"}'),
('cappuccino_petit','Cappuccino Petit','items',100,0,0,'items/cappuccino_petit.webp','Petit cappuccino avec mousse de lait. Restaure 15% de soif.','{"type":"consumable"}'),
('cappuccino_moyen','Cappuccino Moyen','items',100,0,0,'items/cappuccino_moyen.webp','Cappuccino moyen Ã©quilibrÃ© et mousseux. Restaure 25% de soif.','{"type":"consumable"}'),
('cappuccino_grand','Cappuccino Grand','items',100,0,0,'items/cappuccino_grand.webp','Grand cappuccino crÃ©meux et rÃ©confortant. Restaure 35% de soif.','{"type":"consumable"}'),
('sac_grain_espresso','Sac Grain Espresso','items',100,0,0,'items/sac_grain_espresso.webp','Sac de grains de cafÃ© espresso pour la prÃ©paration.','{"type":"objects"}'),
('sac_grain_latte','Sac Grain Latte','items',100,0,0,'items/sac_grain_latte.webp','Sac de grains de cafÃ© latte, torrÃ©faction douce.','{"type":"objects"}'),
('sac_grain_cappuccino','Sac Grain Cappuccino','items',100,0,0,'items/sac_grain_cappuccino.webp','Sac de grains de cafÃ© cappuccino, torrÃ©faction moyenne.','{"type":"objects"}'),
('granita_citron','Granita Citron','items',100,0,0,'items/granita_citron.webp','Granita au citron glacÃ©e et rafraÃ®chissante. Restaure 30% de soif.','{"type":"consumable"}'),
('granita_tropical','Granita Tropical','items',100,0,0,'items/granita_tropical.webp','Granita aux fruits tropicaux givrÃ©e. Restaure 30% de soif.','{"type":"consumable"}'),
('granita_menthe','Granita Menthe','items',100,0,0,'items/granita_menthe.webp','Granita Ã  la menthe fraÃ®che et vivifiante. Restaure 30% de soif.','{"type":"consumable"}'),
('granita_lagoon','Granita Lagoon','items',100,0,0,'items/granita_lagoon.webp','Granita lagoon bleue exotique. Restaure 30% de soif.','{"type":"consumable"}'),
('sirop_citron','Sirop Citron','items',100,0,0,'items/sirop_citron.webp','Sirop de citron concentrÃ© pour granitas et boissons.','{"type":"objects"}'),
('sirop_tropical','Sirop Tropical','items',100,0,0,'items/sirop_tropical.webp','Sirop tropical fruitÃ© pour granitas et cocktails.','{"type":"objects"}'),
('sirop_menthe','Sirop Menthe','items',100,0,0,'items/sirop_menthe.webp','Sirop de menthe verte pour granitas et boissons.','{"type":"objects"}'),
('sirop_lagoon','Sirop Lagoon','items',100,0,0,'items/sirop_lagoon.webp','Sirop lagoon bleu pour granitas et cocktails exotiques.','{"type":"objects"}'),
('glace_pilee','Glace Pilee','items',100,0,0,'items/glace_pilee.webp','Glace pilÃ©e pour la prÃ©paration de granitas et cocktails.','{"type":"objects"}'),
('milkshake_vanille','Milkshake Vanille','items',100,0,0,'items/milkshake_vanille.webp','Milkshake Ã  la vanille onctueux et crÃ©meux. Restaure 25% de soif.','{"type":"consumable"}'),
('milkshake_chocolat','Milkshake Chocolat','items',100,0,0,'items/milkshake_chocolat.webp','Milkshake au chocolat gourmand et riche. Restaure 25% de soif.','{"type":"consumable"}'),
('milkshake_cafe','Milkshake Cafe','items',100,0,0,'items/milkshake_cafe.webp','Milkshake au cafÃ© pour un plaisir glacÃ© cafÃ©inÃ©. Restaure 20% de soif.','{"type":"consumable"}'),
('glace_vanille','Glace Vanille','items',100,0,0,'items/glace_vanille.webp','Boule de glace vanille pour milkshakes et desserts.','{"type":"objects"}'),
('glace_chocolat','Glace Chocolat','items',100,0,0,'items/glace_chocolat.webp','Boule de glace chocolat pour milkshakes et desserts.','{"type":"objects"}'),
('glace_cafe','Glace Cafe','items',100,0,0,'items/glace_cafe.webp','Boule de glace cafÃ© pour milkshakes et desserts.','{"type":"objects"}'),
('cola','Cola','items',100,0,0,'items/cola.webp','Canette de Cola rafraÃ®chissante. Restaure 25% de soif.','{"type":"consumable"}'),
('cola_25cl','Cola 25cl','items',100,0,0,'items/cola_25cl.webp','Petit gobelet de Cola 25cl. Restaure 15% de soif.','{"type":"consumable"}'),
('cola_33cl','Cola 33cl','items',100,0,0,'items/cola_33cl.webp','Gobelet moyen de Cola 33cl. Restaure 20% de soif.','{"type":"consumable"}'),
('cola_50cl','Cola 50cl','items',100,0,0,'items/cola_50cl.webp','Grand gobelet de Cola 50cl. Restaure 30% de soif.','{"type":"consumable"}'),
('sprunk','Sprunk','items',100,0,0,'items/sprunk.webp','Canette de Sprunk pÃ©tillante au citron vert. Restaure 25% de soif.','{"type":"consumable"}'),
('sprunk_25cl','Sprunk 25cl','items',100,0,0,'items/sprunk_25cl.webp','Petit gobelet de Sprunk 25cl. Restaure 15% de soif.','{"type":"consumable"}'),
('sprunk_33cl','Sprunk 33cl','items',100,0,0,'items/sprunk_33cl.webp','Gobelet moyen de Sprunk 33cl. Restaure 20% de soif.','{"type":"consumable"}'),
('sprunk_50cl','Sprunk 50cl','items',100,0,0,'items/sprunk_50cl.webp','Grand gobelet de Sprunk 50cl. Restaure 30% de soif.','{"type":"consumable"}'),
('fut_cola','Fut Cola','items',100,0,0,'items/fut_cola.webp','FÃ»t de Cola pour les distributeurs et restaurants.','{"type":"objects"}'),
('fut_sprunk','Fut Sprunk','items',100,0,0,'items/fut_sprunk.webp','FÃ»t de Sprunk pour les distributeurs et restaurants.','{"type":"objects"}'),
('water','Water','items',100,0,0,'items/water.webp','Bouteille d''eau plate fraÃ®che et hydratante. Restaure 30% de soif.','{"type":"consumable"}'),
('eau_plate','Eau Plate','items',100,0,0,'items/eau_plate.webp','Bouteille d''eau plate minÃ©rale. Restaure 30% de soif.','{"type":"consumable"}'),
('cafe','Cafe','items',100,0,0,'items/cafe.webp','Tasse de cafÃ© chaud et corsÃ©. Restaure 15% de soif.','{"type":"consumable"}'),
('jus_orange','Jus Orange','items',100,0,0,'items/jus_orange.webp','Jus d''orange frais pressÃ©, riche en vitamines. Restaure 30% de soif.','{"type":"consumable"}'),
('jus_pomme','Jus Pomme','items',100,0,0,'items/jus_pomme.webp','Jus de pomme naturel et rafraÃ®chissant. Restaure 30% de soif.','{"type":"consumable"}'),
('the_glace','The Glace','items',100,0,0,'items/the_glace.webp','ThÃ© glacÃ© dÃ©saltÃ©rant et lÃ©ger. Restaure 30% de soif.','{"type":"consumable"}'),
('limonade','Limonade','items',100,0,0,'items/limonade.webp','Limonade pÃ©tillante faite maison. Restaure 30% de soif.','{"type":"consumable"}'),
('bang','Bang','items',100,0,0,'items/bang.webp','Boisson Ã©nergisante Bang pour un boost d''Ã©nergie.','{"type":"objects"}'),
('empty_bang','Empty Bang','items',100,0,0,'items/empty_bang.webp','Canette de Bang vide. Recyclable.','{"type":"objects"}'),
('biere_blonde_generique','Biere Blonde Generique','items',100,0,0,'items/biere_blonde_generique.webp','BiÃ¨re blonde classique et lÃ©gÃ¨re. Restaure 20% de soif. AlcoolisÃ©e.','{"type":"consumable"}'),
('biere_brune','Biere Brune','items',100,0,0,'items/biere_brune.webp','BiÃ¨re brune aux arÃ´mes torrÃ©fiÃ©s et maltÃ©s. Restaure 20% de soif. AlcoolisÃ©e.','{"type":"consumable"}'),
('biere_ambree','Biere Ambree','items',100,0,0,'items/biere_ambree.webp','BiÃ¨re ambrÃ©e aux notes caramÃ©lisÃ©es. Restaure 20% de soif. AlcoolisÃ©e.','{"type":"consumable"}'),
('biere_blanche','Biere Blanche','items',100,0,0,'items/biere_blanche.webp','BiÃ¨re blanche lÃ©gÃ¨re et fruitÃ©e. Restaure 20% de soif. AlcoolisÃ©e.','{"type":"consumable"}'),
('biere_noire','Biere Noire','items',100,0,0,'items/biere_noire.webp','BiÃ¨re noire robuste de type stout. Restaure 20% de soif. AlcoolisÃ©e.','{"type":"consumable"}'),
('biere_unicorn','Biere Unicorn','items',100,0,0,'items/biere_unicorn.webp','BiÃ¨re brassÃ©e par le Vanilla Unicorn. Restaure 5% de soif. AlcoolisÃ©e.','{"type":"consumable"}'),
('biere_yellowjack','Biere Yellowjack','items',100,0,0,'items/biere_yellowjack.webp','BiÃ¨re brassÃ©e par le Yellow Jack Inn. Restaure 5% de soif. AlcoolisÃ©e.','{"type":"consumable"}'),
('biere_asgard','Biere Asgard','items',100,0,0,'items/biere_asgard.webp','BiÃ¨re brassÃ©e par l''Asgard Bar. Restaure 5% de soif. AlcoolisÃ©e.','{"type":"consumable"}'),
('biere_irishpub','Biere Irishpub','items',100,0,0,'items/biere_irishpub.webp','BiÃ¨re brassÃ©e par l''Irish Pub. Restaure 5% de soif. AlcoolisÃ©e.','{"type":"consumable"}'),
('biere_henhouse','Biere Henhouse','items',100,0,0,'items/biere_henhouse.webp','BiÃ¨re brassÃ©e par le Hen House. Restaure 5% de soif. AlcoolisÃ©e.','{"type":"consumable"}'),
('biere_billard','Biere Billard','items',100,0,0,'items/biere_billard.webp','BiÃ¨re brassÃ©e par le 8Billard. Restaure 5% de soif. AlcoolisÃ©e.','{"type":"consumable"}'),
('vodka','Vodka','items',100,0,0,'items/vodka.webp','Bouteille de vodka pure. Restaure 15% de soif. AlcoolisÃ©e.','{"type":"consumable"}'),
('whisky_sec','Whisky Sec','items',100,0,0,'items/whisky_sec.webp','Verre de whisky sec servi pur. Restaure 15% de soif. AlcoolisÃ©.','{"type":"consumable"}'),
('bourbon','Bourbon','items',100,0,0,'items/bourbon.webp','Bourbon amÃ©ricain aux notes boisÃ©es et vanillÃ©es. Restaure 15% de soif. AlcoolisÃ©.','{"type":"consumable"}'),
('rhum_pur','Rhum Pur','items',100,0,0,'items/rhum_pur.webp','Rhum pur ambrÃ© des CaraÃ¯bes. Restaure 15% de soif. AlcoolisÃ©.','{"type":"consumable"}'),
('tequila','Tequila','items',100,0,0,'items/tequila.webp','Tequila mexicaine, idÃ©ale en shot. Restaure 15% de soif. AlcoolisÃ©e.','{"type":"consumable"}'),
('cognac','Cognac','items',100,0,0,'items/cognac.webp','Cognac franÃ§ais raffinÃ© et chaleureux. Restaure 15% de soif. AlcoolisÃ©.','{"type":"consumable"}'),
('pastis','Pastis','items',100,0,0,'items/pastis.webp','Pastis anisÃ© provenÃ§al, Ã  diluer avec de l''eau. Restaure 15% de soif. AlcoolisÃ©.','{"type":"consumable"}'),
('champagne','Champagne','items',100,0,0,'items/champagne.webp','Bouteille de champagne festif et pÃ©tillant. Restaure 20% de soif. AlcoolisÃ©e.','{"type":"consumable"}'),
('moonshine_generique','Moonshine Generique','items',100,0,0,'items/moonshine_generique.webp','Moonshine artisanal distillÃ© clandestinement. Restaure 15% de soif. AlcoolisÃ©.','{"type":"consumable"}'),
('cidre_generique','Cidre Generique','items',100,0,0,'items/cidre_generique.webp','Cidre artisanal de pomme, doux et fruitÃ©. Restaure 20% de soif. AlcoolisÃ©.','{"type":"consumable"}'),
('mojito','Mojito','items',100,0,0,'items/mojito.webp','Mojito frais Ã  la menthe et au citron vert. Restaure 25% de soif. AlcoolisÃ©.','{"type":"consumable"}'),
('margarita','Margarita','items',100,0,0,'items/margarita.webp','Margarita classique au bord salÃ©. Restaure 25% de soif. AlcoolisÃ©e.','{"type":"consumable"}'),
('pina_colada','Pina Colada','items',100,0,0,'items/pina_colada.webp','Pina Colada tropicale Ã  la noix de coco et ananas. Restaure 25% de soif. AlcoolisÃ©e.','{"type":"consumable"}'),
('cosmopolitan','Cosmopolitan','items',100,0,0,'items/cosmopolitan.webp','Cosmopolitan Ã©lÃ©gant Ã  la canneberge. Restaure 25% de soif. AlcoolisÃ©.','{"type":"consumable"}'),
('bloody_mary','Bloody Mary','items',100,0,0,'items/bloody_mary.webp','Bloody Mary Ã©picÃ© au jus de tomate et vodka. Restaure 25% de soif. AlcoolisÃ©.','{"type":"consumable"}'),
('punch','Punch','items',100,0,0,'items/punch.webp','Punch fruitÃ© et festif, mÃ©lange de rhum et jus. Restaure 25% de soif. AlcoolisÃ©.','{"type":"consumable"}'),
('unicorn_carte','Unicorn Carte','items',100,0,0,'items/unicorn_carte.webp','Carte du Vanilla Unicorn. Permet de consulter le menu du bar.','{"type":"objects"}'),
('yellowjack_carte','Yellowjack Carte','items',100,0,0,'items/yellowjack_carte.webp','Carte du Yellow Jack Inn. Permet de consulter le menu du bar western.','{"type":"objects"}'),
('asgard_carte','Asgard Carte','items',100,0,0,'items/asgard_carte.webp','Carte de l''Asgard Bar. Permet de consulter le menu du bar de plage.','{"type":"objects"}'),
('irishpub_carte','Irishpub Carte','items',100,0,0,'items/irishpub_carte.webp','Carte de l''Irish Pub. Permet de consulter le menu du pub irlandais.','{"type":"objects"}'),
('henhouse_carte','Henhouse Carte','items',100,0,0,'items/henhouse_carte.webp','Carte du Hen House. Permet de consulter le menu du bar fermier.','{"type":"objects"}'),
('billard_carte','Billard Carte','items',100,0,0,'items/billard_carte.webp','Carte du 8Billard. Permet de consulter le menu du bar billard.','{"type":"objects"}'),
('burgershot_carte','Burgershot Carte','items',100,0,0,'items/burgershot_carte.webp','Carte du BurgerShot. Permet de consulter le menu fast-food.','{"type":"objects"}'),
('pizzeria_carte','Pizzeria Carte','items',100,0,0,'items/pizzeria_carte.webp','Carte de la Pizzeria. Permet de consulter le menu pizza.','{"type":"objects"}'),
('pearls_carte','Pearls Carte','items',100,0,0,'items/pearls_carte.webp','Carte du Pearls. Permet de consulter le menu fruits de mer.','{"type":"objects"}'),
('noodle_carte','Noodle Carte','items',100,0,0,'items/noodle_carte.webp','Carte du Noodle Exchange. Permet de consulter le menu asiatique.','{"type":"objects"}'),
('bean_coffee_carte','Bean Coffee Carte','items',100,0,0,'items/bean_coffee_carte.webp','Carte du Bean Coffee. Permet de consulter le menu cafÃ©.','{"type":"objects"}'),
('uwu_cafe_carte','Uwu Cafe Carte','items',100,0,0,'items/uwu_cafe_carte.webp','Carte du UwU Cafe. Permet de consulter le menu cafÃ©-pÃ¢tisserie.','{"type":"objects"}'),
('cocaine','Cocaine','items',100,0,0,'items/cocaine.webp','Substance illÃ©gale provoquant des effets visuels Ã  l''usage.','{"type":"objects"}'),
('meth','Meth','items',100,0,0,'items/meth.webp','Cristaux de mÃ©thamphÃ©tamine. Substance illÃ©gale dangereuse avec effets visuels.','{"type":"objects"}'),
('weed','Weed','items',100,0,0,'items/weed.webp','Herbe de cannabis. Substance illÃ©gale avec effets visuels Ã  l''usage.','{"type":"objects"}'),
('pochon_cocaine','Pochon Cocaine','items',100,0,0,'items/pochon_cocaine.webp','Pochon de cocaÃ¯ne conditionnÃ© pour la revente.','{"type":"objects"}'),
('pochon_meth','Pochon Meth','items',100,0,0,'items/pochon_meth.webp','Pochon de mÃ©thamphÃ©tamine conditionnÃ© pour la revente.','{"type":"objects"}'),
('pochon_weed','Pochon Weed','items',100,0,0,'items/pochon_weed.webp','Pochon de cannabis conditionnÃ© pour la revente.','{"type":"objects"}'),
('pochon_ecstasy','Pochon Ecstasy','items',100,0,0,'items/pochon_ecstasy.webp','Pochon d''ecstasy conditionnÃ© pour la revente.','{"type":"objects"}'),
('pochon_vide','Pochon Vide','items',100,0,0,'items/pochon_vide.webp','Pochon vide pour conditionner des substances illÃ©gales.','{"type":"objects"}'),
('weed_gofast','Weed Gofast','items',100,0,0,'items/weed_gofast.webp','Colis de weed en gros pour le transport rapide.','{"type":"objects"}'),
('cannabis_flower','Cannabis Flower','items',100,0,0,'items/cannabis_flower.webp','Fleur de CBD lÃ©gale aux propriÃ©tÃ©s relaxantes.','{"type":"objects"}'),
('cbd_candy','Cbd Candy','items',100,0,0,'items/cbd_candy.webp','Bonbon au CBD aux vertus apaisantes. LÃ©gal.','{"type":"objects"}'),
('cbd_joint','Cbd Joint','items',100,0,0,'items/cbd_joint.webp','Discret et efficace, idÃ©al pour les amateurs.','{"type":"objects"}'),
('cbd_joint_1','Cbd Joint 1','items',100,0,0,'items/cbd_joint_1.webp','Un Ã©quilibre parfait entre durÃ©e et intensitÃ©, Ã  savourer tranquillement.','{"type":"objects"}'),
('cbd_joint_2','Cbd Joint 2','items',100,0,0,'items/cbd_joint_2.webp','Une fumette longue, puissante et mÃ©morable pour les vrais connaisseurs.','{"type":"objects"}'),
('cbd_leaf','Cbd Leaf','items',100,0,0,'items/cbd_leaf.webp','Feuille de CBD sÃ©chÃ©e pour infusion ou prÃ©paration.','{"type":"objects"}'),
('cbd_oil','Cbd Oil','items',100,0,0,'items/cbd_oil.webp','Huile de CBD concentrÃ©e aux propriÃ©tÃ©s thÃ©rapeutiques.','{"type":"objects"}'),
('cigarette','Cigarette','items',100,0,0,'items/cigarette.webp','Cigarette allumable avec animation de fumÃ©e.','{"type":"consumable"}'),
('cigarette_paquet','Cigarette Paquet','items',100,0,0,'items/cigarette_paquet.webp','Paquet de cigarettes contenant plusieurs unitÃ©s.','{"type":"objects"}'),
('e_cigarette','E Cigarette','items',100,0,0,'items/e_cigarette.webp','Cigarette Ã©lectronique avec vapeur aromatisÃ©e.','{"type":"objects"}'),
('e_cigarette_cbd','E Cigarette Cbd','items',100,0,0,'items/e_cigarette_cbd.webp','IdÃ©al pour dÃ©couvrir le produit ou garder une option discrÃ¨te.','{"type":"objects"}'),
('e_cigarette_cbd_1','E Cigarette Cbd 1','items',100,0,0,'items/e_cigarette_cbd_1.webp','Un excellent compromis entre puissance et praticitÃ©, facile Ã  transporter.','{"type":"objects"}'),
('e_cigarette_cbd_2','E Cigarette Cbd 2','items',100,0,0,'items/e_cigarette_cbd_2.webp','ConcentrÃ©, puissant et rentable, parfait pour les consommateurs rÃ©guliers.','{"type":"objects"}'),
('paper_joint','Paper Joint','items',100,0,0,'items/paper_joint.webp','Feuille Ã  rouler pour confectionner des joints.','{"type":"objects"}'),
('paper_tabacco','Paper Tabacco','items',100,0,0,'items/paper_tabacco.webp','Feuille de tabac pour rouler des cigarettes.','{"type":"objects"}'),
('chalumeau','Chalumeau','items',100,0,0,'items/chalumeau.webp','Chalumeau Ã  dÃ©couper pour le travail des mÃ©taux et le crochetage.','{"type":"objects"}'),
('foreuse','Foreuse','items',100,0,0,'items/foreuse.webp','Foreuse industrielle pour percer les coffres-forts.','{"type":"objects"}'),
('laptop','Laptop','items',100,0,0,'items/laptop.webp','Ordinateur portable pour l''usage quotidien.','{"type":"objects"}'),
('tablet','Tablet','items',100,0,0,'items/tablet.webp','Tablette tactile connectÃ©e avec accÃ¨s aux applications.','{"type":"objects"}'),
('casque_audio','Casque Audio','items',100,0,0,'items/casque_audio.webp','Un casque audio de bonne qualitÃ©, idÃ©al pour Ã©couter de la musique.','{"type":"objects"}'),
('pince','Pince','items',100,0,0,'items/pince.webp','Pince Ã  cheveux utilisable permettant de s''attacher les cheveux.','{"type":"objects"}'),
('pince_serflex','Pince Serflex','items',100,0,0,'items/pince_serflex.webp','Pince coupante pour retirer les serflex et liens.','{"type":"objects"}'),
('serflex','Serflex','items',100,0,0,'items/serflex.webp','Liens de serrage en plastique pour attacher temporairement.','{"type":"objects"}'),
('kit_de_crochetage','Kit De Crochetage','items',100,0,0,'items/kit_de_crochetage.webp','Kit professionnel de crochetage pour ouvrir les serrures.','{"type":"objects"}'),
('kit_de_crochetage_veh','Kit De Crochetage Veh','items',100,0,0,'items/kit_de_crochetage_veh.webp','Kit professionnel de crochetage pour ouvrir les serrures de vÃ©hicules.','{"type":"objects"}'),
('cleankit','Cleankit','items',100,0,0,'items/cleankit.webp','Kit de nettoyage pour entretenir les vÃ©hicules.','{"type":"objects"}'),
('repairkit','Repairkit','items',100,0,0,'items/repairkit.webp','Kit de rÃ©paration mÃ©canique pour remettre un vÃ©hicule en Ã©tat.','{"type":"objects"}'),
('fastrepairkit','Fastrepairkit','items',100,0,0,'items/fastrepairkit.webp','Kit de rÃ©paration d''urgence pour une rÃ©paration rapide sur le terrain.','{"type":"objects"}'),
('kitcarrosserie','Kitcarrosserie','items',100,0,0,'items/kitcarrosserie.webp','Kit de carrosserie pour rÃ©parer les dÃ©gÃ¢ts esthÃ©tiques d''un vÃ©hicule.','{"type":"objects"}'),
('fishroad','Fishroad','items',100,0,0,'items/fishroad.webp','Canne Ã  pÃªche pour attraper des poissons en bord de mer.','{"type":"objects"}'),
('bait','Bait','items',100,0,0,'items/bait.webp','AppÃ¢t vivant pour attirer les poissons sur l''hameÃ§on.','{"type":"objects"}'),
('jumelle','Jumelle','items',100,0,0,'items/jumelle.webp','Jumelles permettant d''observer Ã  longue distance. Zoom interactif.','{"type":"objects"}'),
('megaphone','Megaphone','items',100,0,0,'items/megaphone.webp','MÃ©gaphone amplificateur de voix pour s''adresser Ã  une foule.','{"type":"objects"}'),
('boombox','Boombox','items',100,0,0,'items/boombox.webp','Enceinte portable Bluetooth pour diffuser de la musique dans la rue.','{"type":"objects"}'),
('scuba_mask','Scuba Mask','items',100,0,0,'items/scuba_mask.webp','Masque de plongÃ©e avec tuba pour explorer les fonds marins.','{"type":"objects"}'),
('gadget_parachute','Gadget Parachute','items',100,0,0,'items/gadget_parachute.webp','Parachute dÃ©ployable pour sauter en hauteur en toute sÃ©curitÃ©.','{"type":"objects"}'),
('bmx','Bmx','items',100,0,0,'items/bmx.webp','VÃ©lo BMX pliable Ã  sortir de l''inventaire et utiliser.','{"type":"objects"}'),
('skateboard','Skateboard','items',100,0,0,'items/skateboard.webp','Skateboard utilisable pour se dÃ©placer en ville. Non stockable.','{"type":"objects"}'),
('medikit','Medikit','items',100,0,0,'items/medikit.webp','Kit mÃ©dical d''urgence pour soigner les blessures et restaurer la santÃ©.','{"type":"objects"}'),
('medikit_sams','Medikit Sams','items',100,0,0,'items/medikit_sams.webp','Kit de rÃ©animation professionnel du SAMS. Usage mÃ©dical uniquement.','{"type":"objects"}'),
('band','Band','items',100,0,0,'items/band.webp','Bandage standard pour soigner les blessures lÃ©gÃ¨res.','{"type":"objects"}'),
('band_sams','Band Sams','items',100,0,0,'items/band_sams.webp','Bandage professionnel du SAMS pour les soins mÃ©dicaux.','{"type":"objects"}'),
('bequille','Bequille','items',100,0,0,'items/bequille.webp','BÃ©quille mÃ©dicale pour aider un patient Ã  marcher.','{"type":"objects"}'),
('froulant','Froulant','items',100,0,0,'items/froulant.webp','Fauteuil roulant pour transporter un patient blessÃ©.','{"type":"objects"}'),
('sams_paper_document','Sams Paper Document','items',100,0,0,'items/sams_paper_document.webp','Document mÃ©dical officiel du SAMS.','{"type":"objects"}'),
('ethylotest','Ethylotest','items',100,0,0,'items/ethylotest.webp','Ã‰thylotest pour mesurer le taux d''alcoolÃ©mie d''une personne. Usage police.','{"type":"objects"}'),
('poudre','Poudre','items',100,0,0,'items/poudre.webp','Kit de test de poudre pour analyser des substances suspectes. Usage police uniquement.','{"type":"objects"}'),
('gsr_kit','Gsr Kit','items',100,0,0,'items/gsr_kit.webp','Kit de dÃ©tection de rÃ©sidus de tir (GSR).','{"type":"objects"}'),
('bracelet_electronique','Bracelet Electronique','items',100,0,0,'items/bracelet_electronique.webp','Bracelet Ã©lectronique de surveillance judiciaire. PosÃ© par les forces de l''ordre.','{"type":"objects"}'),
('handcuff','Handcuff','items',100,0,0,'items/handcuff.webp','Menottes mÃ©talliques pour immobiliser un suspect.','{"type":"objects"}'),
('handcuff_key','Handcuff Key','items',100,0,0,'items/handcuff_key.webp','ClÃ© de menottes pour libÃ©rer une personne menottÃ©e.','{"type":"objects"}'),
('herse','Herse','items',100,0,0,'items/herse.webp','Herse dÃ©ployable sur la route pour crever les pneus des vÃ©hicules en fuite.','{"type":"objects"}'),
('sabot','Sabot','items',100,0,0,'items/sabot.webp','Sabot de roue pour immobiliser un vÃ©hicule stationnÃ© illÃ©galement.','{"type":"objects"}'),
('radar_gun','Radar Gun','items',100,0,0,'items/radar_gun.webp','Radar de vitesse portatif pour contrÃ´ler la vitesse des vÃ©hicules.','{"type":"objects"}'),
('fingerprint_scanner','Fingerprint Scanner','items',100,0,0,'items/fingerprint_scanner.webp','Lecteur d''empreintes digitales pour identifier les suspects.','{"type":"objects"}'),
('sactete','Sactete','items',100,0,0,'items/sactete.webp','Sac sur la tÃªte pour aveugler temporairement une personne.','{"type":"objects"}'),
('carte_memoire_bodycam','Carte Memoire Bodycam','items',100,0,0,'items/carte_memoire_bodycam.webp','Carte mÃ©moire pour bodycam policiÃ¨re. Enregistrement des interventions. Non stockable.','{"type":"objects"}'),
('phone','Phone','items',100,0,0,'items/phone.webp','TÃ©lÃ©phone portable avec accÃ¨s aux appels, SMS et applications.','{"type":"objects"}'),
('radio_public','Radio Public','items',100,0,0,'items/radio_public.webp','Radio publique permettant de communiquer sur les frÃ©quences ouvertes.','{"type":"objects"}'),
('radio_job','Radio Job','items',100,0,0,'items/radio_job.webp','Radio professionnelle sur frÃ©quence privÃ©e.','{"type":"objects"}'),
('radio_encoder','Radio Encoder','items',100,0,0,'items/radio_encoder.webp','Encodeur radio pour programmer et sÃ©curiser les frÃ©quences radio.','{"type":"objects"}'),
('keys','Keys','items',100,0,0,'items/keys.webp','ClÃ© de vÃ©hicule permettant de dÃ©marrer et verrouiller votre voiture.','{"type":"objects"}'),
('key_motel','Key Motel','items',100,0,0,'items/key_motel.webp','ClÃ© de chambre de motel pour accÃ©der Ã  votre logement temporaire.','{"type":"objects"}'),
('money','Money','items',0,0,0,'items/money.webp','Argent liquide en billets. Devise principale.','{"type":"objects"}'),
('dirty_money','Dirty Money','items',0,0,0,'items/dirty_money.webp','Argent sale obtenu illÃ©galement. Doit Ãªtre blanchi avant utilisation.','{"type":"objects"}'),
('casino_chips','Casino Chips','items',100,0,0,'items/casino_chips.webp','Jetons de casino Ã©changeables contre de l''argent au comptoir.','{"type":"objects"}'),
('usb_piratage_atm','Usb Piratage Atm','items',100,0,0,'items/usb_piratage_atm.webp','ClÃ© USB de piratage pour hacker les distributeurs automatiques.','{"type":"objects"}'),
('usb_piratage_fleeca','Usb Piratage Fleeca','items',100,0,0,'items/usb_piratage_fleeca.webp','ClÃ© USB de piratage pour forcer l''accÃ¨s aux coffres Fleeca.','{"type":"objects"}'),
('jewelry_hacking_device','Jewelry Hacking Device','items',100,0,0,'items/jewelry_hacking_device.webp','ClÃ© USB spÃ©cialisÃ©e pour hacker le systÃ¨me de sÃ©curitÃ© de la bijouterie.','{"type":"objects"}'),
('jewelry_earrings','Jewelry Earrings','items',100,0,0,'items/jewelry_earrings.webp','Boucles d''oreilles volÃ©es Ã  la bijouterie. Objet de valeur recelable.','{"type":"objects"}'),
('jewelry_necklace','Jewelry Necklace','items',100,0,0,'items/jewelry_necklace.webp','Collier en diamant dÃ©robÃ©. Objet de grande valeur recelable.','{"type":"objects"}'),
('jewelry_ring','Jewelry Ring','items',100,0,0,'items/jewelry_ring.webp','Bague en or volÃ©e. Objet de valeur recelable.','{"type":"objects"}'),
('clothes_bag','Clothes Bag','items',100,0,0,'items/clothes_bag.webp','Sac de vÃªtements contenant une tenue complÃ¨te Ã  enfiler.','{"type":"objects"}'),
('potion_1','Potion 1','items',100,0,0,'items/potion_1.webp','Potion multipliant les gains de farm par 2 pendant 2 heures.','{"type":"objects"}'),
('potion_2','Potion 2','items',100,0,0,'items/potion_2.webp','Potion multipliant les gains de farm par 2 pendant 4 heures.','{"type":"objects"}'),
('potion_3','Potion 3','items',100,0,0,'items/potion_3.webp','Potion multipliant les gains de farm par 2 pendant 6 heures.','{"type":"objects"}'),
('potion_4','Potion 4','items',100,0,0,'items/potion_4.webp','Potion multipliant les gains de farm par 3 pendant 2 heures.','{"type":"objects"}'),
('potion_5','Potion 5','items',100,0,0,'items/potion_5.webp','Potion multipliant les gains de farm par 3 pendant 4 heures.','{"type":"objects"}'),
('potion_6','Potion 6','items',100,0,0,'items/potion_6.webp','Potion multipliant les gains de farm par 3 pendant 6 heures.','{"type":"objects"}'),
('potion_7','Potion 7','items',100,0,0,'items/potion_7.webp','Potion multipliant les gains de farm par 4 pendant 2 heures.','{"type":"objects"}'),
('potion_8','Potion 8','items',100,0,0,'items/potion_8.webp','Potion multipliant les gains de farm par 4 pendant 4 heures.','{"type":"objects"}'),
('potion_9','Potion 9','items',100,0,0,'items/potion_9.webp','Potion multipliant les gains de farm par 4 pendant 6 heures.','{"type":"objects"}'),
('fireworks_box_normal','Fireworks Box Normal','items',100,0,0,'items/fireworks_box_normal.webp','BoÃ®te de feux d''artifice standard. Spectacle pyrotechnique modÃ©rÃ©.','{"type":"objects"}'),
('fireworks_box_mega','Fireworks Box Mega','items',100,0,0,'items/fireworks_box_mega.webp','BoÃ®te de feux d''artifice Mega. Grand spectacle pyrotechnique.','{"type":"objects"}'),
('fireworks_box_ultimate','Fireworks Box Ultimate','items',100,0,0,'items/fireworks_box_ultimate.webp','BoÃ®te de feux d''artifice Ultimate. Spectacle pyrotechnique exceptionnel.','{"type":"objects"}'),
('fireworks_pyro_small','Fireworks Pyro Small','items',100,0,0,'items/fireworks_pyro_small.webp','Petit feu d''artifice pyrotechnique. Effet lumineux discret.','{"type":"objects"}'),
('fireworks_pyro_medium','Fireworks Pyro Medium','items',100,0,0,'items/fireworks_pyro_medium.webp','Feu d''artifice pyrotechnique moyen. Bel effet lumineux.','{"type":"objects"}'),
('fireworks_pyro_large','Fireworks Pyro Large','items',100,0,0,'items/fireworks_pyro_large.webp','Grand feu d''artifice pyrotechnique. Effet spectaculaire.','{"type":"objects"}'),
('fireworks_pyro_mega','Fireworks Pyro Mega','items',100,0,0,'items/fireworks_pyro_mega.webp','Feu d''artifice pyrotechnique Mega. Explosion de couleurs.','{"type":"objects"}'),
('fireworks_pyro_fontain','Fireworks Pyro Fontain','items',100,0,0,'items/fireworks_pyro_fontain.webp','Fontaine pyrotechnique projetant des gerbes d''Ã©tincelles.','{"type":"objects"}'),
('fireworks_pyro_pirate','Fireworks Pyro Pirate','items',100,0,0,'items/fireworks_pyro_pirate.webp','Feu d''artifice pirate avec effets sonores et visuels uniques.','{"type":"objects"}'),
('fireworks_pyro_rug','Fireworks Pyro Rug','items',100,0,0,'items/fireworks_pyro_rug.webp','Tapis pyrotechnique crÃ©ant un effet au sol spectaculaire.','{"type":"objects"}'),
('fireworks_pyro_ruglong','Fireworks Pyro Ruglong','items',100,0,0,'items/fireworks_pyro_ruglong.webp','Tapis pyrotechnique long pour un effet au sol prolongÃ©.','{"type":"objects"}'),
('fireworks_pyro_flare1','Fireworks Pyro Flare1','items',100,0,0,'items/fireworks_pyro_flare1.webp','FusÃ©e pyro Flare I. Effet lumineux en altitude.','{"type":"objects"}'),
('fireworks_pyro_flare2','Fireworks Pyro Flare2','items',100,0,0,'items/fireworks_pyro_flare2.webp','FusÃ©e pyro Flare II. Effet lumineux amÃ©liorÃ©.','{"type":"objects"}'),
('fireworks_pyro_flare3','Fireworks Pyro Flare3','items',100,0,0,'items/fireworks_pyro_flare3.webp','FusÃ©e pyro Flare III. Effet lumineux intense.','{"type":"objects"}'),
('fireworks_rocket','Fireworks Rocket','items',100,0,0,'items/fireworks_rocket.webp','FusÃ©e de feu d''artifice classique avec traÃ®nÃ©e colorÃ©e.','{"type":"objects"}'),
('fireworks_solar_flare','Fireworks Solar Flare','items',100,0,0,'items/fireworks_solar_flare.webp','FusÃ©e Ã©clairante solaire projetant une lumiÃ¨re aveuglante.','{"type":"objects"}'),
('employment_contract','Employment Contract','items',100,0,0,'items/employment_contract.webp','Contrat de travail officiel pour embaucher un employÃ©.','{"type":"objects"}'),
('dynasty_contract','Dynasty Contract','items',100,0,0,'items/dynasty_contract.webp','Contrat de bail Dynasty 8 pour la location d''un logement.','{"type":"objects"}'),
('ticket_gratter','Ticket Gratter','items',100,0,0,'items/ticket_gratter.webp','Ticket Ã  gratter avec possibilitÃ© de gagner entre 500$ et 500 000$.','{"type":"consumable"}'),
('spray','Spray','items',100,0,0,'items/spray.webp','Bombe de peinture pour rÃ©aliser des graffitis sur les murs.','{"type":"objects"}'),
('spray_remover','Spray Remover','items',100,0,0,'items/spray_remover.webp','Produit nettoyant pour effacer les graffitis et tags.','{"type":"objects"}'),
('ltd_box','Ltd Box','items',100,0,0,'items/ltd_box.webp','Carton de livraison LTD pour les missions de livraison.','{"type":"objects"}'),
('plane_hint','Plane Hint','items',100,0,0,'items/plane_hint.webp','Indice de localisation d''un crash d''avion contenant du butin.','{"type":"objects"}'),
('sunken_crate','Sunken Crate','items',100,0,0,'items/sunken_crate.webp','Caisse engloutie rÃ©cupÃ©rÃ©e en plongÃ©e sous-marine. Objet de valeur.','{"type":"objects"}'),
('ancient_relic','Ancient Relic','items',100,0,0,'items/ancient_relic.webp','Relique antique dÃ©couverte en plongÃ©e. Artefact de grande valeur.','{"type":"objects"}'),
('rusty_gold_coin','Rusty Gold Coin','items',100,0,0,'items/rusty_gold_coin.webp','PiÃ¨ce d''or rouillÃ©e trouvÃ©e en plongÃ©e. Objet de collection.','{"type":"objects"}'),
('corne_ivoire','Corne Ivoire','items',100,0,0,'items/corne_ivoire.webp','Corne d''ivoire rare et prÃ©cieuse. Objet de contrebande.','{"type":"objects"}'),
('petrol_barrel','Petrol Barrel','items',100,0,0,'items/petrol_barrel.webp','Baril de pÃ©trole brut. Ressource industrielle prÃ©cieuse.','{"type":"objects"}'),
('empty_barrel','Empty Barrel','items',100,0,0,'items/empty_barrel.webp','Baril vide rÃ©utilisable pour le stockage.','{"type":"objects"}'),
('barley','Barley','items',100,0,0,'items/barley.webp','Grain d''orge utilisÃ© dans la fabrication de biÃ¨re artisanale.','{"type":"objects"}'),
('belier','Belier','items',100,0,0,'items/belier.webp','BÃ©lier de porte pour forcer l''entrÃ©e des portes verrouillÃ©es.','{"type":"objects"}');

