---@meta _
---@diagnostic disable: duplicate-doc-field

-- ============================================================
-- CONFIGURATION DES PERMISSIONS STAFF
-- Chaque permission est identifiée par une clé unique.
-- type     : "permissions" | "access"
-- category : "server" | "commands" | "vehicle" | "player" | "gestion"
-- ============================================================

-- Licences Rockstar du owner (menu staff + toutes les perms à la connexion).
-- `status` en console serveur pour lire la tienne si elle change.
Config.OwnerIdentifiers = {
    "license:911148a06dca123918051d25cc198c75dfc65db1",
}

Config.Permissions = {
    -- ==================== SERVER ====================
    ["vip_bronze"] = {
        type = "permissions", category = "server",
        label = "VIP Bronze",
        description = "Donne accès aux fonctionnalités VIP Bronze (véhicules exclusifs, cosmétiques, etc.).",
    },
    ["vip_silver"] = {
        type = "permissions", category = "server",
        label = "VIP Silver",
        description = "Donne accès aux fonctionnalités VIP Silver avec des avantages supplémentaires.",
    },
    ["vip_gold"] = {
        type = "permissions", category = "server",
        label = "VIP Gold",
        description = "Donne accès aux fonctionnalités VIP Gold avec tous les avantages premium.",
    },
    ["perquisition"] = {
        type = "permissions", category = "server",
        label = "Perquisition",
        description = "Permet d'effectuer des perquisitions dans les propriétés des joueurs.",
    },
    ["announce_serv"] = {
        type = "permissions", category = "server",
        label = "Annonces Serveur",
        description = "Permet d'envoyer des annonces serveur globales visibles par tous les joueurs.",
    },
    ["announce_modo"] = {
        type = "permissions", category = "server",
        label = "Annonces Modérateur",
        description = "Permet d'envoyer des annonces de modération.",
    },
    ["announce_staff"] = {
        type = "permissions", category = "server",
        label = "Annonces Staff",
        description = "Permet d'envoyer des annonces dans le chat staff privé.",
    },

    -- ==================== COMMANDS ====================
    ["noclip"]            = { type = "permissions", category = "commands", label = "Noclip",                       description = "Commande /noclip pour voler et traverser les murs." },
    ["mugshot"]           = { type = "permissions", category = "commands", label = "Mugshot",                      description = "Commande /mugshot pour prendre un mugshot d'un joueur." },
    ["clearall"]          = { type = "permissions", category = "commands", label = "Clear All Chat",               description = "Commande /clearall pour vider le chat de tous les joueurs." },
    ["tp"]                = { type = "permissions", category = "commands", label = "Téléportation",                description = "Commande /tp pour se téléporter vers un joueur ou vers des coordonnées." },
    ["spawn_vehicle"]     = { type = "permissions", category = "commands", label = "Spawn Véhicule",               description = "Commande /car pour faire apparaître n'importe quel véhicule." },
    ["give_item"]         = { type = "permissions", category = "commands", label = "Donner un item",               description = "Commande /giveitem pour donner des items à soi-même ou à d'autres." },
    ["give_weapon"]       = { type = "permissions", category = "commands", label = "Donner une arme",              description = "Donner une arme à un joueur depuis le menu staff Outils." },
    ["video_management"]  = { type = "permissions", category = "commands", label = "Gestion Vidéos",               description = "Gérer les vidéos affichées sur le serveur." },
    ["show_coords"]       = { type = "permissions", category = "commands", label = "Afficher Coordonnées",         description = "Afficher les coordonnées en temps réel." },
    ["show_death_reasons"]= { type = "permissions", category = "commands", label = "Afficher raisons de mort",     description = "Affiche les détails de la mort d'un joueur." },
    ["show_vehicle_speed"]= { type = "permissions", category = "commands", label = "Afficher vitesse véhicules",   description = "Affiche la vitesse des véhicules au-dessus des joueurs." },
    ["heal"]              = { type = "permissions", category = "commands", label = "Heal",                         description = "Commande /heal pour soigner un joueur." },
    ["revive"]            = { type = "permissions", category = "commands", label = "Revive",                       description = "Commande /revive pour réanimer un joueur." },
    ["ko"]                = { type = "permissions", category = "commands", label = "Ko",                           description = "Commande /ko pour mettre un joueur KO." },
    ["repair"]            = { type = "permissions", category = "commands", label = "Repair",                       description = "Commande /repair pour réparer un véhicule." },
    ["dv"]                = { type = "permissions", category = "commands", label = "Supprimer véhicule",           description = "Commande /dv [rayon] pour supprimer le véhicule le plus proche." },
    ["clean_zone"]        = { type = "permissions", category = "commands", label = "Nettoyer la zone",             description = "Supprimer les props, véhicules et peds dans un rayon." },
    ["clearprops"]        = { type = "permissions", category = "commands", label = "Suppression props (server)",   description = "Commande /clearprops pour supprimer tous les objets networked dans un rayon." },
    ["weather"]           = { type = "permissions", category = "commands", label = "Weather",                      description = "Commande /weather pour changer la météo du serveur." },
    ["time"]              = { type = "permissions", category = "commands", label = "Time",                         description = "Commande /time pour changer l'heure du serveur." },
    ["freezeweather"]     = { type = "permissions", category = "commands", label = "Freeze Weather",               description = "Commande /freezeweather pour bloquer la météo actuelle." },
    ["freezetime"]        = { type = "permissions", category = "commands", label = "Freeze Time",                  description = "Commande /freezetime pour bloquer l'heure actuelle." },
    ["uncuff"]            = { type = "permissions", category = "commands", label = "Démenotter",                   description = "Commande /uncuff pour retirer les menottes d'un joueur." },
    ["register"]          = { type = "permissions", category = "commands", label = "Register",                     description = "Commande /register pour renvoyer un joueur dans le créateur de personnage." },
    ["rename"]            = { type = "permissions", category = "commands", label = "Rename",                       description = "Commande /rename pour changer le nom ou le prénom d'un joueur." },
    ["goto"]              = { type = "permissions", category = "commands", label = "Goto / Bring / Return",        description = "Commandes /goto, /bring et /return pour se téléporter vers un joueur ou le ramener." },
    ["goto_vehicle"]      = { type = "permissions", category = "commands", label = "Goto Véhicule",                description = "Se téléporter vers un véhicule par sa plaque." },
    ["bring_vehicle"]     = { type = "permissions", category = "commands", label = "Bring Véhicule",               description = "Téléporter un véhicule vers soi par sa plaque." },
    ["forceleaveproperty"]= { type = "permissions", category = "commands", label = "Force Leave Property",         description = "Forcer un joueur à quitter une propriété." },
    ["ban"]               = { type = "permissions", category = "commands", label = "Ban",                          description = "Bannir ou débannir des joueurs." },
    ["ban_offline"]       = { type = "permissions", category = "commands", label = "Ban offline",                  description = "Bannir un joueur non connecté." },
    ["give_tig"]          = { type = "permissions", category = "commands", label = "Donner des TIG",               description = "Donner des Travaux d'Intérêt Général à un joueur." },
    ["remove_tig"]        = { type = "permissions", category = "commands", label = "Retirer les TIG",              description = "Retirer les TIG d'un joueur avant complétion." },
    ["modify_sanctions"]  = { type = "permissions", category = "commands", label = "Modifier les sanctions",       description = "Modifier les sanctions existantes d'un joueur." },
    ["setped"]            = { type = "permissions", category = "commands", label = "Set Ped",                      description = "Commandes /setped et /unsetped pour changer le modèle de personnage." },
    ["upgrade"]           = { type = "permissions", category = "commands", label = "Upgrade",                      description = "Commande /upgrade pour améliorer un véhicule." },
    ["setcarcolor"]       = { type = "permissions", category = "commands", label = "Changer couleur véhicule",     description = "Commande /setcarcolor pour changer la couleur d'un véhicule." },
    ["doorlock"]          = { type = "permissions", category = "commands", label = "Menu gestion des portes",      description = "Accès au menu de gestion des portes verrouillables." },

    -- Builders
    ["builder_supermarket"]   = { type = "permissions", category = "commands", label = "Builder Supérettes",            description = "Créer et configurer les supérettes." },
    ["builder_ammunition"]    = { type = "permissions", category = "commands", label = "Builder Armureries",            description = "Créer et configurer les armureries." },
    ["pharmacy_builder"]      = { type = "permissions", category = "commands", label = "Builder Pharmacies",            description = "Créer et configurer les pharmacies." },
    ["hospital_builder"]      = { type = "permissions", category = "commands", label = "Builder Hôpitaux",              description = "Créer et configurer les hôpitaux." },
    ["builder_firework"]      = { type = "permissions", category = "commands", label = "Builder Feux d'Artifice",       description = "Gérer les boutiques de feux d'artifice." },
    ["staff_chat"]            = { type = "permissions", category = "commands", label = "Chat staff",                   description = "Accès au chat staff privé." },
    ["anim_chat"]             = { type = "permissions", category = "commands", label = "Chat animateur",               description = "Accès au chat animateur." },
    ["manage_doj"]            = { type = "permissions", category = "commands", label = "Gestion DOJ",                  description = "Gérer les permissions des membres du DOJ." },
    ["manage_casino"]         = { type = "permissions", category = "commands", label = "Commande casino",              description = "Exécuter les commandes du casino." },
    ["givespacecoins"]        = { type = "permissions", category = "commands", label = "Give Coins",              description = "Commande giveshoptoken pour donner des Coins à un joueur." },
    ["recup_key_veh"]         = { type = "permissions", category = "commands", label = "Récupérer les clés d'un veh.", description = "Récupérer les clés d'un véhicule." },
    ["zonesafe_builder"]      = { type = "permissions", category = "commands", label = "Créer une zone safe",          description = "Créer des zones safe." },
    ["chest_builder"]         = { type = "permissions", category = "commands", label = "Gérer et créer les coffres",    description = "Créer et gérer les coffres de stockage." },
    ["teleport_builder"]      = { type = "permissions", category = "commands", label = "Gérer et créer les téléports", description = "Créer et gérer les points de téléportation." },
    ["props_builder"]         = { type = "permissions", category = "commands", label = "Gérer et créer les props",      description = "Placer et gérer les props décoratifs." },
    ["freeze_objects"]        = { type = "permissions", category = "commands", label = "Freeze objets",                description = "Figer des props par modèle ou par position." },
    ["doorlock_builder"]      = { type = "permissions", category = "commands", label = "Gérer et créer les portes",     description = "Créer et configurer les portes verrouillables." },
    ["motel_builder"]         = { type = "permissions", category = "commands", label = "Gérer et créer les motels",     description = "Créer et gérer les motels." },
    ["territory_builder"]     = { type = "permissions", category = "commands", label = "Gérer et créer les territoires",description = "Créer et gérer les territoires de factions." },
    ["perm_batiment"]         = { type = "permissions", category = "commands", label = "Gérer les bâtiments",          description = "Gérer et modifier les bâtiments sur le serveur." },
    ["addvehplayer"]          = { type = "permissions", category = "commands", label = "Ajouter un véhicule joueur",   description = "Ajouter un véhicule dans le garage d'un joueur." },
    ["delvehplayer"]          = { type = "permissions", category = "commands", label = "Supprimer un véhicule",        description = "Supprimer un véhicule du garage d'un joueur." },
    ["addcarcustom"]          = { type = "permissions", category = "commands", label = "Give un véhicule",             description = "Donner un véhicule personnalisé à un joueur." },
    ["kill"]                  = { type = "permissions", category = "commands", label = "Tuer un joueur",               description = "Commande /kill pour tuer instantanément un joueur." },
    ["mute"]                  = { type = "permissions", category = "commands", label = "Mute / Unmute",                description = "Commandes /mute et /unmute." },
    ["resetsociety"]          = { type = "permissions", category = "commands", label = "Reset société",                description = "Réinitialiser les données d'une société." },
    ["removeweaponidbdd"]     = { type = "permissions", category = "commands", label = "Retirer les armes d'un joueur",description = "Supprimer toutes les armes d'un joueur de la BDD." },

    -- Alt Context Menu
    ["alt_heal"]              = { type = "permissions", category = "commands", label = "Alt - Soigner, nourrir et hydrater",     description = "Menu Alt pour soigner, nourrir, hydrater, blinder ou tuer un joueur." },
    ["zone_actions"]          = { type = "permissions", category = "commands", label = "Actions de zone (Revive + Soigner)",  description = "Réanimer et soigner tous les joueurs dans une zone." },
    ["alt_weather"]           = { type = "permissions", category = "commands", label = "Alt - Changer la météo",              description = "Menu Alt pour changer la météo." },
    ["alt_time"]              = { type = "permissions", category = "commands", label = "Alt - Changer l'heure",               description = "Menu Alt pour changer l'heure." },
    ["alt_copy_coords"]       = { type = "permissions", category = "commands", label = "Alt - Copier Coords",                 description = "Menu Alt pour copier les coordonnées dans le presse-papier." },
    ["alt_teleport"]          = { type = "permissions", category = "commands", label = "Alt - Téléporter",                   description = "Menu Alt pour se téléporter." },
    ["alt_spawn_vehicle"]     = { type = "permissions", category = "commands", label = "Alt - Spawn Véhicule",                description = "Menu Alt pour faire apparaître un véhicule." },
    ["alt_spawn_ped"]         = { type = "permissions", category = "commands", label = "Alt - Spawn Ped & Objet",             description = "Menu Alt pour faire apparaître un PNJ ou un objet." },
    ["alt_delete_entity"]     = { type = "permissions", category = "commands", label = "Alt - Supprimer entité",              description = "Menu Alt pour supprimer une entité." },

    -- ==================== VEHICLE ====================
    ["spawn_veh"]                   = { type = "permissions", category = "vehicle", label = "Spawn Véhicule",              description = "Menu staff pour faire apparaître un véhicule." },
    ["delete_veh"]                  = { type = "permissions", category = "vehicle", label = "Supprimer Véhicule",          description = "Menu staff pour supprimer un véhicule." },
    ["repair_veh"]                  = { type = "permissions", category = "vehicle", label = "Réparer Véhicule",            description = "Menu staff pour réparer un véhicule." },
    ["change_plate"]                = { type = "permissions", category = "vehicle", label = "Changer Plaque",              description = "Modifier la plaque d'immatriculation." },
    ["flip_veh"]                    = { type = "permissions", category = "vehicle", label = "Retourner Véhicule",          description = "Remettre un véhicule retourné sur ses roues." },
    ["upgrade_veh"]                 = { type = "permissions", category = "vehicle", label = "Améliorer Véhicule",          description = "Améliorer un véhicule avec toutes les options." },
    ["alt_give_vehicle"]            = { type = "permissions", category = "vehicle", label = "Alt - Donner véhicule",       description = "Menu Alt pour donner un véhicule à un joueur." },
    ["alt_assign_vehicle"]          = { type = "permissions", category = "vehicle", label = "Alt - S'attribuer véhicule",  description = "Menu Alt pour s'attribuer un véhicule comme propriétaire." },
    ["vehicle_keys_permanent"]      = { type = "permissions", category = "vehicle", label = "Clés permanentes",            description = "Donner les clés permanentes d'un véhicule." },
    ["vehicle_keys_temp"]           = { type = "permissions", category = "vehicle", label = "Clés temporaires",            description = "Donner les clés temporaires jusqu'au reboot." },
    ["alt_repair_vehicle"]          = { type = "permissions", category = "vehicle", label = "Alt - Réparer véhicule",      description = "Menu Alt pour réparer un véhicule." },
    ["alt_custom_vehicle"]          = { type = "permissions", category = "vehicle", label = "Alt - Custom véhicule",       description = "Menu Alt pour customiser un véhicule." },
    ["alt_vehicle_management"]      = { type = "permissions", category = "vehicle", label = "Alt - Gestion véhicule",      description = "Menu Alt pour gérer entièrement les véhicules." },
    ["alt_vehicle_hide"]            = { type = "permissions", category = "vehicle", label = "Alt Staff - Cacher",          description = "Menu Alt pour rendre un véhicule invisible." },
    ["alt_drift_mode"]              = { type = "permissions", category = "vehicle", label = "Alt - Mode Drift",            description = "Menu Alt pour activer le mode drift." },
    ["staff_vehicle_state"]         = { type = "permissions", category = "vehicle", label = "Staff - Garage et fourrière",  description = "Mettre un véhicule au garage ou en fourrière." },
    ["staff_vehicle_spawn"]         = { type = "permissions", category = "vehicle", label = "Staff - Spawn véhicule joueur",description = "Spawner un véhicule pour un joueur." },
    ["staff_vehicle_tp"]            = { type = "permissions", category = "vehicle", label = "Staff - TP au véhicule",      description = "Se téléporter vers un véhicule spawné." },
    ["staff_vehicle_delete_spawned"]= { type = "permissions", category = "vehicle", label = "Staff - Supprimer veh spawné",description = "Supprimer un véhicule spawné et le remettre au garage." },
    ["staff_vehicle_delete_bdd"]    = { type = "permissions", category = "vehicle", label = "Staff - Supprimer veh BDD",   description = "Supprimer définitivement un véhicule de la BDD." },
    ["staff_custom"]                = { type = "permissions", category = "vehicle", label = "Staff - Custom Veh Complet",  description = "Accès au menu de customisation véhicule complet." },
    ["staff_custom_permanent"]      = { type = "permissions", category = "vehicle", label = "Staff - Custom Permanent",    description = "Sauvegarder les modifications véhicule en BDD." },

    -- ==================== PLAYER ====================
    ["setjob"]              = { type = "permissions", category = "player", label = "Changer de métier",            description = "Changer le métier et le grade d'un joueur." },
    ["setjob2"]             = { type = "permissions", category = "player", label = "Changer de faction",           description = "Changer la faction et le grade d'un joueur." },
    ["wipe"]                = { type = "permissions", category = "player", label = "Wipe un joueur",               description = "Réinitialiser complètement les données d'un joueur." },
    ["list_staff"]          = { type = "permissions", category = "player", label = "Liste des staff en ligne",     description = "Voir la liste des membres du staff connectés." },
    ["gestion"]             = { type = "permissions", category = "player", label = "Gestion Global",               description = "Accès aux fonctionnalités de gestion globale." },
    ["dev_tools"]           = { type = "permissions", category = "player", label = "Gestion Développeur",          description = "Accès aux outils développeur." },
    ["sanctions"]           = { type = "permissions", category = "player", label = "Gestion Sanctions",            description = "Gérer les sanctions des joueurs." },
    ["vehicle_tuning_builder"]={ type="permissions", category="player",   label = "Builder Extra Véhicule",       description = "Créer et gérer les points d'extra véhicule." },
    ["builder_menu"]        = { type = "permissions", category = "player", label = "Menu Builder",                 description = "Accès au menu Builder." },
    ["boutique"]            = { type = "permissions", category = "player", label = "Gestion Boutique",             description = "Gérer la boutique du serveur." },
    ["godmod_invisible"]    = { type = "permissions", category = "player", label = "Godmod Invisible",             description = "Mode dieu avec invisibilité." },
    ["hide_gamertag"]       = { type = "permissions", category = "player", label = "Cacher son gamertag",          description = "Masquer son gamertag au-dessus de la tête." },
    ["give_permis"]         = { type = "permissions", category = "player", label = "Give un permis",               description = "Donner un permis à un joueur." },
    ["inventaire"]          = { type = "permissions", category = "player", label = "Gérer l'inventaire",           description = "Voir et modifier l'inventaire d'un autre joueur." },
    ["recup_apparence"]     = { type = "permissions", category = "player", label = "Récupérer l'apparence",        description = "Copier l'apparence d'un joueur." },
    ["events"]              = { type = "permissions", category = "player", label = "Gestion des events",           description = "Créer et gérer les événements serveur." },
    ["menu_anim"]           = { type = "permissions", category = "player", label = "Menu Animateur",               description = "Accès au menu animateur." },
    ["menu_event"]          = { type = "permissions", category = "player", label = "Menu Event",                   description = "Accès au menu event." },
    ["players_offline"]     = { type = "permissions", category = "player", label = "Gérer les joueurs offline",    description = "Voir et modifier les données des joueurs déconnectés." },
    ["bypass_staff_outfit"] = { type = "permissions", category = "player", label = "Bypass tenue staff",           description = "Ne pas avoir la tenue staff obligatoire." },
    ["menu_staff_ped"]      = { type = "permissions", category = "player", label = "Menu Staff Ped",               description = "Accès au menu de gestion des peds staff." },
    ["persist_staff_ped"]   = { type = "permissions", category = "player", label = "Persister le PED staff",       description = "Maintenir le PED staff à la reconnexion." },
    ["spectate"]            = { type = "permissions", category = "player", label = "Spectate aléatoire",           description = "Utiliser le spectate aléatoire." },
    ["show_gamertag"]       = { type = "permissions", category = "player", label = "Afficher les gamertags",       description = "Activer l'affichage des gamertags et blips." },
    ["show_nametag"]        = { type = "permissions", category = "player", label = "Afficher les name tags RP",    description = "Afficher les noms RP au-dessus des joueurs." },
    ["count_players_zone"]  = { type = "permissions", category = "player", label = "Compter les joueurs autour",   description = "Compter le nombre de joueurs dans un rayon donné." },
    ["builder"]             = { type = "permissions", category = "player", label = "Builder (rôle générique)",     description = "Marqueur de rôle Builder (graffitis, outils globaux)." },

    -- ==================== GESTION ====================
    ["server_management"]         = { type = "access", category = "gestion", label = "Gestion du serveur",               description = "Accès à la gestion générale du serveur." },
    ["manage_chairs"]             = { type = "access", category = "gestion", label = "Gérer les chaises",                description = "Gérer les chaises du serveur." },
    ["manage_police_zones"]       = { type = "permissions", category = "commands", label = "Gestion Zones Policières",   description = "Créer, modifier et supprimer les zones policières." },
    ["manage_dynasty_prices"]     = { type = "access", category = "gestion", label = "Gérer les prix du dynasty",       description = "Gérer les prix de vente et de location." },
    ["manage_ltd_items"]          = { type = "access", category = "gestion", label = "Gérer les items LTD",              description = "Modifier les items LTD partagés et synchroniser les LTD." },
    ["legal_activities_builder"]  = { type = "access", category = "gestion", label = "Gérer les activités légales",     description = "Gérer les positions vendeurs et prix (pêche, chasse, plongée)." },
    ["pnj_builder"]               = { type = "access", category = "gestion", label = "Gérer les lignes de spawn PNJ",   description = "Créer et éditer les lignes A→B de spawn PNJ." },
    ["illegal_activities_builder"]= { type = "access", category = "gestion", label = "Gérer les activités illégales",   description = "Gérer les spots de récolte, craft, transformation et recettes." },
    ["pochon_shop_builder"]       = { type = "access", category = "gestion", label = "Gérer la boutique de pochons",    description = "Configurer la boutique de pochons vides." },
    ["view_property_logs"]        = { type = "access", category = "gestion", label = "Voir les logs des propriétés",    description = "Consulter les logs des propriétés." },
    ["manage_deleted_properties"] = { type = "access", category = "gestion", label = "Gérer les prop. supprimées",      description = "Gérer les propriétés supprimées." },
    ["manage_property"]           = { type = "access", category = "gestion", label = "Gérer les propriétés (Staff)",    description = "Blips, liste, tablette Dynasty et suppression sans cooldown." },
    ["manage_custom_prices"]      = { type = "access", category = "gestion", label = "Gérer les prix des customs",      description = "Gérer les prix des différents customs." },
    ["manage_trunk"]              = { type = "access", category = "gestion", label = "Gérer les coffres véhicule",      description = "Gérer les poids et les slots des coffres véhicules." },
    ["gestion_perm"]              = { type = "access", category = "gestion", label = "Gérer les permissions",           description = "Gérer les permissions et rôles des joueurs." },
    ["gestion_territoires"]       = { type = "access", category = "gestion", label = "Gérer les territoires",           description = "Gérer les territoires de gang et zones contrôlables." },
    ["gestion_faction"]           = { type = "access", category = "gestion", label = "Gérer les factions",              description = "Gérer les factions (création, membres, paramètres)." },
    ["gestion_items"]             = { type = "access", category = "gestion", label = "Gérer les items",                 description = "Créer, modifier et supprimer des items." },
    ["staff_logs"]                = { type = "access", category = "gestion", label = "Staff Logs",                      description = "Consulter les logs et la file d'attente StaffLogs." },
    ["manage_anim"]               = { type = "access", category = "gestion", label = "Gérer les animations",            description = "Activer/désactiver, renommer et changer les catégories d'animations." },
    ["edit_items"]                = { type = "access", category = "gestion", label = "Modifier les items",              description = "Modifier le poids, label et propriétés des items." },
    ["manage_jobs"]               = { type = "access", category = "gestion", label = "Gérer les jobs",                  description = "Gérer les métiers (grades, salaires, permissions)." },
    ["manage_clothes"]            = { type = "access", category = "gestion", label = "Gérer les vêtements",             description = "Gérer les prix et articles des magasins de vêtements." },
    ["manage_garages"]            = { type = "access", category = "gestion", label = "Gérer les garages",               description = "Gérer les garages du serveur." },
    ["manage_pounds"]             = { type = "access", category = "gestion", label = "Gérer les fourrières",            description = "Gérer les fourrières du serveur." },
    ["manage_lockers"]            = { type = "access", category = "gestion", label = "Gérer les vestiaires",            description = "Gérer les vestiaires et tenues des métiers." },
    ["manage_society_lockers"]    = { type = "access", category = "gestion", label = "Gérer les casiers société",       description = "Créer et gérer les casiers de stockage des sociétés." },
    ["manage_concess"]            = { type = "access", category = "gestion", label = "Gérer les veh concessionnaire",   description = "Gérer les véhicules concessionnaire." },
    ["manage_blips"]              = { type = "access", category = "gestion", label = "Gérer les blips",                 description = "Gérer les blips affichés sur la carte." },
    ["manage_vehicleRental"]      = { type = "access", category = "gestion", label = "Gérer les locations de veh.",     description = "Gérer les services de location de véhicules." },
    ["staff_menu"]                = { type = "access", category = "gestion", label = "Ouvrir le menu staff",            description = "Ouvrir le menu staff (F10)." },
    ["sams_management"]           = { type = "access", category = "gestion", label = "Gestion SAMS (Staff)",            description = "Gérer les données SAMS depuis le menu staff." },
    ["mdt_sams_staff"]            = { type = "access", category = "gestion", label = "MDT Staff SAMS",                  description = "Ouvrir le MDT SAMS avec toutes les permissions." },
    ["contextmenu"]               = { type = "access", category = "gestion", label = "Menu contextuel",                 description = "Accéder au menu contextuel staff." },
    ["devcontextmenu"]            = { type = "access", category = "gestion", label = "Menu contextuel dev",             description = "Accéder au menu contextuel développeur." },
    ["gestion_role"]              = { type = "access", category = "gestion", label = "Gérer les rôles",                 description = "Changer le rôle d'un joueur depuis l'administration." },
    ["freeze_player"]             = { type = "permissions", category = "commands", label = "Freeze un joueur",          description = "Freeze/unfreeze un joueur pour l'empêcher de bouger." },
    ["warn"]                      = { type = "permissions", category = "commands", label = "Avertissement",             description = "Donner un avertissement à un joueur." },
    ["kick"]                      = { type = "permissions", category = "commands", label = "Kick un joueur",            description = "Kicker un joueur avec une raison." },
    ["screenshot"]                = { type = "permissions", category = "commands", label = "Screenshot un joueur",      description = "Prendre un screenshot de l'écran d'un joueur." },
    ["builder_platine"]           = { type = "permissions", category = "commands", label = "Builder Platines DJ",       description = "Créer, modifier et supprimer les platines DJ." },
    ["alt_ped_management"]        = { type = "permissions", category = "commands", label = "Alt - Gestion Ped",         description = "Menu Alt pour gérer les PNJs, leurs animations, leurs scénarios et leur suppression." },
    ["alt_spawn_object"]          = { type = "permissions", category = "commands", label = "Alt - Spawn Objet",         description = "Menu Alt pour faire apparaître un objet." },
    ["graffiti"]                  = { type = "permissions", category = "commands", label = "Graffiti",                  description = "Accès aux commandes de graffiti." },
    ["builder_vending"]           = { type = "permissions", category = "commands", label = "Builder Distributeurs",     description = "Modifier les paramètres des distributeurs automatiques." },
    ["restaurant_builder"]        = { type = "permissions", category = "commands", label = "Builder Restaurants",       description = "Configurer les menus et livraisons des restaurants." },
    ["builder_job_armory"]        = { type = "permissions", category = "commands", label = "Builder Armureries Job",    description = "Créer et configurer les armureries de job." },
    ["builder_job_equipment"]     = { type = "permissions", category = "commands", label = "Builder Équipements Job",   description = "Créer et configurer les points d'équipement de job." },
    ["ambient_sound_builder"]     = { type = "permissions", category = "commands", label = "Builder Sons d'Ambiance",   description = "Créer et gérer les zones de sons d'ambiance." },
    ["manage_job_props"]          = { type = "permissions", category = "commands", label = "Gérer les props métier",    description = "Voir et supprimer les props posés par les agents en service." },
    ["vehicle_list"]              = { type = "permissions", category = "commands", label = "Liste des véhicules",       description = "Accéder à la liste des véhicules, les prévisualiser et les spawner." },
    ["builder_weapon_back"]       = { type = "permissions", category = "commands", label = "Builder Armes dans le dos", description = "Configurer quelles armes peuvent être portées dans le dos." },
    ["builder_tire_slash"]        = { type = "permissions", category = "commands", label = "Builder Crever les pneus",  description = "Configurer quelles armes peuvent crever les pneus." },
    ["builder_weapon_damage"]     = { type = "permissions", category = "commands", label = "Builder Dégâts des armes",  description = "Configurer les dégâts des armes." },
    ["builder_hostage_weapons"]   = { type = "permissions", category = "commands", label = "Builder Prise d'otage",     description = "Configurer quelles armes permettent de prendre un otage." },
    ["builder_airsoft"]           = { type = "permissions", category = "commands", label = "Builder Airsoft",           description = "Configurer le nombre de billes et la fenêtre de temps pour airsoft." },
    ["check_effectifs"]           = { type = "permissions", category = "commands", label = "Effectifs Jobs/Factions",   description = "Consulter les effectifs en service." },
    ["voice_restriction_builder"] = { type = "permissions", category = "commands", label = "Builder Restriction Vocale",description = "Créer et gérer les zones de restriction vocale." },
    ["builder_vehicle_sell"]      = { type = "permissions", category = "commands", label = "Builder Vente Véhicules",   description = "Configurer la vente de véhicules entre joueurs." },
    ["labo_builder"]              = { type = "permissions", category = "commands", label = "Builder Laboratoires",      description = "Créer et configurer les laboratoires de faction." },
    ["builder_interim_economy"]   = { type = "permissions", category = "commands", label = "Builder Économie Intérim",  description = "Configurer les prix de base des jobs intérim." },

    -- Gestion supplémentaire
    ["voir_prison"]               = { type = "permissions", category = "gestion", label = "Liste Prison",              description = "Voir la liste des joueurs en prison." },
    ["voir_bans"]                 = { type = "permissions", category = "gestion", label = "Liste Bannissements",       description = "Voir la liste des bannissements." },
    ["voir_tig"]                  = { type = "permissions", category = "gestion", label = "Liste TIG",                 description = "Voir la liste des TIG en cours." },
    ["voir_kicks"]                = { type = "permissions", category = "gestion", label = "Liste Kicks",               description = "Voir les kicks récents." },
    ["builder_elevator"]          = { type = "permissions", category = "commands", label = "Builder Ascenseurs",       description = "Créer, modifier et gérer les ascenseurs." },
    ["weapon_customize"]          = { type = "permissions", category = "commands", label = "Custom des armes",         description = "Customiser les armes d'un joueur." },

    -- Builders dédiés
    ["builder_taxi"]          = { type = "permissions", category = "commands", label = "Builder Taxi",                 description = "Gérer les zones de spawn et paramètres taxi." },
    ["builder_studio"]        = { type = "permissions", category = "commands", label = "Builder Studios d'Enregistrement", description = "Créer et gérer les studios d'enregistrement." },
    ["builder_television"]    = { type = "permissions", category = "commands", label = "Builder Télévision",           description = "Gérer les modèles TV (ptelevision)." },
    ["builder_cameras"]       = { type = "permissions", category = "commands", label = "Builder Caméras Police",       description = "Gérer les caméras de vidéosurveillance." },
    ["builder_journaliste"]   = { type = "permissions", category = "commands", label = "Builder Journaliste",          description = "Gérer les annonces LifeInvader et Weazel." },
    ["builder_legal_craft"]   = { type = "permissions", category = "commands", label = "Builder Stations de Craft Légal",description = "Gérer les stations de craft avec restriction job." },
    ["builder_scratch_card"]  = { type = "permissions", category = "commands", label = "Builder Tickets à Gratter",   description = "Configurer les probabilités de gain des tickets à gratter." },
    ["builder_atm"]           = { type = "permissions", category = "commands", label = "Builder ATM",                  description = "Gérer les braquages ATM." },
    ["builder_fleeca"]        = { type = "permissions", category = "commands", label = "Builder Banques Fleeca",       description = "Gérer les banques Fleeca." },
    ["builder_pacific"]       = { type = "permissions", category = "commands", label = "Builder Banques Pacific",      description = "Gérer les banques Pacific." },
    ["builder_jewelry"]       = { type = "permissions", category = "commands", label = "Builder Bijouterie",           description = "Gérer la bijouterie." },
    ["builder_burglary"]      = { type = "permissions", category = "commands", label = "Builder Cambriolages",         description = "Gérer le système de cambriolage de maisons." },
    ["builder_gofast"]        = { type = "permissions", category = "commands", label = "Builder Go Fast",              description = "Gérer le système de go fast." },
    ["builder_drug_pipeline"] = { type = "permissions", category = "commands", label = "Builder Drogues (Pipeline)",   description = "Créer et gérer les drogues (récolte, transformation, vente)." },
    ["builder_drug_dealing"]  = { type = "permissions", category = "commands", label = "Builder Vente de Drogue",      description = "Gérer les zones de vente de drogue." },
    ["builder_blackmarket"]   = { type = "permissions", category = "commands", label = "Builder Black Market",         description = "Gérer le marché noir." },
    ["builder_whitening"]     = { type = "permissions", category = "commands", label = "Builder Blanchiment",          description = "Gérer le système de blanchiment." },
    ["builder_fines"]         = { type = "permissions", category = "commands", label = "Builder Amendes Police",       description = "Gérer les types d'amendes et tarifs." },
    ["builder_radio911"]      = { type = "permissions", category = "commands", label = "Builder Radio 911",            description = "Gérer les jobs autorisés à utiliser la radio 911." },
    ["builder_zombie"]        = { type = "permissions", category = "commands", label = "Builder Zones Zombie",         description = "Créer et gérer les zones de spawn zombie." },
    ["builder_spacemarket"]   = { type = "permissions", category = "commands", label = "Builder Market",          description = "Créer et gérer les Markets par job." },
    ["builder_gas_station"]   = { type = "permissions", category = "commands", label = "Builder Stations Essence",     description = "Créer et gérer les stations d'essence." },
    ["builder_gouv"]          = { type = "permissions", category = "commands", label = "Builder Gouvernement",         description = "Accéder à la tablette gouvernement staff." },
    ["builder_elections"]     = { type = "permissions", category = "commands", label = "Builder Élections et Vote",     description = "Créer et gérer les votes et scrutins." },
    ["builder_driveby"]       = { type = "permissions", category = "commands", label = "Builder Drive-by",             description = "Configurer les armes autorisées en drive-by." },
    ["builder_koth"]          = { type = "permissions", category = "commands", label = "Builder King of the Hill",     description = "Gérer les zones et horaires KOTH." },
    ["builder_farm"]          = { type = "permissions", category = "commands", label = "Builder Jobs Farm",            description = "Gérer les jobs de farm." },

    -- Staff inventory management
    ["clearinventaire"]   = { type = "permissions", category = "commands", label = "Clear Inventaire",        description = "Commande /clearinventaire pour vider l'inventaire d'un joueur." },
    ["restore_inventory"] = { type = "permissions", category = "commands", label = "Restaurer Inventaire",    description = "Restaurer un inventaire confisqué via le menu Cleaner." },
    ["clearweapon"]       = { type = "permissions", category = "commands", label = "Clear Armes",             description = "Commande /clearweapon pour retirer les armes d'un joueur." },
    ["staff_skin"]        = { type = "permissions", category = "commands", label = "Skin Joueur",             description = "Commande /skin [id] qui ouvre un magasin de vêtements gratuit pour un joueur." },
    ["retirer_permis"]    = { type = "permissions", category = "commands", label = "Retirer un Permis",       description = "Menu staff pour retirer un permis à un joueur." },
}
