---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- DateTime: 09/02/2026 01:02
---

local model <const> = JobModel.new("dynasty")
                              :setLabel("Dynasty")
                              :activateBuilder("catalog")