---@meta _
---@diagnostic disable: duplicate-doc-field

Config.DefaultWeaponTints = {
    [0] = "skin par défaut",
    [1] = "skin vert",
    [2] = "skin doré",
    [3] = "skin rose",
    [4] = "skin militaire",
    [5] = "skin bleu",
    [6] = "skin orange",
    [7] = "skin platine",
}

Config.MK2WeaponTints = {
    [0]  = "Classic Black",
    [1]  = "Classic Gray",
    [2]  = "Classic Two-Tone",
    [3]  = "Classic White",
    [4]  = "Classic Beige",
    [5]  = "Classic Green",
    [6]  = "Classic Blue",
    [7]  = "Classic Earth",
    [8]  = "Classic Brown & Black",
    [9]  = "Contrast Red",
    [10] = "Contrast Blue",
    [11] = "Contrast Yellow",
    [12] = "Contrast Orange",
    [13] = "Bold Pink",
    [14] = "Bold Purple & Yellow",
    [15] = "Bold Orange",
    [16] = "Bold Green & Purple",
    [17] = "Bold Red Features",
    [18] = "Bold Green Features",
    [19] = "Bold Cyan Features",
    [20] = "Bold Yellow Features",
    [21] = "Bold Red & White",
    [22] = "Bold Blue & White",
    [23] = "Metallic Gold",
    [24] = "Metallic Platinum",
    [25] = "Metallic Gray & Lilac",
    [26] = "Metallic Purple & Lime",
    [27] = "Metallic Red",
    [28] = "Metallic Green",
    [29] = "Metallic Blue",
    [30] = "Metallic White & Aqua",
    [31] = "Metallic Orange & Yellow",
    [32] = "Metallic Red & Yellow"
}

-- Configuration pour le système d'armes dans le dos
Config.WeaponBack = {
    -- Groupes d'armes compatibles avec le port dans le dos (par hash de groupe GTA)
    compatibleGroups = {
        [`GROUP_RIFLE`] = true,    -- Fusils d'assaut uniquement (AK47, M4, etc.)
        -- [`GROUP_SMG`] = true, -- Mitraillettes désactivées
        -- [`GROUP_SHOTGUN`] = true, -- Fusils à pompe désactivés
        -- [`GROUP_SNIPER`] = true, -- Snipers désactivés
        -- [`GROUP_MG`] = true, -- Machine guns désactivées (trop lourdes)
        -- [`GROUP_HEAVY`] = true, -- Armes lourdes désactivées
    },
    -- Armes lourdes (ne peuvent pas être portées dans le dos + restrictions spéciales)
    heavyWeapons = {
        ["WEAPON_COMPACTLAUNCHER"] = true,
        ["WEAPON_GRENADELAUNCHER"] = true,
        ["WEAPON_HOMINGLAUNCHER"] = true,
        ["WEAPON_MINIGUN"] = true,
        ["WEAPON_RAILGUN"] = true,
        ["WEAPON_RPG"] = true,
        ["WEAPON_RAYMINIGUN"] = true,
        ["WEAPON_RAILGUNXM3"] = true,
        ["WEAPON_FIREWORK"] = true,
    },
    bigWeapons = {
        -- SMG
        ["WEAPON_MICROSMG"] = true,
        ["WEAPON_MACHINEPISTOL"] = true,
        ["WEAPON_MINISMG"] = true,
        ["WEAPON_SMG"] = true,
        ["WEAPON_SMG_MK2"] = true,
        ["WEAPON_ASSAULTSMG"] = true,
        ["WEAPON_COMBATPDW"] = true,
        ["WEAPON_TECPISTOL"] = true,
        -- Rifles
        ["WEAPON_ASSAULTRIFLE"] = true,
        ["WEAPON_ASSAULTRIFLE_MK2"] = true,
        ["WEAPON_CARBINERIFLE"] = true,
        ["WEAPON_CARBINERIFLE_MK2"] = true,
        ["WEAPON_ADVANCEDRIFLE"] = true,
        ["WEAPON_SPECIALCARBINE"] = true,
        ["WEAPON_SPECIALCARBINE_MK2"] = true,
        ["WEAPON_BULLPUPRIFLE"] = true,
        ["WEAPON_BULLPUPRIFLE_MK2"] = true,
        ["WEAPON_COMPACTRIFLE"] = true,
        ["WEAPON_MILITARYRIFLE"] = true,
        ["WEAPON_HEAVYRIFLE"] = true,
        ["WEAPON_TACTICALRIFLE"] = true,
        -- Shotguns
        ["WEAPON_PUMPSHOTGUN"] = true,
        ["WEAPON_PUMPSHOTGUN_MK2"] = true,
        ["WEAPON_SAWNOFFSHOTGUN"] = true,
        ["WEAPON_ASSAULTSHOTGUN"] = true,
        ["WEAPON_BULLPUPSHOTGUN"] = true,
        ["WEAPON_MUSKET"] = true,
        ["WEAPON_HEAVYSHOTGUN"] = true,
        ["WEAPON_DBSHOTGUN"] = true,
        ["WEAPON_AUTOSHOTGUN"] = true,
        ["WEAPON_COMBATSHOTGUN"] = true,
        -- Snipers
        ["WEAPON_SNIPERRIFLE"] = true,
        ["WEAPON_HEAVYSNIPER"] = true,
        ["WEAPON_HEAVYSNIPER_MK2"] = true,
        ["WEAPON_MARKSMANRIFLE"] = true,
        ["WEAPON_MARKSMANRIFLE_MK2"] = true,
        ["WEAPON_PRECISIONRIFLE"] = true,
        -- MG
        ["WEAPON_MG"] = true,
        ["WEAPON_COMBATMG"] = true,
        ["WEAPON_COMBATMG_MK2"] = true,
        ["WEAPON_GUSENBERG"] = true,
    },
    -- Paramètres d'attachement (bone spine)
    attachment = {
        bone = 24818, -- SKEL_Spine1
        offset = vector3(0.095, -0.15, -0.02),
        rotation = vector3(0.0, 165.0, -1.0),
    },
}

Config.Weapons = {
    -- Mêlée
    { name = "WEAPON_DAGGER", label = "Dague", melee = true, components = {} },
    { name = "WEAPON_BAT", label = "Batte de baseball", melee = true, components = {} },
    { name = "WEAPON_BATTLEAXE", label = "Hache de combat", melee = true, components = {} },
    {
        name = "WEAPON_KNUCKLE",
        label = "Poing américain",
        melee = true,
        components = {
            { name = "knuckle_base", label = "Base", hash = 'COMPONENT_KNUCKLE_VARMOD_BASE' },
            { name = "knuckle_pimp", label = "Pimp", hash = 'COMPONENT_KNUCKLE_VARMOD_PIMP' },
            { name = "knuckle_ballas", label = "Ballas", hash = 'COMPONENT_KNUCKLE_VARMOD_BALLAS' },
            { name = "knuckle_dollar", label = "Dollar", hash = 'COMPONENT_KNUCKLE_VARMOD_DOLLAR' },
            { name = "knuckle_diamond", label = "Diamant", hash = 'COMPONENT_KNUCKLE_VARMOD_DIAMOND' },
            { name = "knuckle_hate", label = "Haine", hash = 'COMPONENT_KNUCKLE_VARMOD_HATE' },
            { name = "knuckle_love", label = "Amour", hash = 'COMPONENT_KNUCKLE_VARMOD_LOVE' },
            { name = "knuckle_player", label = "Joueur", hash = 'COMPONENT_KNUCKLE_VARMOD_PLAYER' },
            { name = "knuckle_king", label = "Roi", hash = 'COMPONENT_KNUCKLE_VARMOD_KING' },
            { name = "knuckle_vagos", label = "Vagos", hash = 'COMPONENT_KNUCKLE_VARMOD_VAGOS' },
        },
    },
    { name = "WEAPON_BOTTLE", label = "Bouteille cassée", melee = true, components = {} },
    { name = "WEAPON_CROWBAR", label = "Pied de biche", melee = true, components = {} },
    { name = "WEAPON_FLASHLIGHT", label = "Lampe torche", melee = true, components = {} },
    { name = "WEAPON_GOLFCLUB", label = "Club de golf", melee = true, components = {} },
    { name = "WEAPON_HAMMER", label = "Marteau", melee = true, components = {} },
    { name = "WEAPON_HATCHET", label = "Hachette", melee = true, components = {} },
    { name = "WEAPON_KNIFE", label = "Couteau", melee = true, components = {} },
    { name = "WEAPON_MACHETE", label = "Machette", melee = true, components = {} },
    { name = "WEAPON_NIGHTSTICK", label = "Matraque", melee = true, components = {} },
    { name = "WEAPON_WRENCH", label = "Clé à molette", melee = true, components = {} },
    { name = "WEAPON_POOLCUE", label = "Queue de billard", melee = true, components = {} },
    { name = "WEAPON_STONE_HATCHET", label = "Hachette en pierre", melee = true, components = {} },
    {
        name = "WEAPON_SWITCHBLADE",
        label = "Couteau à cran d'arrêt",
        melee = true,
        components = {
            { name = "handle_default", label = "Manche standard", hash = 'COMPONENT_SWITCHBLADE_VARMOD_BASE' },
            { name = "handle_vip", label = "Manche VIP", hash = 'COMPONENT_SWITCHBLADE_VARMOD_VAR1' },
            { name = "handle_bodyguard", label = "Manche garde du corps", hash = 'COMPONENT_SWITCHBLADE_VARMOD_VAR2' },
        },
    },
    -- Pistolets
    {
        name = "WEAPON_APPISTOL",
        label = "Pistolet AP",
        ammo = { label = "Munitions", hash = 'AMMO_PISTOL' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_APPISTOL_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_APPISTOL_CLIP_02' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_PI_FLSH' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_PI_SUPP' },
            { name = "luxary_finish", label = "Finition de luxe", hash = 'COMPONENT_APPISTOL_VARMOD_LUXE' },
        },
    },
    { name = "WEAPON_CERAMICPISTOL", label = "Pistolet en céramique", tints = Config.DefaultWeaponTints, components = {}, ammo = { label = "Munitions", hash = 'AMMO_PISTOL' } },
    {
        name = "WEAPON_COMBATPISTOL",
        label = "Pistolet de combat",
        ammo = { label = "Munitions", hash = 'AMMO_PISTOL' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_COMBATPISTOL_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_COMBATPISTOL_CLIP_02' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_PI_FLSH' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_PI_SUPP' },
            { name = "luxary_finish", label = "Finition de luxe", hash = 'COMPONENT_COMBATPISTOL_VARMOD_LOWRIDER' },
        },
    },
    { name = "WEAPON_DOUBLEACTION", label = "Revolver à double action", tints = Config.DefaultWeaponTints, components = {}, ammo = { label = "Munitions", hash = 'AMMO_PISTOL' } },
    { name = "WEAPON_NAVYREVOLVER", label = "Revolver Navy", tints = Config.DefaultWeaponTints, components = {}, ammo = { label = "Munitions", hash = 'AMMO_PISTOL' } },
    { name = "WEAPON_FLAREGUN", label = "Pistolet de détresse", tints = Config.DefaultWeaponTints, components = {}, ammo = { label = "Fusée éclairante", hash = 'AMMO_FLAREGUN' } },
    { name = "WEAPON_GADGETPISTOL", label = "Pistolet gadget", tints = Config.DefaultWeaponTints, components = {}, ammo = { label = "Munitions", hash = 'AMMO_PISTOL' } },
    {
        name = "WEAPON_HEAVYPISTOL",
        label = "Pistolet lourd",
        ammo = { label = "Munitions", hash = 'AMMO_PISTOL' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_HEAVYPISTOL_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_HEAVYPISTOL_CLIP_02' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_PI_FLSH' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_PI_SUPP' },
            { name = "luxary_finish", label = "Finition de luxe", hash = 'COMPONENT_HEAVYPISTOL_VARMOD_LUXE' },
        },
    },
    {
        name = "WEAPON_REVOLVER",
        label = "Revolver",
        ammo = { label = "Munitions", hash = 'AMMO_PISTOL' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_REVOLVER_CLIP_01' },
            { name = "vip_finish", label = "Finition VIP", hash = 'COMPONENT_REVOLVER_VARMOD_BOSS' },
            { name = "bodyguard_finish", label = "Finition garde du corps", hash = 'COMPONENT_REVOLVER_VARMOD_GOON' },
        },
    },
    {
        name = "WEAPON_REVOLVER_MK2",
        label = "Revolver Mk II",
        ammo = { label = "Munitions", hash = 'AMMO_PISTOL' },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_REVOLVER_MK2_CLIP_01' },
            { name = "ammo_tracer", label = "Munitions traçantes", hash = 'COMPONENT_REVOLVER_MK2_CLIP_TRACER' },
            { name = "ammo_incendiary", label = "Munitions incendiaires", hash = 'COMPONENT_REVOLVER_MK2_CLIP_INCENDIARY' },
            { name = "ammo_hollowpoint", label = "Munitions à pointe creuse", hash = 'COMPONENT_REVOLVER_MK2_CLIP_HOLLOWPOINT' },
            { name = "ammo_fmj", label = "Munitions FMJ", hash = 'COMPONENT_REVOLVER_MK2_CLIP_FMJ' },
            { name = "scope_holo", label = "Viseur holographique", hash = 'COMPONENT_AT_SIGHTS' },
            { name = "scope_small", label = "Petite lunette", hash = 'COMPONENT_AT_SCOPE_MACRO_MK2' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_PI_FLSH' },
            { name = "compensator", label = "Compensateur", hash = 'COMPONENT_AT_PI_COMP_03' },
            { name = "camo_finish", label = "Finition camouflage", hash = 'COMPONENT_REVOLVER_MK2_CAMO' },
            { name = "camo_finish2", label = "Finition camouflage 2", hash = 'COMPONENT_REVOLVER_MK2_CAMO_02' },
            { name = "camo_finish3", label = "Finition camouflage 3", hash = 'COMPONENT_REVOLVER_MK2_CAMO_03' },
            { name = "camo_finish4", label = "Finition camouflage 4", hash = 'COMPONENT_REVOLVER_MK2_CAMO_04' },
            { name = "camo_finish5", label = "Finition camouflage 5", hash = 'COMPONENT_REVOLVER_MK2_CAMO_05' },
            { name = "camo_finish6", label = "Finition camouflage 6", hash = 'COMPONENT_REVOLVER_MK2_CAMO_06' },
            { name = "camo_finish7", label = "Finition camouflage 7", hash = 'COMPONENT_REVOLVER_MK2_CAMO_07' },
            { name = "camo_finish8", label = "Finition camouflage 8", hash = 'COMPONENT_REVOLVER_MK2_CAMO_08' },
            { name = "camo_finish9", label = "Finition camouflage 9", hash = 'COMPONENT_REVOLVER_MK2_CAMO_09' },
            { name = "camo_finish10", label = "Finition camouflage 10", hash = 'COMPONENT_REVOLVER_MK2_CAMO_10' },
            { name = "camo_finish11", label = "Finition camouflage 11", hash = 'COMPONENT_REVOLVER_MK2_CAMO_IND_01' },
        },
    },
    { name = "WEAPON_MARKSMANPISTOL", label = "Pistolet marksman", tints = Config.DefaultWeaponTints, components = {}, ammo = { label = "Munitions", hash = 'AMMO_PISTOL' } },
    {
        name = "WEAPON_PISTOL",
        label = "Pistolet",
        ammo = { label = "Munitions", hash = 'AMMO_PISTOL' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_PISTOL_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_PISTOL_CLIP_02' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_PI_FLSH' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_PI_SUPP_02' },
            { name = "luxary_finish", label = "Finition de luxe", hash = 'COMPONENT_PISTOL_VARMOD_LUXE' },
        },
    },
    {
        name = "WEAPON_PISTOL_MK2",
        label = "Pistolet Mk II",
        ammo = { label = "Munitions", hash = 'AMMO_PISTOL' },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_PISTOL_MK2_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_PISTOL_MK2_CLIP_02' },
            { name = "ammo_tracer", label = "Munitions traçantes", hash = 'COMPONENT_PISTOL_MK2_CLIP_TRACER' },
            { name = "ammo_incendiary", label = "Munitions incendiaires", hash = 'COMPONENT_PISTOL_MK2_CLIP_INCENDIARY' },
            { name = "ammo_hollowpoint", label = "Munitions à pointe creuse", hash = 'COMPONENT_PISTOL_MK2_CLIP_HOLLOWPOINT' },
            { name = "ammo_fmj", label = "Munitions FMJ", hash = 'COMPONENT_PISTOL_MK2_CLIP_FMJ' },
            { name = "scope", label = "Lunette", hash = 'COMPONENT_AT_PI_RAIL' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_PI_FLSH_02' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_PI_SUPP_02' },
            { name = "compensator", label = "Compensateur", hash = 'COMPONENT_AT_PI_COMP' },
            { name = "camo_finish", label = "Finition camouflage", hash = 'COMPONENT_PISTOL_MK2_CAMO' },
            { name = "camo_finish2", label = "Finition camouflage 2", hash = 'COMPONENT_PISTOL_MK2_CAMO_02' },
            { name = "camo_finish3", label = "Finition camouflage 3", hash = 'COMPONENT_PISTOL_MK2_CAMO_03' },
            { name = "camo_finish4", label = "Finition camouflage 4", hash = 'COMPONENT_PISTOL_MK2_CAMO_04' },
            { name = "camo_finish5", label = "Finition camouflage 5", hash = 'COMPONENT_PISTOL_MK2_CAMO_05' },
            { name = "camo_finish6", label = "Finition camouflage 6", hash = 'COMPONENT_PISTOL_MK2_CAMO_06' },
            { name = "camo_finish7", label = "Finition camouflage 7", hash = 'COMPONENT_PISTOL_MK2_CAMO_07' },
            { name = "camo_finish8", label = "Finition camouflage 8", hash = 'COMPONENT_PISTOL_MK2_CAMO_08' },
            { name = "camo_finish9", label = "Finition camouflage 9", hash = 'COMPONENT_PISTOL_MK2_CAMO_09' },
            { name = "camo_finish10", label = "Finition camouflage 10", hash = 'COMPONENT_PISTOL_MK2_CAMO_10' },
            { name = "camo_finish11", label = "Finition camouflage 11", hash = 'COMPONENT_PISTOL_MK2_CAMO_IND_01' },
            { name = "camo_slide_finish", label = "Finition glissière camouflage", hash = 'COMPONENT_PISTOL_MK2_CAMO_SLIDE' },
            { name = "camo_slide_finish2", label = "Finition glissière camouflage 2", hash = 'COMPONENT_PISTOL_MK2_CAMO_02_SLIDE' },
            { name = "camo_slide_finish3", label = "Finition glissière camouflage 3", hash = 'COMPONENT_PISTOL_MK2_CAMO_03_SLIDE' },
            { name = "camo_slide_finish4", label = "Finition glissière camouflage 4", hash = 'COMPONENT_PISTOL_MK2_CAMO_04_SLIDE' },
            { name = "camo_slide_finish5", label = "Finition glissière camouflage 5", hash = 'COMPONENT_PISTOL_MK2_CAMO_05_SLIDE' },
            { name = "camo_slide_finish6", label = "Finition glissière camouflage 6", hash = 'COMPONENT_PISTOL_MK2_CAMO_06_SLIDE' },
            { name = "camo_slide_finish7", label = "Finition glissière camouflage 7", hash = 'COMPONENT_PISTOL_MK2_CAMO_07_SLIDE' },
            { name = "camo_slide_finish8", label = "Finition glissière camouflage 8", hash = 'COMPONENT_PISTOL_MK2_CAMO_08_SLIDE' },
            { name = "camo_slide_finish9", label = "Finition glissière camouflage 9", hash = 'COMPONENT_PISTOL_MK2_CAMO_09_SLIDE' },
            { name = "camo_slide_finish10", label = "Finition glissière camouflage 10", hash = 'COMPONENT_PISTOL_MK2_CAMO_10_SLIDE' },
            { name = "camo_slide_finish11", label = "Finition glissière camouflage 11", hash = 'COMPONENT_PISTOL_MK2_CAMO_IND_01_SLIDE' },
        },
    },
    {
        name = "WEAPON_PISTOL50",
        label = "Pistolet calibre 50",
        ammo = { label = "Munitions", hash = 'AMMO_PISTOL' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_PISTOL50_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_PISTOL50_CLIP_02' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_PI_FLSH' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_AR_SUPP_02' },
            { name = "luxary_finish", label = "Finition de luxe", hash = 'COMPONENT_PISTOL50_VARMOD_LUXE' },
        },
    },
    {
        name = "WEAPON_SNSPISTOL",
        label = "Pistolet SNS",
        ammo = { label = "Munitions", hash = 'AMMO_PISTOL' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_SNSPISTOL_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_SNSPISTOL_CLIP_02' },
            { name = "luxary_finish", label = "Finition de luxe", hash = 'COMPONENT_SNSPISTOL_VARMOD_LOWRIDER' },
        },
    },
    {
        name = "WEAPON_SNSPISTOL_MK2",
        label = "Pistolet SNS Mk II",
        ammo = { label = "Munitions", hash = 'AMMO_PISTOL' },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_SNSPISTOL_MK2_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_SNSPISTOL_MK2_CLIP_02' },
            { name = "ammo_tracer", label = "Munitions traçantes", hash = 'COMPONENT_SNSPISTOL_MK2_CLIP_TRACER' },
            { name = "ammo_incendiary", label = "Munitions incendiaires", hash = 'COMPONENT_SNSPISTOL_MK2_CLIP_INCENDIARY' },
            { name = "ammo_hollowpoint", label = "Munitions à pointe creuse", hash = 'COMPONENT_SNSPISTOL_MK2_CLIP_HOLLOWPOINT' },
            { name = "ammo_fmj", label = "Munitions FMJ", hash = 'COMPONENT_SNSPISTOL_MK2_CLIP_FMJ' },
            { name = "scope", label = "Lunette", hash = 'COMPONENT_AT_PI_RAIL_02' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_PI_FLSH_03' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_PI_SUPP_02' },
            { name = "compensator", label = "Compensateur", hash = 'COMPONENT_AT_PI_COMP_02' },
            { name = "camo_finish", label = "Finition camouflage", hash = 'COMPONENT_SNSPISTOL_MK2_CAMO' },
            { name = "camo_finish2", label = "Finition camouflage 2", hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_02' },
            { name = "camo_finish3", label = "Finition camouflage 3", hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_03' },
            { name = "camo_finish4", label = "Finition camouflage 4", hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_04' },
            { name = "camo_finish5", label = "Finition camouflage 5", hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_05' },
            { name = "camo_finish6", label = "Finition camouflage 6", hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_06' },
            { name = "camo_finish7", label = "Finition camouflage 7", hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_07' },
            { name = "camo_finish8", label = "Finition camouflage 8", hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_08' },
            { name = "camo_finish9", label = "Finition camouflage 9", hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_09' },
            { name = "camo_finish10", label = "Finition camouflage 10", hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_10' },
            { name = "camo_finish11", label = "Finition camouflage 11", hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_IND_01' },
            { name = "camo_slide_finish", label = "Finition glissière camouflage", hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_SLIDE' },
            { name = "camo_slide_finish2", label = "Finition glissière camouflage 2", hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_02_SLIDE' },
            { name = "camo_slide_finish3", label = "Finition glissière camouflage 3", hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_03_SLIDE' },
            { name = "camo_slide_finish4", label = "Finition glissière camouflage 4", hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_04_SLIDE' },
            { name = "camo_slide_finish5", label = "Finition glissière camouflage 5", hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_05_SLIDE' },
            { name = "camo_slide_finish6", label = "Finition glissière camouflage 6", hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_06_SLIDE' },
            { name = "camo_slide_finish7", label = "Finition glissière camouflage 7", hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_07_SLIDE' },
            { name = "camo_slide_finish8", label = "Finition glissière camouflage 8", hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_08_SLIDE' },
            { name = "camo_slide_finish9", label = "Finition glissière camouflage 9", hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_09_SLIDE' },
            { name = "camo_slide_finish10", label = "Finition glissière camouflage 10", hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_10_SLIDE' },
            { name = "camo_slide_finish11", label = "Finition glissière camouflage 11", hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_IND_01_SLIDE' },
        },
    },
    { name = "WEAPON_STUNGUN", label = "Taser", tints = Config.DefaultWeaponTints, components = {} },
    { name = "WEAPON_STUNROD", label = "Bâton électrique", tints = Config.DefaultWeaponTints, components = {} },
    { name = "WEAPON_RAYPISTOL", label = "Pistolet rayé", tints = Config.DefaultWeaponTints, components = {} },
    {
        name = "WEAPON_VINTAGEPISTOL",
        label = "Pistolet vintage",
        ammo = { label = "Munitions", hash = 'AMMO_PISTOL' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_VINTAGEPISTOL_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_VINTAGEPISTOL_CLIP_02' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_PI_SUPP' },
        },
    },
    -- Fusils à pompe
    {
        name = "WEAPON_ASSAULTSHOTGUN",
        label = "Fusil à pompe d'assaut",
        ammo = { label = "Cartouches", hash = 'AMMO_SHOTGUN' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_ASSAULTSHOTGUN_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_ASSAULTSHOTGUN_CLIP_02' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_AR_SUPP' },
            { name = "grip", label = "Poignée", hash = 'COMPONENT_AT_AR_AFGRIP' },
        },
    },
    { name = "WEAPON_AUTOSHOTGUN", label = "Fusil à pompe automatique", tints = Config.DefaultWeaponTints, components = {}, ammo = { label = "Cartouches", hash = 'AMMO_SHOTGUN' } },
    {
        name = "WEAPON_BULLPUPSHOTGUN",
        label = "Fusil à pompe bullpup",
        ammo = { label = "Cartouches", hash = 'AMMO_SHOTGUN' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_AR_SUPP_02' },
            { name = "grip", label = "Poignée", hash = 'COMPONENT_AT_AR_AFGRIP' },
        },
    },
    {
        name = "WEAPON_COMBATSHOTGUN",
        label = "Fusil à pompe de combat",
        ammo = { label = "Cartouches", hash = 'AMMO_SHOTGUN' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_AR_SUPP' },
        },
    },
    { name = "WEAPON_DBSHOTGUN", label = "Fusil à double canon", tints = Config.DefaultWeaponTints, components = {}, ammo = { label = "Cartouches", hash = 'AMMO_SHOTGUN' } },
    {
        name = "WEAPON_HEAVYSHOTGUN",
        label = "Fusil à pompe lourd",
        ammo = { label = "Cartouches", hash = 'AMMO_SHOTGUN' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_HEAVYSHOTGUN_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_HEAVYSHOTGUN_CLIP_02' },
            { name = "clip_drum", label = "Chargeur tambour", hash = 'COMPONENT_HEAVYSHOTGUN_CLIP_03' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_AR_SUPP_02' },
            { name = "grip", label = "Poignée", hash = 'COMPONENT_AT_AR_AFGRIP' },
        },
    },
    { name = "WEAPON_MUSKET", label = "Mousquet", tints = Config.DefaultWeaponTints, components = {}, ammo = { label = "Cartouches", hash = 'AMMO_SHOTGUN' } },
    {
        name = "WEAPON_PUMPSHOTGUN",
        label = "Fusil à pompe",
        ammo = { label = "Cartouches", hash = 'AMMO_SHOTGUN' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_SR_SUPP' },
            { name = "luxary_finish", label = "Finition de luxe", hash = 'COMPONENT_PUMPSHOTGUN_VARMOD_LOWRIDER' },
        },
    },
    {
        name = "WEAPON_PUMPSHOTGUN_MK2",
        label = "Fusil à pompe Mk II",
        ammo = { label = "Cartouches", hash = 'AMMO_SHOTGUN' },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "shells_default", label = "Cartouches standard", hash = 'COMPONENT_PUMPSHOTGUN_MK2_CLIP_01' },
            { name = "shells_incendiary", label = "Cartouches incendiaires", hash = 'COMPONENT_PUMPSHOTGUN_MK2_CLIP_INCENDIARY' },
            { name = "shells_armor", label = "Cartouches perforantes", hash = 'COMPONENT_PUMPSHOTGUN_MK2_CLIP_ARMORPIERCING' },
            { name = "shells_hollowpoint", label = "Cartouches à pointe creuse", hash = 'COMPONENT_PUMPSHOTGUN_MK2_CLIP_HOLLOWPOINT' },
            { name = "shells_explosive", label = "Cartouches explosives", hash = 'COMPONENT_PUMPSHOTGUN_MK2_CLIP_EXPLOSIVE' },
            { name = "scope_holo", label = "Viseur holographique", hash = 'COMPONENT_AT_SIGHTS' },
            { name = "scope_small", label = "Petite lunette", hash = 'COMPONENT_AT_SCOPE_MACRO_MK2' },
            { name = "scope_medium", label = "Lunette moyenne", hash = 'COMPONENT_AT_SCOPE_SMALL_MK2' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_SR_SUPP_03' },
            { name = "muzzle_squared", label = "Frein de bouche carré", hash = 'COMPONENT_AT_MUZZLE_08' },
            { name = "camo_finish", label = "Finition camouflage", hash = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO' },
            { name = "camo_finish2", label = "Finition camouflage 2", hash = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_02' },
            { name = "camo_finish3", label = "Finition camouflage 3", hash = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_03' },
            { name = "camo_finish4", label = "Finition camouflage 4", hash = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_04' },
            { name = "camo_finish5", label = "Finition camouflage 5", hash = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_05' },
            { name = "camo_finish6", label = "Finition camouflage 6", hash = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_06' },
            { name = "camo_finish7", label = "Finition camouflage 7", hash = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_07' },
            { name = "camo_finish8", label = "Finition camouflage 8", hash = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_08' },
            { name = "camo_finish9", label = "Finition camouflage 9", hash = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_09' },
            { name = "camo_finish10", label = "Finition camouflage 10", hash = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_10' },
            { name = "camo_finish11", label = "Finition camouflage 11", hash = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_IND_01' },
        },
    },
    {
        name = "WEAPON_SAWNOFFSHOTGUN",
        label = "Fusil à canon scié",
        ammo = { label = "Cartouches", hash = 'AMMO_SHOTGUN' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "luxary_finish", label = "Finition de luxe", hash = 'COMPONENT_SAWNOFFSHOTGUN_VARMOD_LUXE' },
        },
    },
    -- SMG & LMG
    {
        name = "WEAPON_ASSAULTSMG",
        label = "SMG d'assaut",
        ammo = { label = "Munitions", hash = 'AMMO_SMG' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_ASSAULTSMG_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_ASSAULTSMG_CLIP_02' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "scope", label = "Lunette", hash = 'COMPONENT_AT_SCOPE_MACRO' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_AR_SUPP_02' },
            { name = "luxary_finish", label = "Finition de luxe", hash = 'COMPONENT_ASSAULTSMG_VARMOD_LOWRIDER' },
        },
    },
    {
        name = "WEAPON_COMBATMG",
        label = "Mitrailleuse de combat",
        ammo = { label = "Munitions", hash = 'AMMO_MG' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_COMBATMG_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_COMBATMG_CLIP_02' },
            { name = "scope", label = "Lunette", hash = 'COMPONENT_AT_SCOPE_MEDIUM' },
            { name = "grip", label = "Poignée", hash = 'COMPONENT_AT_AR_AFGRIP' },
            { name = "luxary_finish", label = "Finition de luxe", hash = 'COMPONENT_COMBATMG_VARMOD_LOWRIDER' },
        },
    },
    {
        name = "WEAPON_COMBATMG_MK2",
        label = "Mitrailleuse de combat Mk II",
        ammo = { label = "Munitions", hash = 'AMMO_MG' },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_COMBATMG_MK2_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_COMBATMG_MK2_CLIP_02' },
            { name = "ammo_tracer", label = "Munitions traçantes", hash = 'COMPONENT_COMBATMG_MK2_CLIP_TRACER' },
            { name = "ammo_incendiary", label = "Munitions incendiaires", hash = 'COMPONENT_COMBATMG_MK2_CLIP_INCENDIARY' },
            { name = "ammo_hollowpoint", label = "Munitions à pointe creuse", hash = 'COMPONENT_COMBATMG_MK2_CLIP_ARMORPIERCING' },
            { name = "ammo_fmj", label = "Munitions FMJ", hash = 'COMPONENT_COMBATMG_MK2_CLIP_FMJ' },
            { name = "grip", label = "Poignée", hash = 'COMPONENT_AT_AR_AFGRIP_02' },
            { name = "scope_holo", label = "Viseur holographique", hash = 'COMPONENT_AT_SIGHTS' },
            { name = "scope_medium", label = "Lunette moyenne", hash = 'COMPONENT_AT_SCOPE_SMALL_MK2' },
            { name = "scope_large", label = "Lunette longue", hash = 'COMPONENT_AT_SCOPE_MEDIUM_MK2' },
            { name = "muzzle_flat", label = "Frein de bouche plat", hash = 'COMPONENT_AT_MUZZLE_01' },
            { name = "muzzle_tactical", label = "Frein de bouche tactique", hash = 'COMPONENT_AT_MUZZLE_02' },
            { name = "muzzle_fat", label = "Frein de bouche large", hash = 'COMPONENT_AT_MUZZLE_03' },
            { name = "muzzle_precision", label = "Frein de bouche de précision", hash = 'COMPONENT_AT_MUZZLE_04' },
            { name = "muzzle_heavy", label = "Frein de bouche lourd", hash = 'COMPONENT_AT_MUZZLE_05' },
            { name = "muzzle_slanted", label = "Frein de bouche incliné", hash = 'COMPONENT_AT_MUZZLE_06' },
            { name = "muzzle_split", label = "Frein de bouche divisé", hash = 'COMPONENT_AT_MUZZLE_07' },
            { name = "barrel_default", label = "Canon standard", hash = 'COMPONENT_AT_MG_BARREL_01' },
            { name = "barrel_heavy", label = "Canon lourd", hash = 'COMPONENT_AT_MG_BARREL_02' },
            { name = "camo_finish", label = "Finition camouflage", hash = 'COMPONENT_COMBATMG_MK2_CAMO' },
            { name = "camo_finish2", label = "Finition camouflage 2", hash = 'COMPONENT_COMBATMG_MK2_CAMO_02' },
            { name = "camo_finish3", label = "Finition camouflage 3", hash = 'COMPONENT_COMBATMG_MK2_CAMO_03' },
            { name = "camo_finish4", label = "Finition camouflage 4", hash = 'COMPONENT_COMBATMG_MK2_CAMO_04' },
            { name = "camo_finish5", label = "Finition camouflage 5", hash = 'COMPONENT_COMBATMG_MK2_CAMO_05' },
            { name = "camo_finish6", label = "Finition camouflage 6", hash = 'COMPONENT_COMBATMG_MK2_CAMO_06' },
            { name = "camo_finish7", label = "Finition camouflage 7", hash = 'COMPONENT_COMBATMG_MK2_CAMO_07' },
            { name = "camo_finish8", label = "Finition camouflage 8", hash = 'COMPONENT_COMBATMG_MK2_CAMO_08' },
            { name = "camo_finish9", label = "Finition camouflage 9", hash = 'COMPONENT_COMBATMG_MK2_CAMO_09' },
            { name = "camo_finish10", label = "Finition camouflage 10", hash = 'COMPONENT_COMBATMG_MK2_CAMO_10' },
            { name = "camo_finish11", label = "Finition camouflage 11", hash = 'COMPONENT_COMBATMG_MK2_CAMO_IND_01' },
        },
    },
    {
        name = "WEAPON_COMBATPDW",
        label = "PDW de combat",
        ammo = { label = "Munitions", hash = 'AMMO_SMG' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_COMBATPDW_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_COMBATPDW_CLIP_02' },
            { name = "clip_drum", label = "Chargeur tambour", hash = 'COMPONENT_COMBATPDW_CLIP_03' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "grip", label = "Poignée", hash = 'COMPONENT_AT_AR_AFGRIP' },
            { name = "scope", label = "Lunette", hash = 'COMPONENT_AT_SCOPE_SMALL' },
        },
    },
    {
        name = "WEAPON_GUSENBERG",
        label = "Gusenberg",
        ammo = { label = "Munitions", hash = 'AMMO_MG' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_GUSENBERG_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_GUSENBERG_CLIP_02' },
        },
    },
    {
        name = "WEAPON_MACHINEPISTOL",
        label = "Pistolet mitrailleur",
        ammo = { label = "Munitions", hash = 'AMMO_PISTOL' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_MACHINEPISTOL_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_MACHINEPISTOL_CLIP_02' },
            { name = "clip_drum", label = "Chargeur tambour", hash = 'COMPONENT_MACHINEPISTOL_CLIP_03' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_PI_SUPP' },
        },
    },
    {
        name = "WEAPON_MG",
        label = "Mitrailleuse",
        ammo = { label = "Munitions", hash = 'AMMO_MG' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_MG_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_MG_CLIP_02' },
            { name = "scope", label = "Lunette", hash = 'COMPONENT_AT_SCOPE_SMALL_02' },
            { name = "luxary_finish", label = "Finition de luxe", hash = 'COMPONENT_MG_VARMOD_LOWRIDER' },
        },
    },
    {
        name = "WEAPON_MICROSMG",
        label = "Micro SMG",
        ammo = { label = "Munitions", hash = 'AMMO_SMG' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_MICROSMG_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_MICROSMG_CLIP_02' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_PI_FLSH' },
            { name = "scope", label = "Lunette", hash = 'COMPONENT_AT_SCOPE_MACRO' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_AR_SUPP_02' },
            { name = "luxary_finish", label = "Finition de luxe", hash = 'COMPONENT_MICROSMG_VARMOD_LUXE' },
        },
    },
    {
        name = "WEAPON_MINISMG",
        label = "Mini SMG",
        ammo = { label = "Munitions", hash = 'AMMO_SMG' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_MINISMG_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_MINISMG_CLIP_02' },
        },
    },
    {
        name = "WEAPON_SMG",
        label = "SMG",
        ammo = { label = "Munitions", hash = 'AMMO_SMG' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_SMG_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_SMG_CLIP_02' },
            { name = "clip_drum", label = "Chargeur tambour", hash = 'COMPONENT_SMG_CLIP_03' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "scope", label = "Lunette", hash = 'COMPONENT_AT_SCOPE_MACRO_02' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_PI_SUPP' },
            { name = "luxary_finish", label = "Finition de luxe", hash = 'COMPONENT_SMG_VARMOD_LUXE' },
        },
    },
    {
        name = "WEAPON_SMG_MK2",
        label = "SMG Mk II",
        ammo = { label = "Munitions", hash = 'AMMO_SMG' },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_SMG_MK2_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_SMG_MK2_CLIP_02' },
            { name = "ammo_tracer", label = "Munitions traçantes", hash = 'COMPONENT_SMG_MK2_CLIP_TRACER' },
            { name = "ammo_incendiary", label = "Munitions incendiaires", hash = 'COMPONENT_SMG_MK2_CLIP_INCENDIARY' },
            { name = "ammo_hollowpoint", label = "Munitions à pointe creuse", hash = 'COMPONENT_SMG_MK2_CLIP_HOLLOWPOINT' },
            { name = "ammo_fmj", label = "Munitions FMJ", hash = 'COMPONENT_SMG_MK2_CLIP_FMJ' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "scope_holo", label = "Viseur holographique", hash = 'COMPONENT_AT_SIGHTS_SMG' },
            { name = "scope_small", label = "Petite lunette", hash = 'COMPONENT_AT_SCOPE_MACRO_02_SMG_MK2' },
            { name = "scope_medium", label = "Lunette moyenne", hash = 'COMPONENT_AT_SCOPE_SMALL_SMG_MK2' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_PI_SUPP' },
            { name = "muzzle_flat", label = "Frein de bouche plat", hash = 'COMPONENT_AT_MUZZLE_01' },
            { name = "muzzle_tactical", label = "Frein de bouche tactique", hash = 'COMPONENT_AT_MUZZLE_02' },
            { name = "muzzle_fat", label = "Frein de bouche large", hash = 'COMPONENT_AT_MUZZLE_03' },
            { name = "muzzle_precision", label = "Frein de bouche de précision", hash = 'COMPONENT_AT_MUZZLE_04' },
            { name = "muzzle_heavy", label = "Frein de bouche lourd", hash = 'COMPONENT_AT_MUZZLE_05' },
            { name = "muzzle_slanted", label = "Frein de bouche incliné", hash = 'COMPONENT_AT_MUZZLE_06' },
            { name = "muzzle_split", label = "Frein de bouche divisé", hash = 'COMPONENT_AT_MUZZLE_07' },
            { name = "barrel_default", label = "Canon standard", hash = 'COMPONENT_AT_SB_BARREL_01' },
            { name = "barrel_heavy", label = "Canon lourd", hash = 'COMPONENT_AT_SB_BARREL_02' },
            { name = "camo_finish", label = "Finition camouflage", hash = 'COMPONENT_SMG_MK2_CAMO' },
            { name = "camo_finish2", label = "Finition camouflage 2", hash = 'COMPONENT_SMG_MK2_CAMO_02' },
            { name = "camo_finish3", label = "Finition camouflage 3", hash = 'COMPONENT_SMG_MK2_CAMO_03' },
            { name = "camo_finish4", label = "Finition camouflage 4", hash = 'COMPONENT_SMG_MK2_CAMO_04' },
            { name = "camo_finish5", label = "Finition camouflage 5", hash = 'COMPONENT_SMG_MK2_CAMO_05' },
            { name = "camo_finish6", label = "Finition camouflage 6", hash = 'COMPONENT_SMG_MK2_CAMO_06' },
            { name = "camo_finish7", label = "Finition camouflage 7", hash = 'COMPONENT_SMG_MK2_CAMO_07' },
            { name = "camo_finish8", label = "Finition camouflage 8", hash = 'COMPONENT_SMG_MK2_CAMO_08' },
            { name = "camo_finish9", label = "Finition camouflage 9", hash = 'COMPONENT_SMG_MK2_CAMO_09' },
            { name = "camo_finish10", label = "Finition camouflage 10", hash = 'COMPONENT_SMG_MK2_CAMO_10' },
            { name = "camo_finish11", label = "Finition camouflage 11", hash = 'COMPONENT_SMG_MK2_CAMO_IND_01' },
        },
    },
    { name = "WEAPON_RAYCARBINE", label = "Carabine rayé", ammo = { label = "Munitions", hash = 'AMMO_SMG' }, tints = Config.DefaultWeaponTints, components = {} },
    -- Fusils
    {
        name = "WEAPON_ADVANCEDRIFLE",
        label = "Fusil avancé",
        ammo = { label = "Munitions", hash = 'AMMO_RIFLE' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_ADVANCEDRIFLE_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_ADVANCEDRIFLE_CLIP_02' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "scope", label = "Lunette", hash = 'COMPONENT_AT_SCOPE_SMALL' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_AR_SUPP' },
            { name = "luxary_finish", label = "Finition de luxe", hash = 'COMPONENT_ADVANCEDRIFLE_VARMOD_LUXE' },
        },
    },
    {
        name = "WEAPON_ASSAULTRIFLE",
        label = "Fusil d'assaut",
        ammo = { label = "Munitions", hash = 'AMMO_RIFLE' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_ASSAULTRIFLE_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_ASSAULTRIFLE_CLIP_02' },
            { name = "clip_drum", label = "Chargeur tambour", hash = 'COMPONENT_ASSAULTRIFLE_CLIP_03' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "scope", label = "Lunette", hash = 'COMPONENT_AT_SCOPE_MACRO' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_AR_SUPP_02' },
            { name = "grip", label = "Poignée", hash = 'COMPONENT_AT_AR_AFGRIP' },
            { name = "luxary_finish", label = "Finition de luxe", hash = 'COMPONENT_ASSAULTRIFLE_VARMOD_LUXE' },
        },
    },
    {
        name = "WEAPON_ASSAULTRIFLE_MK2",
        label = "Fusil d'assaut Mk II",
        ammo = { label = "Munitions", hash = 'AMMO_RIFLE' },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_ASSAULTRIFLE_MK2_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_ASSAULTRIFLE_MK2_CLIP_02' },
            { name = "ammo_tracer", label = "Munitions traçantes", hash = 'COMPONENT_ASSAULTRIFLE_MK2_CLIP_TRACER' },
            { name = "ammo_incendiary", label = "Munitions incendiaires", hash = 'COMPONENT_ASSAULTRIFLE_MK2_CLIP_INCENDIARY' },
            { name = "ammo_armor", label = "Munitions perforantes", hash = 'COMPONENT_ASSAULTRIFLE_MK2_CLIP_ARMORPIERCING' },
            { name = "ammo_fmj", label = "Munitions FMJ", hash = 'COMPONENT_ASSAULTRIFLE_MK2_CLIP_FMJ' },
            { name = "grip", label = "Poignée", hash = 'COMPONENT_AT_AR_AFGRIP_02' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "scope_holo", label = "Viseur holographique", hash = 'COMPONENT_AT_SIGHTS' },
            { name = "scope_small", label = "Petite lunette", hash = 'COMPONENT_AT_SCOPE_MACRO_MK2' },
            { name = "scope_large", label = "Lunette longue", hash = 'COMPONENT_AT_SCOPE_MEDIUM_MK2' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_AR_SUPP_02' },
            { name = "muzzle_flat", label = "Frein de bouche plat", hash = 'COMPONENT_AT_MUZZLE_01' },
            { name = "muzzle_tactical", label = "Frein de bouche tactique", hash = 'COMPONENT_AT_MUZZLE_02' },
            { name = "muzzle_fat", label = "Frein de bouche large", hash = 'COMPONENT_AT_MUZZLE_03' },
            { name = "muzzle_precision", label = "Frein de bouche de précision", hash = 'COMPONENT_AT_MUZZLE_04' },
            { name = "muzzle_heavy", label = "Frein de bouche lourd", hash = 'COMPONENT_AT_MUZZLE_05' },
            { name = "muzzle_slanted", label = "Frein de bouche incliné", hash = 'COMPONENT_AT_MUZZLE_06' },
            { name = "muzzle_split", label = "Frein de bouche divisé", hash = 'COMPONENT_AT_MUZZLE_07' },
            { name = "barrel_default", label = "Canon standard", hash = 'COMPONENT_AT_AR_BARREL_01' },
            { name = "barrel_heavy", label = "Canon lourd", hash = 'COMPONENT_AT_AR_BARREL_02' },
            { name = "camo_finish", label = "Finition camouflage", hash = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO' },
            { name = "camo_finish2", label = "Finition camouflage 2", hash = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_02' },
            { name = "camo_finish3", label = "Finition camouflage 3", hash = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_03' },
            { name = "camo_finish4", label = "Finition camouflage 4", hash = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_04' },
            { name = "camo_finish5", label = "Finition camouflage 5", hash = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_05' },
            { name = "camo_finish6", label = "Finition camouflage 6", hash = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_06' },
            { name = "camo_finish7", label = "Finition camouflage 7", hash = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_07' },
            { name = "camo_finish8", label = "Finition camouflage 8", hash = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_08' },
            { name = "camo_finish9", label = "Finition camouflage 9", hash = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_09' },
            { name = "camo_finish10", label = "Finition camouflage 10", hash = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_10' },
            { name = "camo_finish11", label = "Finition camouflage 11", hash = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_IND_01' },
        },
    },
    {
        name = "WEAPON_BULLPUPRIFLE",
        label = "Fusil bullpup",
        ammo = { label = "Munitions", hash = 'AMMO_RIFLE' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_BULLPUPRIFLE_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_BULLPUPRIFLE_CLIP_02' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "scope", label = "Lunette", hash = 'COMPONENT_AT_SCOPE_SMALL' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_AR_SUPP' },
            { name = "grip", label = "Poignée", hash = 'COMPONENT_AT_AR_AFGRIP' },
            { name = "luxary_finish", label = "Finition basse", hash = 'COMPONENT_BULLPUPRIFLE_VARMOD_LOW' },
        },
    },
    {
        name = "WEAPON_BULLPUPRIFLE_MK2",
        label = "Fusil bullpup Mk II",
        ammo = { label = "Munitions", hash = 'AMMO_RIFLE' },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_BULLPUPRIFLE_MK2_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_BULLPUPRIFLE_MK2_CLIP_02' },
            { name = "ammo_tracer", label = "Munitions traçantes", hash = 'COMPONENT_BULLPUPRIFLE_MK2_CLIP_TRACER' },
            { name = "ammo_incendiary", label = "Munitions incendiaires", hash = 'COMPONENT_BULLPUPRIFLE_MK2_CLIP_INCENDIARY' },
            { name = "ammo_armor", label = "Munitions perforantes", hash = 'COMPONENT_BULLPUPRIFLE_MK2_CLIP_ARMORPIERCING' },
            { name = "ammo_fmj", label = "Munitions FMJ", hash = 'COMPONENT_BULLPUPRIFLE_MK2_CLIP_FMJ' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "scope_holo", label = "Viseur holographique", hash = 'COMPONENT_AT_SIGHTS' },
            { name = "scope_small", label = "Petite lunette", hash = 'COMPONENT_AT_SCOPE_MACRO_02_MK2' },
            { name = "scope_medium", label = "Lunette moyenne", hash = 'COMPONENT_AT_SCOPE_SMALL_MK2' },
            { name = "barrel_default", label = "Canon standard", hash = 'COMPONENT_AT_BP_BARREL_01' },
            { name = "barrel_heavy", label = "Canon lourd", hash = 'COMPONENT_AT_BP_BARREL_02' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_AR_SUPP' },
            { name = "muzzle_flat", label = "Frein de bouche plat", hash = 'COMPONENT_AT_MUZZLE_01' },
            { name = "muzzle_tactical", label = "Frein de bouche tactique", hash = 'COMPONENT_AT_MUZZLE_02' },
            { name = "muzzle_fat", label = "Frein de bouche large", hash = 'COMPONENT_AT_MUZZLE_03' },
            { name = "muzzle_precision", label = "Frein de bouche de précision", hash = 'COMPONENT_AT_MUZZLE_04' },
            { name = "muzzle_heavy", label = "Frein de bouche lourd", hash = 'COMPONENT_AT_MUZZLE_05' },
            { name = "muzzle_slanted", label = "Frein de bouche incliné", hash = 'COMPONENT_AT_MUZZLE_06' },
            { name = "muzzle_split", label = "Frein de bouche divisé", hash = 'COMPONENT_AT_MUZZLE_07' },
            { name = "grip", label = "Poignée", hash = 'COMPONENT_AT_AR_AFGRIP_02' },
            { name = "camo_finish", label = "Finition camouflage", hash = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO' },
            { name = "camo_finish2", label = "Finition camouflage 2", hash = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_02' },
            { name = "camo_finish3", label = "Finition camouflage 3", hash = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_03' },
            { name = "camo_finish4", label = "Finition camouflage 4", hash = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_04' },
            { name = "camo_finish5", label = "Finition camouflage 5", hash = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_05' },
            { name = "camo_finish6", label = "Finition camouflage 6", hash = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_06' },
            { name = "camo_finish7", label = "Finition camouflage 7", hash = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_07' },
            { name = "camo_finish8", label = "Finition camouflage 8", hash = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_08' },
            { name = "camo_finish9", label = "Finition camouflage 9", hash = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_09' },
            { name = "camo_finish10", label = "Finition camouflage 10", hash = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_10' },
            { name = "camo_finish11", label = "Finition camouflage 11", hash = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_IND_01' },
        },
    },
    {
        name = "WEAPON_CARBINERIFLE",
        label = "Carabine",
        ammo = { label = "Munitions", hash = 'AMMO_RIFLE' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_CARBINERIFLE_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_CARBINERIFLE_CLIP_02' },
            { name = "clip_box", label = "Chargeur boîte", hash = 'COMPONENT_CARBINERIFLE_CLIP_03' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "scope", label = "Lunette", hash = 'COMPONENT_AT_SCOPE_MEDIUM' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_AR_SUPP' },
            { name = "grip", label = "Poignée", hash = 'COMPONENT_AT_AR_AFGRIP' },
            { name = "luxary_finish", label = "Finition de luxe", hash = 'COMPONENT_CARBINERIFLE_VARMOD_LUXE' },
        },
    },
    {
        name = "WEAPON_CARBINERIFLE_MK2",
        label = "Carabine Mk II",
        ammo = { label = "Munitions", hash = 'AMMO_RIFLE' },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_CARBINERIFLE_MK2_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_CARBINERIFLE_MK2_CLIP_02' },
            { name = "ammo_tracer", label = "Munitions traçantes", hash = 'COMPONENT_CARBINERIFLE_MK2_CLIP_TRACER' },
            { name = "ammo_incendiary", label = "Munitions incendiaires", hash = 'COMPONENT_CARBINERIFLE_MK2_CLIP_INCENDIARY' },
            { name = "ammo_armor", label = "Munitions perforantes", hash = 'COMPONENT_CARBINERIFLE_MK2_CLIP_ARMORPIERCING' },
            { name = "ammo_fmj", label = "Munitions FMJ", hash = 'COMPONENT_CARBINERIFLE_MK2_CLIP_FMJ' },
            { name = "grip", label = "Poignée", hash = 'COMPONENT_AT_AR_AFGRIP_02' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "scope_holo", label = "Viseur holographique", hash = 'COMPONENT_AT_SIGHTS' },
            { name = "scope_medium", label = "Lunette moyenne", hash = 'COMPONENT_AT_SCOPE_MACRO_MK2' },
            { name = "scope_large", label = "Lunette longue", hash = 'COMPONENT_AT_SCOPE_MEDIUM_MK2' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_AR_SUPP' },
            { name = "muzzle_flat", label = "Frein de bouche plat", hash = 'COMPONENT_AT_MUZZLE_01' },
            { name = "muzzle_tactical", label = "Frein de bouche tactique", hash = 'COMPONENT_AT_MUZZLE_02' },
            { name = "muzzle_fat", label = "Frein de bouche large", hash = 'COMPONENT_AT_MUZZLE_03' },
            { name = "muzzle_precision", label = "Frein de bouche de précision", hash = 'COMPONENT_AT_MUZZLE_04' },
            { name = "muzzle_heavy", label = "Frein de bouche lourd", hash = 'COMPONENT_AT_MUZZLE_05' },
            { name = "muzzle_slanted", label = "Frein de bouche incliné", hash = 'COMPONENT_AT_MUZZLE_06' },
            { name = "muzzle_split", label = "Frein de bouche divisé", hash = 'COMPONENT_AT_MUZZLE_07' },
            { name = "barrel_default", label = "Canon standard", hash = 'COMPONENT_AT_CR_BARREL_01' },
            { name = "barrel_heavy", label = "Canon lourd", hash = 'COMPONENT_AT_CR_BARREL_02' },
            { name = "camo_finish", label = "Finition camouflage", hash = 'COMPONENT_CARBINERIFLE_MK2_CAMO' },
            { name = "camo_finish2", label = "Finition camouflage 2", hash = 'COMPONENT_CARBINERIFLE_MK2_CAMO_02' },
            { name = "camo_finish3", label = "Finition camouflage 3", hash = 'COMPONENT_CARBINERIFLE_MK2_CAMO_03' },
            { name = "camo_finish4", label = "Finition camouflage 4", hash = 'COMPONENT_CARBINERIFLE_MK2_CAMO_04' },
            { name = "camo_finish5", label = "Finition camouflage 5", hash = 'COMPONENT_CARBINERIFLE_MK2_CAMO_05' },
            { name = "camo_finish6", label = "Finition camouflage 6", hash = 'COMPONENT_CARBINERIFLE_MK2_CAMO_06' },
            { name = "camo_finish7", label = "Finition camouflage 7", hash = 'COMPONENT_CARBINERIFLE_MK2_CAMO_07' },
            { name = "camo_finish8", label = "Finition camouflage 8", hash = 'COMPONENT_CARBINERIFLE_MK2_CAMO_08' },
            { name = "camo_finish9", label = "Finition camouflage 9", hash = 'COMPONENT_CARBINERIFLE_MK2_CAMO_09' },
            { name = "camo_finish10", label = "Finition camouflage 10", hash = 'COMPONENT_CARBINERIFLE_MK2_CAMO_10' },
            { name = "camo_finish11", label = "Finition camouflage 11", hash = 'COMPONENT_CARBINERIFLE_MK2_CAMO_IND_01' },
        },
    },
    {
        name = "WEAPON_COMPACTRIFLE",
        label = "Fusil compact",
        ammo = { label = "Munitions", hash = 'AMMO_RIFLE' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_COMPACTRIFLE_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_COMPACTRIFLE_CLIP_02' },
            { name = "clip_drum", label = "Chargeur tambour", hash = 'COMPONENT_COMPACTRIFLE_CLIP_03' },
        },
    },
    {
        name = "WEAPON_MILITARYRIFLE",
        label = "Fusil militaire",
        ammo = { label = "Munitions", hash = 'AMMO_RIFLE' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_MILITARYRIFLE_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_MILITARYRIFLE_CLIP_02' },
            { name = "ironsights", label = "Viseur", hash = 'COMPONENT_MILITARYRIFLE_SIGHT_01' },
            { name = "scope", label = "Lunette", hash = 'COMPONENT_AT_SCOPE_SMALL' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_AR_SUPP' },
        },
    },
    {
        name = "WEAPON_SPECIALCARBINE",
        label = "Carabine spéciale",
        ammo = { label = "Munitions", hash = 'AMMO_RIFLE' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_SPECIALCARBINE_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_SPECIALCARBINE_CLIP_02' },
            { name = "clip_drum", label = "Chargeur tambour", hash = 'COMPONENT_SPECIALCARBINE_CLIP_03' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "scope", label = "Lunette", hash = 'COMPONENT_AT_SCOPE_MEDIUM' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_AR_SUPP_02' },
            { name = "grip", label = "Poignée", hash = 'COMPONENT_AT_AR_AFGRIP' },
            { name = "luxary_finish", label = "Finition de luxe", hash = 'COMPONENT_SPECIALCARBINE_VARMOD_LOWRIDER' },
        },
    },
    {
        name = "WEAPON_SPECIALCARBINE_MK2",
        label = "Carabine spéciale Mk II",
        ammo = { label = "Munitions", hash = 'AMMO_RIFLE' },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_SPECIALCARBINE_MK2_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_SPECIALCARBINE_MK2_CLIP_02' },
            { name = "ammo_tracer", label = "Munitions traçantes", hash = 'COMPONENT_SPECIALCARBINE_MK2_CLIP_TRACER' },
            { name = "ammo_incendiary", label = "Munitions incendiaires", hash = 'COMPONENT_SPECIALCARBINE_MK2_CLIP_INCENDIARY' },
            { name = "ammo_armor", label = "Munitions perforantes", hash = 'COMPONENT_SPECIALCARBINE_MK2_CLIP_ARMORPIERCING' },
            { name = "ammo_fmj", label = "Munitions FMJ", hash = 'COMPONENT_SPECIALCARBINE_MK2_CLIP_FMJ' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "scope_holo", label = "Viseur holographique", hash = 'COMPONENT_AT_SIGHTS' },
            { name = "scope_small", label = "Petite lunette", hash = 'COMPONENT_AT_SCOPE_MACRO_MK2' },
            { name = "scope_large", label = "Lunette longue", hash = 'COMPONENT_AT_SCOPE_MEDIUM_MK2' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_AR_SUPP_02' },
            { name = "muzzle_flat", label = "Frein de bouche plat", hash = 'COMPONENT_AT_MUZZLE_01' },
            { name = "muzzle_tactical", label = "Frein de bouche tactique", hash = 'COMPONENT_AT_MUZZLE_02' },
            { name = "muzzle_fat", label = "Frein de bouche large", hash = 'COMPONENT_AT_MUZZLE_03' },
            { name = "muzzle_precision", label = "Frein de bouche de précision", hash = 'COMPONENT_AT_MUZZLE_04' },
            { name = "muzzle_heavy", label = "Frein de bouche lourd", hash = 'COMPONENT_AT_MUZZLE_05' },
            { name = "muzzle_slanted", label = "Frein de bouche incliné", hash = 'COMPONENT_AT_MUZZLE_06' },
            { name = "muzzle_split", label = "Frein de bouche divisé", hash = 'COMPONENT_AT_MUZZLE_07' },
            { name = "grip", label = "Poignée", hash = 'COMPONENT_AT_AR_AFGRIP_02' },
            { name = "barrel_default", label = "Canon standard", hash = 'COMPONENT_AT_SC_BARREL_01' },
            { name = "barrel_heavy", label = "Canon lourd", hash = 'COMPONENT_AT_SC_BARREL_02' },
            { name = "camo_finish", label = "Finition camouflage", hash = 'COMPONENT_SPECIALCARBINE_MK2_CAMO' },
            { name = "camo_finish2", label = "Finition camouflage 2", hash = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_02' },
            { name = "camo_finish3", label = "Finition camouflage 3", hash = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_03' },
            { name = "camo_finish4", label = "Finition camouflage 4", hash = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_04' },
            { name = "camo_finish5", label = "Finition camouflage 5", hash = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_05' },
            { name = "camo_finish6", label = "Finition camouflage 6", hash = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_06' },
            { name = "camo_finish7", label = "Finition camouflage 7", hash = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_07' },
            { name = "camo_finish8", label = "Finition camouflage 8", hash = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_08' },
            { name = "camo_finish9", label = "Finition camouflage 9", hash = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_09' },
            { name = "camo_finish10", label = "Finition camouflage 10", hash = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_10' },
            { name = "camo_finish11", label = "Finition camouflage 11", hash = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_IND_01' },
        },
    },
    {
        name = "WEAPON_HEAVYRIFLE",
        label = "Fusil lourd",
        ammo = { label = "Munitions", hash = 'AMMO_RIFLE' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_HEAVYRIFLE_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_HEAVYRIFLE_CLIP_02' },
            { name = "scope_holo", label = "Viseur holographique", hash = 'COMPONENT_HEAVYRIFLE_SIGHT_01' },
            { name = "scope", label = "Lunette", hash = 'COMPONENT_AT_SCOPE_MEDIUM' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_AR_SUPP' },
            { name = "grip", label = "Poignée", hash = 'COMPONENT_AT_AR_AFGRIP' },
        },
    },
    -- Sniper
    {
        name = "WEAPON_HEAVYSNIPER",
        label = "Fusil de sniper lourd",
        ammo = { label = "Munitions", hash = 'AMMO_SNIPER' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "scope", label = "Lunette", hash = 'COMPONENT_AT_SCOPE_LARGE' },
            { name = "scope_advanced", label = "Lunette avancée", hash = 'COMPONENT_AT_SCOPE_MAX' },
        },
    },
    {
        name = "WEAPON_HEAVYSNIPER_MK2",
        label = "Fusil de sniper lourd Mk II",
        ammo = { label = "Munitions", hash = 'AMMO_SNIPER' },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_HEAVYSNIPER_MK2_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_HEAVYSNIPER_MK2_CLIP_02' },
            { name = "ammo_incendiary", label = "Munitions incendiaires", hash = 'COMPONENT_HEAVYSNIPER_MK2_CLIP_INCENDIARY' },
            { name = "ammo_armor", label = "Munitions perforantes", hash = 'COMPONENT_HEAVYSNIPER_MK2_CLIP_ARMORPIERCING' },
            { name = "ammo_fmj", label = "Munitions FMJ", hash = 'COMPONENT_HEAVYSNIPER_MK2_CLIP_FMJ' },
            { name = "ammo_explosive", label = "Munitions explosives", hash = 'COMPONENT_HEAVYSNIPER_MK2_CLIP_EXPLOSIVE' },
            { name = "scope_zoom", label = "Lunette zoom", hash = 'COMPONENT_AT_SCOPE_LARGE_MK2' },
            { name = "scope_advanced", label = "Lunette avancée", hash = 'COMPONENT_AT_SCOPE_MAX' },
            { name = "scope_nightvision", label = "Lunette vision nocturne", hash = 'COMPONENT_AT_SCOPE_NV' },
            { name = "scope_thermal", label = "Lunette thermique", hash = 'COMPONENT_AT_SCOPE_THERMAL' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_SR_SUPP_03' },
            { name = "muzzle_squared", label = "Frein de bouche carré", hash = 'COMPONENT_AT_MUZZLE_08' },
            { name = "muzzle_bell", label = "Frein de bouche en cloche", hash = 'COMPONENT_AT_MUZZLE_09' },
            { name = "barrel_default", label = "Canon standard", hash = 'COMPONENT_AT_SR_BARREL_01' },
            { name = "barrel_heavy", label = "Canon lourd", hash = 'COMPONENT_AT_SR_BARREL_02' },
            { name = "camo_finish", label = "Finition camouflage", hash = 'COMPONENT_HEAVYSNIPER_MK2_CAMO' },
            { name = "camo_finish2", label = "Finition camouflage 2", hash = 'COMPONENT_HEAVYSNIPER_MK2_CAMO_02' },
            { name = "camo_finish3", label = "Finition camouflage 3", hash = 'COMPONENT_HEAVYSNIPER_MK2_CAMO_03' },
            { name = "camo_finish4", label = "Finition camouflage 4", hash = 'COMPONENT_HEAVYSNIPER_MK2_CAMO_04' },
            { name = "camo_finish5", label = "Finition camouflage 5", hash = 'COMPONENT_HEAVYSNIPER_MK2_CAMO_05' },
            { name = "camo_finish6", label = "Finition camouflage 6", hash = 'COMPONENT_HEAVYSNIPER_MK2_CAMO_06' },
            { name = "camo_finish7", label = "Finition camouflage 7", hash = 'COMPONENT_HEAVYSNIPER_MK2_CAMO_07' },
            { name = "camo_finish8", label = "Finition camouflage 8", hash = 'COMPONENT_HEAVYSNIPER_MK2_CAMO_08' },
            { name = "camo_finish9", label = "Finition camouflage 9", hash = 'COMPONENT_HEAVYSNIPER_MK2_CAMO_09' },
            { name = "camo_finish10", label = "Finition camouflage 10", hash = 'COMPONENT_HEAVYSNIPER_MK2_CAMO_10' },
            { name = "camo_finish11", label = "Finition camouflage 11", hash = 'COMPONENT_HEAVYSNIPER_MK2_CAMO_IND_01' },
        },
    },
    {
        name = "WEAPON_MARKSMANRIFLE",
        label = "Fusil marksman",
        ammo = { label = "Munitions", hash = 'AMMO_SNIPER' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_MARKSMANRIFLE_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_MARKSMANRIFLE_CLIP_02' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "scope", label = "Lunette", hash = 'COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_AR_SUPP' },
            { name = "grip", label = "Poignée", hash = 'COMPONENT_AT_AR_AFGRIP' },
            { name = "luxary_finish", label = "Finition de luxe", hash = 'COMPONENT_MARKSMANRIFLE_VARMOD_LUXE' },
        },
    },
    {
        name = "WEAPON_MARKSMANRIFLE_MK2",
        label = "Fusil marksman Mk II",
        ammo = { label = "Munitions", hash = 'AMMO_SNIPER' },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_MARKSMANRIFLE_MK2_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_MARKSMANRIFLE_MK2_CLIP_02' },
            { name = "ammo_tracer", label = "Munitions traçantes", hash = 'COMPONENT_MARKSMANRIFLE_MK2_CLIP_TRACER' },
            { name = "ammo_incendiary", label = "Munitions incendiaires", hash = 'COMPONENT_MARKSMANRIFLE_MK2_CLIP_INCENDIARY' },
            { name = "ammo_armor", label = "Munitions perforantes", hash = 'COMPONENT_MARKSMANRIFLE_MK2_CLIP_ARMORPIERCING' },
            { name = "ammo_fmj", label = "Munitions FMJ", hash = 'COMPONENT_MARKSMANRIFLE_MK2_CLIP_FMJ' },
            { name = "scope_holo", label = "Viseur holographique", hash = 'COMPONENT_AT_SIGHTS' },
            { name = "scope_large", label = "Lunette longue", hash = 'COMPONENT_AT_SCOPE_MEDIUM_MK2' },
            { name = "scope_zoom", label = "Lunette zoom", hash = 'COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM_MK2' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_AR_SUPP' },
            { name = "muzzle_flat", label = "Frein de bouche plat", hash = 'COMPONENT_AT_MUZZLE_01' },
            { name = "muzzle_tactical", label = "Frein de bouche tactique", hash = 'COMPONENT_AT_MUZZLE_02' },
            { name = "muzzle_fat", label = "Frein de bouche large", hash = 'COMPONENT_AT_MUZZLE_03' },
            { name = "muzzle_precision", label = "Frein de bouche de précision", hash = 'COMPONENT_AT_MUZZLE_04' },
            { name = "muzzle_heavy", label = "Frein de bouche lourd", hash = 'COMPONENT_AT_MUZZLE_05' },
            { name = "muzzle_slanted", label = "Frein de bouche incliné", hash = 'COMPONENT_AT_MUZZLE_06' },
            { name = "muzzle_split", label = "Frein de bouche divisé", hash = 'COMPONENT_AT_MUZZLE_07' },
            { name = "barrel_default", label = "Canon standard", hash = 'COMPONENT_AT_MRFL_BARREL_01' },
            { name = "barrel_heavy", label = "Canon lourd", hash = 'COMPONENT_AT_MRFL_BARREL_02' },
            { name = "grip", label = "Poignée", hash = 'COMPONENT_AT_AR_AFGRIP_02' },
            { name = "camo_finish", label = "Finition camouflage", hash = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO' },
            { name = "camo_finish2", label = "Finition camouflage 2", hash = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO_02' },
            { name = "camo_finish3", label = "Finition camouflage 3", hash = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO_03' },
            { name = "camo_finish4", label = "Finition camouflage 4", hash = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO_04' },
            { name = "camo_finish5", label = "Finition camouflage 5", hash = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO_05' },
            { name = "camo_finish6", label = "Finition camouflage 6", hash = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO_06' },
            { name = "camo_finish7", label = "Finition camouflage 7", hash = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO_07' },
            { name = "camo_finish8", label = "Finition camouflage 8", hash = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO_08' },
            { name = "camo_finish9", label = "Finition camouflage 9", hash = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO_09' },
            { name = "camo_finish10", label = "Finition camouflage 10", hash = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO_10' },
            { name = "camo_finish11", label = "Finition camouflage 11", hash = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO_IND_01' },
        },
    },
    {
        name = "WEAPON_SNIPERRIFLE",
        label = "Fusil de sniper",
        ammo = { label = "Munitions", hash = 'AMMO_SNIPER' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "scope", label = "Lunette", hash = 'COMPONENT_AT_SCOPE_LARGE' },
            { name = "scope_advanced", label = "Lunette avancée", hash = 'COMPONENT_AT_SCOPE_MAX' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_AR_SUPP_02' },
            { name = "luxary_finish", label = "Finition de luxe", hash = 'COMPONENT_SNIPERRIFLE_VARMOD_LUXE' },
        },
    },
    -- Lourd / Lanceurs
    {
        name = "WEAPON_COMPACTLAUNCHER",
        label = "Lanceur compact",
        tints = Config.DefaultWeaponTints,
---@class components
        components = {},
        ammo = { label = "Munitions de lance-grenades", hash = 'AMMO_GRENADELAUNCHER' },
    },
    { name = "WEAPON_FIREWORK", label = "Feu d'artifice", components = {}, ammo = { label = "Munitions de feu d'artifice", hash = 'AMMO_FIREWORK' } },
    {
        name = "WEAPON_GRENADELAUNCHER",
        label = "Lance-grenades",
        tints = Config.DefaultWeaponTints,
---@class components
        components = {},
        ammo = { label = "Munitions de lance-grenades", hash = 'AMMO_GRENADELAUNCHER' },
    },
    { name = "WEAPON_HOMINGLAUNCHER", label = "Lanceur à tête chercheuse", tints = Config.DefaultWeaponTints, components = {}, ammo = { label = "Roquettes", hash = 'AMMO_HOMINGLAUNCHER' } },
    { name = "WEAPON_MINIGUN", label = "Minigun", tints = Config.DefaultWeaponTints, components = {}, ammo = { label = "Munitions", hash = 'AMMO_MINIGUN' } },
    { name = "WEAPON_RAILGUN", label = "Railgun", tints = Config.DefaultWeaponTints, components = {}, ammo = { label = "Munitions", hash = 'AMMO_RAILGUN' } },
    { name = "WEAPON_RPG", label = "RPG", tints = Config.DefaultWeaponTints, components = {}, ammo = { label = "Roquettes", hash = 'AMMO_RPG' } },
    { name = "WEAPON_RAYMINIGUN", label = "Minigun rayé", tints = Config.DefaultWeaponTints, components = {}, ammo = { label = "Munitions", hash = 'AMMO_MINIGUN' } },
    -- Jetables
    { name = "WEAPON_BALL", label = "Balle", components = {}, ammo = { label = "Balle", hash = 'AMMO_BALL' }, throwable = true },
    { name = "WEAPON_BZGAS", label = "Gaz BZ", components = {}, ammo = { label = "Gaz BZ", hash = 'AMMO_BZGAS' }, throwable = true },
    { name = "WEAPON_FLARE", label = "Fusée éclairante", components = {}, ammo = { label = "Fusée éclairante", hash = 'AMMO_FLARE' }, throwable = true },
    { name = "WEAPON_GRENADE", label = "Grenade", components = {}, ammo = { label = "Grenade", hash = 'AMMO_GRENADE' }, throwable = true },
    { name = "WEAPON_PETROLCAN", label = "Jerrican d'essence", components = {}, ammo = { label = "Essence", hash = 'AMMO_PETROLCAN' }, tool = true },
    { name = "WEAPON_HAZARDCAN", label = "Jerrican dangereux", components = {}, ammo = { label = "Essence", hash = 'AMMO_PETROLCAN' }, throwable = true },
    { name = "WEAPON_MOLOTOV", label = "Cocktail Molotov", components = {}, ammo = { label = "Molotov", hash = 'AMMO_MOLOTOV' }, throwable = true },
    { name = "WEAPON_PROXMINE", label = "Mine de proximité", components = {}, ammo = { label = "Mine", hash = 'AMMO_PROXMINE' }, throwable = true },
    { name = "WEAPON_PIPEBOMB", label = "Bombe tuyau", components = {}, ammo = { label = "Bombe", hash = 'AMMO_PIPEBOMB' }, throwable = true },
    { name = "WEAPON_SNOWBALL", label = "Boule de neige", components = {}, ammo = { label = "Boule de neige", hash = 'AMMO_SNOWBALL' }, throwable = true },
    { name = "WEAPON_STICKYBOMB", label = "Bombe collante", components = {}, ammo = { label = "Bombe collante", hash = 'AMMO_STICKYBOMB' }, throwable = true },
    { name = "WEAPON_SMOKEGRENADE", label = "Grenade fumigène", components = {}, ammo = { label = "Grenade fumigène", hash = 'AMMO_SMOKEGRENADE' }, throwable = true },
    -- Outils
    { name = "WEAPON_FIREEXTINGUISHER", label = "Extincteur", components = {}, ammo = { label = "Charge", hash = 'AMMO_FIREEXTINGUISHER' }, tool = true },
    { name = "WEAPON_DIGISCANNER", label = "Scanner digital", components = {} },
    { name = "GADGET_PARACHUTE", label = "Parachute", components = {}, throwable = true },
    {
        name = "WEAPON_TACTICALRIFLE",
        label = "Fusil tactique",
        ammo = { label = "Munitions", hash = 'AMMO_RIFLE' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_TACTICALRIFLE_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_TACTICALRIFLE_CLIP_02' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_AR_FLSH_REH' },
            { name = "grip", label = "Poignée", hash = 'COMPONENT_AT_AR_AFGRIP' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_AR_SUPP_02' },
        },
    },
    {
        name = "WEAPON_BATTLERIFLE",
        label = "Fusil de bataille",
        ammo = { label = "Munitions", hash = 'AMMO_RIFLE' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_BATTLERIFLE_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_BATTLERIFLE_CLIP_02' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_AR_SUPP' },
        },
    },
    {
        name = "WEAPON_SNOWLAUNCHER",
        label = "Lanceur de boules de neige",
        ammo = { label = "Boules de neige", hash = 'AMMO_SNOWLAUNCHER' },
        tints = Config.DefaultWeaponTints,
---@class components
        components = {},
    },
    {
        name = "WEAPON_HACKINGDEVICE",
        label = "Dispositif de piratage",
        tints = Config.DefaultWeaponTints,
---@class components
        components = {},
    },
    {
        name = "WEAPON_PRECISIONRIFLE",
        label = "Fusil de précision",
        ammo = { label = "Munitions", hash = 'AMMO_SNIPER' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_PRECISIONRIFLE_CLIP_01' },
        },
    },
    { name = "WEAPON_METALDETECTOR", label = "Détecteur de métaux", components = {} },
    {
        name = "WEAPON_PISTOLXM3",
        label = "Pistolet XM3",
        ammo = { label = "Munitions", hash = 'AMMO_PISTOL' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_PISTOLXM3_CLIP_01' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_PISTOLXM3_SUPP' },
        },
    },
    { name = "WEAPON_ACIDPACKAGE", label = "Pack d'acide", components = {}, throwable = true },
    { name = "WEAPON_CANDYCANE", label = "Canne en bonbon", components = {} },
    {
        name = "WEAPON_RAILGUNXM3",
        label = "Railgun XM3",
        ammo = { label = "Munitions", hash = 'AMMO_RAILGUN' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_RAILGUNXM3_CLIP_01' },
        },
    },
    { name = "WEAPON_PEPPERSPRAY", label = "Spray au poivre", components = {}, ammo = { label = "Spray", hash = 'WEAPON_PEPPERSPRAY' }, throwable = true },
    { name = "WEAPON_ASPBATON", label = "Matraque ASP", melee = true, noTint = true, components = {} },
    { name = "WEAPON_LESSLAUNCHER", label = "Lanceur 40mm non-letal", noTint = true, components = {} },
    { name = "WEAPON_BEANBAG", label = "Beanbag", noTint = true, ammo = { label = "Beanbag", hash = 'AMMO_BEANBAG' }, components = {} },
    { name = "WEAPON_BEANBAG2", label = "Beanbag orange", noTint = true, ammo = { label = "Beanbag", hash = 'AMMO_BEANBAG' }, components = {} },
    {
        name = "WEAPON_PDGLOCK17",
        label = "Glock 17 PD",
        noTint = true,
        ammo = { label = "Munitions", hash = 'AMMO_PISTOL' },
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_PDGLOCK17_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_PDGLOCK17_CLIP_02' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_PI_FLSH' },
        },
    },
    {
        name = "WEAPON_GLOCK20",
        label = "Glock 20",
        noTint = true,
        ammo = { label = "Munitions", hash = 'AMMO_PISTOL' },
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_GLOCK20_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_GLOCK20_CLIP_02' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_PI_FLSH' },
        },
    },
    {
        name = "WEAPON_SWMP9L",
        label = "Smith & Wesson M&P9",
        noTint = true,
        ammo = { label = "Munitions", hash = 'AMMO_PISTOL' },
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_SWMP9L_CLIP_01' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_PI_SWMP9L_FLSH' },
        },
    },
    {
        name = "WEAPON_SIG_SAUCER",
        label = "Sig Sauer",
        noTint = true,
        ammo = { label = "Munitions", hash = 'AMMO_PISTOL' },
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_SIG_SAUCER_MAG1' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_SIG_SAUCER_FLSH' },
        },
    },
    { name = "WEAPON_gtaserx", label = "Taser X vert", noTint = true, components = {} },
    { name = "WEAPON_taserx", label = "Taser X jaune", noTint = true, components = {} },
    {
        name = "WEAPON_HK416",
        label = "HK416",
        noTint = true,
        ammo = { label = "Munitions", hash = 'AMMO_RIFLE' },
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_HK416_CLIP_01' },
            { name = "clip_extended", label = "Chargeur allongé", hash = 'COMPONENT_HK416_CLIP_02' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_HK416_FLSH' },
            { name = "grip", label = "Poignée", hash = 'COMPONENT_AT_HK416_AFGRIP' },
        },
    },
    {
        name = "WEAPON_KS1",
        label = "KAC KS-1",
        noTint = true,
        ammo = { label = "Munitions", hash = 'AMMO_RIFLE' },
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_KS1_CLIP_01' },
            { name = "suppressor", label = "Silencieux", hash = 'COMPONENT_AT_KS1_SUPP' },
        },
    },
    {
        name = "WEAPON_M4A1CD",
        label = "M4A1",
        noTint = true,
        ammo = { label = "Munitions", hash = 'AMMO_RIFLE' },
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_M4A1CD_CLIP' },
            { name = "barrel", label = "Canon", hash = 'COMPONENT_M4A1CD_BARREL' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_M4A1CD_FLSH' },
            { name = "scope", label = "Lunette", hash = 'COMPONENT_M4A1CD_SCOPE' },
        },
    },
    {
        name = "WEAPON_AR15",
        label = "AR-15 PD",
        noTint = true,
        ammo = { label = "Munitions", hash = 'AMMO_RIFLE' },
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_PDAR15_CLIP_01' },
            { name = "flashlight", label = "Lampe torche", hash = 'COMPONENT_AT_AR_PDAR15_FLSH' },
        },
    },
    {
        name = "WEAPON_M870",
        label = "M870",
        noTint = true,
        ammo = { label = "Cartouches", hash = 'AMMO_SHOTGUN' },
        components = {},
    },
    {
        name = "WEAPON_PDPT700",
        label = "Remington M700",
        noTint = true,
        ammo = { label = "Munitions", hash = 'AMMO_SNIPER' },
        components = {
            { name = "clip_default", label = "Chargeur standard", hash = 'COMPONENT_PT700_CLIP_01' },
            { name = "scope", label = "Lunette", hash = 'COMPONENT_AT_SCOPE_PT700' },
        },
    },
    {
        name = "WEAPON_AIRSOFTKALASH47",
        label = "Airsoft Kalash-47",
        airsoft = true,
        ammo = { label = "Billes airsoft", hash = 'AMMO_RIFLE' },
        components = {
            { name = "clip_default", label = "Chargeur", hash = 'COMPONENT_AIRSOFTKALASH47_CLIP_01' },
            { name = "scope", label = "Lunette", hash = 'COMPONENT_AT_AIRSOFTAK47_SCOPE' },
        },
    },
    {
        name = "WEAPON_AIRSOFTBURST",
        label = "Airsoft Burst",
        airsoft = true,
        ammo = { label = "Billes airsoft", hash = 'AMMO_SMG' },
        components = {
            { name = "clip_default", label = "Chargeur", hash = 'COMPONENT_AIRSOFTBURST_CLIP_01' },
        },
    },
    {
        name = "WEAPON_AIRSOFTDRAGO",
        label = "Airsoft Drago",
        airsoft = true,
        ammo = { label = "Billes airsoft", hash = 'AMMO_RIFLE' },
        components = {
            { name = "clip_default", label = "Chargeur", hash = 'COMPONENT_AIRSOFTDRAGO_CLIP_01' },
        },
    },
    {
        name = "WEAPON_AIRSOFTFALCON57",
        label = "Airsoft Falcon-57",
        airsoft = true,
        ammo = { label = "Billes airsoft", hash = 'AMMO_PISTOL' },
        components = {
            { name = "clip_default", label = "Chargeur", hash = 'COMPONENT_AIRSOFTFALCON57_CLIP_01' },
        },
    },
    { name = "WEAPON_AIRSOFTGK36", label = "Airsoft GK36", airsoft = true, ammo = { label = "Billes airsoft", hash = 'AMMO_RIFLE' }, components = {} },
    { name = "WEAPON_AIRSOFTTITAN", label = "Airsoft Titan", airsoft = true, ammo = { label = "Billes airsoft", hash = 'AMMO_PISTOL' }, components = {} },
    {
        name = "WEAPON_AIRSOFTMQ14",
        label = "Airsoft MQ14",
        airsoft = true,
        ammo = { label = "Billes airsoft", hash = 'AMMO_SNIPER' },
        components = {
            { name = "clip_default", label = "Chargeur", hash = 'COMPONENT_AIRSOFTMQ14_CLIP_01' },
        },
    },
    {
        name = "WEAPON_AIRSOFTR594",
        label = "Airsoft R594",
        airsoft = true,
        ammo = { label = "Billes airsoft", hash = 'AMMO_MG' },
        components = {
            { name = "clip_default", label = "Chargeur", hash = 'COMPONENT_AIRSOFTR594_CLIP' },
        },
    },
    {
        name = "WEAPON_AIRSOFTC4A1",
        label = "Airsoft C4A1",
        airsoft = true,
        ammo = { label = "Billes airsoft", hash = 'AMMO_RIFLE' },
        components = {
            { name = "clip_default", label = "Chargeur", hash = 'COMPONENT_AIRSOFTC4A1_CLIP_01' },
        },
    },
    { name = "WEAPON_AIRSOFTPHANTOM5", label = "Airsoft Phantom-5", airsoft = true, ammo = { label = "Billes airsoft", hash = 'AMMO_SMG' }, components = {} },
    {
        name = "WEAPON_AIRSOFTPREDATOR90",
        label = "Airsoft Predator-90",
        airsoft = true,
        ammo = { label = "Billes airsoft", hash = 'AMMO_SMG' },
        components = {
            { name = "clip_default", label = "Chargeur", hash = 'COMPONENT_AIRSOFTPREDATOR90_CLIP_01' },
        },
    },
    { name = "WEAPON_AIRSOFTT870", label = "Airsoft Tactical 870", airsoft = true, ammo = { label = "Billes airsoft", hash = 'AMMO_SHOTGUN' }, components = {} },
    {
        name = "WEAPON_AIRSOFTSTORM",
        label = "Airsoft Storm",
        airsoft = true,
        ammo = { label = "Billes airsoft", hash = 'AMMO_RIFLE' },
        components = {
            { name = "clip_default", label = "Chargeur", hash = 'COMPONENT_AIRSOFTSTORM_CLIP_01' },
        },
    },
    { name = "WEAPON_AIRSOFTVIPER", label = "Airsoft Viper", airsoft = true, ammo = { label = "Billes airsoft", hash = 'AMMO_SMG' }, components = {} },
    {
        name = "WEAPON_AIRSOFTXTE",
        label = "Airsoft XTE",
        airsoft = true,
        ammo = { label = "Billes airsoft", hash = 'AMMO_PISTOL' },
        components = {
            { name = "clip_default", label = "Chargeur", hash = 'COMPONENT_AIRSOFTXTE_CLIP_01' },
        },
    },
}
