---@meta _
---@diagnostic disable: duplicate-doc-field

-- ============================================================
-- Carlist Staff - Catalogue de tous les vehicules du serveur
-- Utilise par client/staff/menu/carlist.lua
-- Chaque entree : { label = "...", model = "..." }
-- Les liveries sont detectees dynamiquement en jeu via GetVehicleLiveryCount()
-- ============================================================

VFW.Staff = VFW.Staff or {}
VFW.Staff.Carlist = {}

-- ============================================================
-- VEHICULES VANILLA GTA V (source: docs.fivem.net)
-- ============================================================

VFW.Staff.Carlist["Compactes"] = {
    { label = "Asbo",                model = "asbo" },
    { label = "Blista",              model = "blista" },
    { label = "Brioso R/A",         model = "brioso" },
    { label = "Brioso 300",         model = "brioso2" },
    { label = "Brioso 300 Widebody", model = "brioso3" },
    { label = "Club",               model = "club" },
    { label = "Dilettante",         model = "dilettante" },
    { label = "Dilettante 2",       model = "dilettante2" },
    { label = "Issi",               model = "issi2" },
    { label = "Issi Classic",       model = "issi3" },
    { label = "Issi Apocalypse",    model = "issi4" },
    { label = "Issi Future Shock",  model = "issi5" },
    { label = "Issi Nightmare",     model = "issi6" },
    { label = "Blista Kanjo",       model = "kanjo" },
    { label = "Panto",              model = "panto" },
    { label = "Prairie",            model = "prairie" },
    { label = "Rhapsody",           model = "rhapsody" },
    { label = "Weevil",             model = "weevil" },
}

VFW.Staff.Carlist["Berlines"] = {
    { label = "Asea",               model = "asea" },
    { label = "Asea 2",             model = "asea2" },
    { label = "Asterope",           model = "asterope" },
    { label = "Asterope GZ",        model = "asterope2" },
    { label = "Cinquemila",         model = "cinquemila" },
    { label = "Cognoscenti 55",     model = "cog55" },
    { label = "Cognoscenti 55 Blindee", model = "cog552" },
    { label = "Cognoscenti",        model = "cognoscenti" },
    { label = "Cognoscenti Blindee", model = "cognoscenti2" },
    { label = "Deity",              model = "deity" },
    { label = "Chavos V6",          model = "driftchavosv6" },
    { label = "Hardy (Drift)",      model = "drifthardy" },
    { label = "Emperor",            model = "emperor" },
    { label = "Emperor 2",          model = "emperor2" },
    { label = "Emperor 3",          model = "emperor3" },
    { label = "Fugitive",           model = "fugitive" },
    { label = "Glendale",           model = "glendale" },
    { label = "Glendale Custom",    model = "glendale2" },
    { label = "Hardy",              model = "hardy" },
    { label = "Impaler SZ",         model = "impaler5" },
    { label = "Ingot",              model = "ingot" },
    { label = "Intruder",           model = "intruder" },
    { label = "Turreted Limo",      model = "limo2" },
    { label = "Minimus",            model = "minimus" },
    { label = "Premier",            model = "premier" },
    { label = "Primo",              model = "primo" },
    { label = "Primo Custom",       model = "primo2" },
    { label = "Regina",             model = "regina" },
    { label = "Rhinehart",          model = "rhinehart" },
    { label = "Romero Hearse",      model = "romero" },
    { label = "Schafter",           model = "schafter2" },
    { label = "Schafter V12 Blindee", model = "schafter5" },
    { label = "Schafter LWB Blindee", model = "schafter6" },
    { label = "Stafford",           model = "stafford" },
    { label = "Stanier",            model = "stanier" },
    { label = "Stratum",            model = "stratum" },
    { label = "Stretch",            model = "stretch" },
    { label = "Super Diamond",      model = "superd" },
    { label = "Surge",              model = "surge" },
    { label = "Tailgater",          model = "tailgater" },
    { label = "Tailgater S",        model = "tailgater2" },
    { label = "Warrener",           model = "warrener" },
    { label = "Warrener HKR",       model = "warrener2" },
    { label = "Washington",         model = "washington" },
}

VFW.Staff.Carlist["SUV"] = {
    { label = "Aleutian",           model = "aleutian" },
    { label = "Astron",             model = "astron" },
    { label = "Baller",             model = "baller" },
    { label = "Baller 2",           model = "baller2" },
    { label = "Baller LE",          model = "baller3" },
    { label = "Baller LE LWB",      model = "baller4" },
    { label = "Baller LE Blindee",  model = "baller5" },
    { label = "Baller LE LWB Blindee", model = "baller6" },
    { label = "Baller ST",          model = "baller7" },
    { label = "Baller ST-D",        model = "baller8" },
    { label = "BeeJay XL",          model = "bjxl" },
    { label = "Cavalcade",          model = "cavalcade" },
    { label = "Cavalcade 2",        model = "cavalcade2" },
    { label = "Cavalcade XL",       model = "cavalcade3" },
    { label = "Contender",          model = "contender" },
    { label = "Dorado",             model = "dorado" },
    { label = "Dubsta",             model = "dubsta" },
    { label = "Dubsta 2",           model = "dubsta2" },
    { label = "Everon RS",          model = "everon3" },
    { label = "FQ 2",               model = "fq2" },
    { label = "Granger",            model = "granger" },
    { label = "Granger 3600LX",     model = "granger2" },
    { label = "Gresley",            model = "gresley" },
    { label = "Habanero",           model = "habanero" },
    { label = "Huntley S",          model = "huntley" },
    { label = "Issi Rally",         model = "issi8" },
    { label = "I-Wagen",            model = "iwagen" },
    { label = "Jubilee",            model = "jubilee" },
    { label = "Landstalker",        model = "landstalker" },
    { label = "Landstalker XL",     model = "landstalker2" },
    { label = "Mesa",               model = "mesa" },
    { label = "Mesa 2",             model = "mesa2" },
    { label = "Novak",              model = "novak" },
    { label = "Patriot",            model = "patriot" },
    { label = "Patriot Stretch",    model = "patriot2" },
    { label = "Radius",             model = "radi" },
    { label = "Rebla GTS",          model = "rebla" },
    { label = "Rocoto",             model = "rocoto" },
    { label = "Seminole",           model = "seminole" },
    { label = "Seminole Frontier",  model = "seminole2" },
    { label = "Serrano",            model = "serrano" },
    { label = "Squaddie",           model = "squaddie" },
    { label = "Toros",              model = "toros" },
    { label = "Vivanite",           model = "vivanite" },
    { label = "Woodlander",         model = "woodlander" },
    { label = "XLS",                model = "xls" },
    { label = "XLS Blindee",        model = "xls2" },
}

VFW.Staff.Carlist["Coupes"] = {
    { label = "Cognoscenti Cabrio", model = "cogcabrio" },
    { label = "FR36 (Drift)",       model = "driftfr36" },
    { label = "Sentinel XS (Drift)", model = "driftsent2" },
    { label = "Exemplar",           model = "exemplar" },
    { label = "F620",               model = "f620" },
    { label = "Felon",              model = "felon" },
    { label = "Felon GT",           model = "felon2" },
    { label = "FR36",               model = "fr36" },
    { label = "Jackal",             model = "jackal" },
    { label = "Kanjo SJ",           model = "kanjosj" },
    { label = "Oracle XS",          model = "oracle" },
    { label = "Oracle",             model = "oracle2" },
    { label = "Postlude",           model = "postlude" },
    { label = "Previon",            model = "previon" },
    { label = "Sentinel XS",        model = "sentinel" },
    { label = "Sentinel",           model = "sentinel2" },
    { label = "Sentinel XS4",       model = "sentinel6" },
    { label = "Windsor",            model = "windsor" },
    { label = "Windsor Drop",       model = "windsor2" },
    { label = "Zion",               model = "zion" },
    { label = "Zion Cabrio",        model = "zion2" },
}

VFW.Staff.Carlist["Muscles"] = {
    { label = "Blade",              model = "blade" },
    { label = "Brigham",            model = "brigham" },
    { label = "Broadway",           model = "broadway" },
    { label = "Buccaneer",          model = "buccaneer" },
    { label = "Buccaneer Custom",   model = "buccaneer2" },
    { label = "Buffalo STX",        model = "buffalo4" },
    { label = "Buffalo EVX",        model = "buffalo5" },
    { label = "Chino",              model = "chino" },
    { label = "Chino Custom",       model = "chino2" },
    { label = "Clique",             model = "clique" },
    { label = "Clique Wagon",       model = "clique2" },
    { label = "Coquette BlackFin",  model = "coquette3" },
    { label = "Deviant",            model = "deviant" },
    { label = "Dominator",          model = "dominator" },
    { label = "Dominator Pisswasser", model = "dominator2" },
    { label = "Dominator GTX",      model = "dominator3" },
    { label = "Dominator Apocalypse", model = "dominator4" },
    { label = "Dominator Future Shock", model = "dominator5" },
    { label = "Dominator Nightmare", model = "dominator6" },
    { label = "Dominator ASP",      model = "dominator7" },
    { label = "Dominator GTT",      model = "dominator8" },
    { label = "Dominator GT",       model = "dominator9" },
    { label = "Dominator GT (Drift)", model = "driftdom9" },
    { label = "Dominator FX",       model = "driftdominator10" },
    { label = "Gauntlet Hellfire (Drift)", model = "driftgauntlet4" },
    { label = "Yosemite (Drift)",   model = "driftyosemite" },
    { label = "Dukes",              model = "dukes" },
    { label = "Duke O'Death",       model = "dukes2" },
    { label = "Beater Dukes",       model = "dukes3" },
    { label = "Ellie",              model = "ellie" },
    { label = "Eudora",             model = "eudora" },
    { label = "Faction",            model = "faction" },
    { label = "Faction Custom",     model = "faction2" },
    { label = "Faction Donk",       model = "faction3" },
    { label = "Gauntlet",           model = "gauntlet" },
    { label = "Gauntlet Redwood",   model = "gauntlet2" },
    { label = "Gauntlet Classic",   model = "gauntlet3" },
    { label = "Gauntlet Hellfire",  model = "gauntlet4" },
    { label = "Gauntlet Classic Custom", model = "gauntlet5" },
    { label = "Greenwood",          model = "greenwood" },
    { label = "Hermes",             model = "hermes" },
    { label = "Hotknife",           model = "hotknife" },
    { label = "Hustler",            model = "hustler" },
    { label = "Impaler",            model = "impaler" },
    { label = "Impaler Apocalypse", model = "impaler2" },
    { label = "Impaler Future Shock", model = "impaler3" },
    { label = "Impaler Nightmare",  model = "impaler4" },
    { label = "Impaler LX",         model = "impaler6" },
    { label = "Imperator Apocalypse", model = "imperator" },
    { label = "Imperator Future Shock", model = "imperator2" },
    { label = "Imperator Nightmare", model = "imperator3" },
    { label = "Lurcher",            model = "lurcher" },
    { label = "Manana Custom",      model = "manana2" },
    { label = "Moonbeam",           model = "moonbeam" },
    { label = "Moonbeam Custom",    model = "moonbeam2" },
    { label = "Nightshade",         model = "nightshade" },
    { label = "Peyote Gasser",      model = "peyote2" },
    { label = "Phoenix",            model = "phoenix" },
    { label = "Picador",            model = "picador" },
    { label = "Rat-Loader",         model = "ratloader" },
    { label = "Rat-Truck",          model = "ratloader2" },
    { label = "Ruiner",             model = "ruiner" },
    { label = "Ruiner 2000",        model = "ruiner2" },
    { label = "Ruiner 3",           model = "ruiner3" },
    { label = "Ruiner ZZ-8",        model = "ruiner4" },
    { label = "Sabre Turbo",        model = "sabregt" },
    { label = "Sabre Turbo Custom", model = "sabregt2" },
    { label = "Slamvan",            model = "slamvan" },
    { label = "Lost Slamvan",       model = "slamvan2" },
    { label = "Slamvan Custom",     model = "slamvan3" },
    { label = "Slamvan Apocalypse", model = "slamvan4" },
    { label = "Slamvan Future Shock", model = "slamvan5" },
    { label = "Slamvan Nightmare",  model = "slamvan6" },
    { label = "Stallion",           model = "stalion" },
    { label = "Stallion Burger Shot", model = "stalion2" },
    { label = "Tahoma Coupe",       model = "tahoma" },
    { label = "Tampa",              model = "tampa" },
    { label = "Tampa Weaponized",   model = "tampa3" },
    { label = "Tampa GT",           model = "tampa4" },
    { label = "Tulip",              model = "tulip" },
    { label = "Tulip M-100",        model = "tulip2" },
    { label = "Vamos",              model = "vamos" },
    { label = "Vigero",             model = "vigero" },
    { label = "Vigero ZX",          model = "vigero2" },
    { label = "Vigero ZX Convertible", model = "vigero3" },
    { label = "Virgo",              model = "virgo" },
    { label = "Virgo Classic Custom", model = "virgo2" },
    { label = "Virgo Classic",       model = "virgo3" },
    { label = "Voodoo Custom",      model = "voodoo" },
    { label = "Voodoo",             model = "voodoo2" },
    { label = "Weevil Custom",      model = "weevil2" },
    { label = "Yosemite",           model = "yosemite" },
    { label = "Drift Yosemite",     model = "yosemite2" },
}

VFW.Staff.Carlist["Sport Classique"] = {
    { label = "Ardent",             model = "ardent" },
    { label = "Astrale",            model = "astrale" },
    { label = "Roosevelt",          model = "btype" },
    { label = "Franken Stange",     model = "btype2" },
    { label = "Roosevelt Valor",    model = "btype3" },
    { label = "Casco",              model = "casco" },
    { label = "Cheburek",           model = "cheburek" },
    { label = "Cheetah Classic",    model = "cheetah2" },
    { label = "Cheetah Classic LSCM", model = "cheetah3" },
    { label = "Coquette Classic",   model = "coquette2" },
    { label = "Deluxo",             model = "deluxo" },
    { label = "Dynasty",            model = "dynasty" },
    { label = "Fagaloa",            model = "fagaloa" },
    { label = "Feltzer Classic",    model = "feltzer3" },
    { label = "GT500",              model = "gt500" },
    { label = "GT750",              model = "gt750" },
    { label = "Infernus Classic",   model = "infernus2" },
    { label = "Itali Classic",      model = "itali2" },
    { label = "JB 700",             model = "jb700" },
    { label = "JB 700W",            model = "jb7002" },
    { label = "Mamba",              model = "mamba" },
    { label = "Manana",             model = "manana" },
    { label = "Michelli GT",        model = "michelli" },
    { label = "Monroe",             model = "monroe" },
    { label = "Nebula Turbo",       model = "nebula" },
    { label = "Peyote",             model = "peyote" },
    { label = "Peyote Custom",      model = "peyote3" },
    { label = "Pigalle",            model = "pigalle" },
    { label = "Rapid GT Classic",   model = "rapidgt3" },
    { label = "Retinue",            model = "retinue" },
    { label = "Retinue Mk II",      model = "retinue2" },
    { label = "Savestra",           model = "savestra" },
    { label = "Stinger",            model = "stinger" },
    { label = "Stinger GT",         model = "stingergt" },
    { label = "Stromberg",          model = "stromberg" },
    { label = "Swinger",            model = "swinger" },
    { label = "Toreador",           model = "toreador" },
    { label = "Torero",             model = "torero" },
    { label = "Tornado",            model = "tornado" },
    { label = "Tornado 2",          model = "tornado2" },
    { label = "Tornado 3",          model = "tornado3" },
    { label = "Tornado 4",          model = "tornado4" },
    { label = "Tornado Custom",     model = "tornado5" },
    { label = "Tornado Rat Rod",    model = "tornado6" },
    { label = "Turismo Classic",    model = "turismo2" },
    { label = "Viseris",            model = "viseris" },
    { label = "190z",               model = "z190" },
    { label = "Zion Classic",       model = "zion3" },
    { label = "Z-Type",             model = "ztype" },
}

VFW.Staff.Carlist["Sport"] = {
    { label = "Alpha",              model = "alpha" },
    { label = "Banshee",            model = "banshee" },
    { label = "Bestia GTS",         model = "bestiagts" },
    { label = "Blista Compact",     model = "blista2" },
    { label = "Blista Go Go Monkey", model = "blista3" },
    { label = "Buffalo",            model = "buffalo" },
    { label = "Buffalo S",          model = "buffalo2" },
    { label = "Buffalo Sprunk",     model = "buffalo3" },
    { label = "Calico GTF",         model = "calico" },
    { label = "Carbonizzare",       model = "carbonizzare" },
    { label = "Comet",              model = "comet2" },
    { label = "Comet Retro Custom", model = "comet3" },
    { label = "Comet Safari",       model = "comet4" },
    { label = "Comet SR",           model = "comet5" },
    { label = "Comet S2",           model = "comet6" },
    { label = "Comet S2 Cabrio",    model = "comet7" },
    { label = "Coquette",           model = "coquette" },
    { label = "Coquette D10",       model = "coquette4" },
    { label = "Corsita",            model = "corsita" },
    { label = "La Coureuse",        model = "coureur" },
    { label = "Cypher",             model = "cypher" },
    { label = "8F Drafter",         model = "drafter" },
    { label = "Euros (Drift)",      model = "drifteuros" },
    { label = "Futo GTX (Drift)",   model = "driftfuto" },
    { label = "Jester RR (Drift)",  model = "driftjester" },
    { label = "Remus (Drift)",      model = "driftremus" },
    { label = "RT3000 (Drift)",     model = "driftrt3" },
    { label = "Tampa (Drift)",      model = "drifttampa" },
    { label = "ZR350 (Drift)",      model = "driftzr350" },
    { label = "Elegy Retro Custom", model = "elegy" },
    { label = "Elegy RH8",          model = "elegy2" },
    { label = "Euros",              model = "euros" },
    { label = "Everon Hotring",     model = "everon2" },
    { label = "Feltzer",            model = "feltzer2" },
    { label = "Flash GT",           model = "flashgt" },
    { label = "Furore GT",          model = "furoregt" },
    { label = "Fusilade",           model = "fusilade" },
    { label = "Futo",               model = "futo" },
    { label = "Futo GTX",           model = "futo2" },
    { label = "Gauntlet Hotring",   model = "gauntlet6" },
    { label = "GB200",              model = "gb200" },
    { label = "Growler",            model = "growler" },
    { label = "Hotring Sabre",      model = "hotring" },
    { label = "Imorgon",            model = "imorgon" },
    { label = "Issi Sport",         model = "issi7" },
    { label = "Itali GTO",          model = "italigto" },
    { label = "Itali RSX",          model = "italirsx" },
    { label = "Jester",             model = "jester" },
    { label = "Jester Racecar",     model = "jester2" },
    { label = "Jester Classic",     model = "jester3" },
    { label = "Jester RR",          model = "jester4" },
    { label = "Jugular",            model = "jugular" },
    { label = "Khamelion",          model = "khamelion" },
    { label = "Komoda",             model = "komoda" },
    { label = "Kuruma",             model = "kuruma" },
    { label = "Kuruma Blindee",     model = "kuruma2" },
    { label = "Locust",             model = "locust" },
    { label = "Lynx",               model = "lynx" },
    { label = "Massacro",           model = "massacro" },
    { label = "Massacro Racecar",   model = "massacro2" },
    { label = "Neo",                model = "neo" },
    { label = "Neon",               model = "neon" },
    { label = "9F",                  model = "ninef" },
    { label = "9F Cabrio",          model = "ninef2" },
    { label = "Omnis",              model = "omnis" },
    { label = "Omnis e-GT",         model = "omnisegt" },
    { label = "Panthere",           model = "panthere" },
    { label = "Paragon R",          model = "paragon" },
    { label = "Paragon R Blindee",  model = "paragon2" },
    { label = "Pariah",             model = "pariah" },
    { label = "Penumbra",           model = "penumbra" },
    { label = "Penumbra FF",        model = "penumbra2" },
    { label = "300R",               model = "r300" },
    { label = "Raiden",             model = "raiden" },
    { label = "Rapid GT",           model = "rapidgt" },
    { label = "Rapid GT 2",         model = "rapidgt2" },
    { label = "Rapid GT X",         model = "rapidgt4" },
    { label = "Raptor",             model = "raptor" },
    { label = "Remus",              model = "remus" },
    { label = "Revolter",           model = "revolter" },
    { label = "RT3000",             model = "rt3000" },
    { label = "Ruston",             model = "ruston" },
    { label = "Schafter V12",       model = "schafter3" },
    { label = "Schafter LWB",       model = "schafter4" },
    { label = "Schlagen GT",        model = "schlagen" },
    { label = "Schwartzer",         model = "schwarzer" },
    { label = "Sentinel 3",         model = "sentinel3" },
    { label = "Sentinel Classic Widebody", model = "sentinel4" },
    { label = "Sentinel GTS",       model = "sentinel5" },
    { label = "Seven-70",           model = "seven70" },
    { label = "SM722",              model = "sm722" },
    { label = "Specter",            model = "specter" },
    { label = "Specter Custom",     model = "specter2" },
    { label = "Itali GTO Stinger TT", model = "stingertt" },
    { label = "Streiter",           model = "streiter" },
    { label = "Sugoi",              model = "sugoi" },
    { label = "Sultan",             model = "sultan" },
    { label = "Sultan Classic",     model = "sultan2" },
    { label = "Sultan RS Classic",  model = "sultan3" },
    { label = "Surano",             model = "surano" },
    { label = "Tampa (Sport)",      model = "tampa2" },
    { label = "10F",                model = "tenf" },
    { label = "10F Widebody",       model = "tenf2" },
    { label = "Tropos Rallye",      model = "tropos" },
    { label = "Vectre",             model = "vectre" },
    { label = "Verlierer",          model = "verlierer2" },
    { label = "Veto Classic",       model = "veto" },
    { label = "Veto Modern",        model = "veto2" },
    { label = "V-STR",              model = "vstr" },
    { label = "ZR350",              model = "zr350" },
    { label = "ZR380 Apocalypse",   model = "zr380" },
    { label = "ZR380 Future Shock", model = "zr3802" },
    { label = "ZR380 Nightmare",    model = "zr3803" },
}

VFW.Staff.Carlist["Super"] = {
    { label = "Adder",              model = "adder" },
    { label = "Autarch",            model = "autarch" },
    { label = "Banshee 900R",       model = "banshee2" },
    { label = "Bullet",             model = "bullet" },
    { label = "Champion",           model = "champion" },
    { label = "Cheetah",            model = "cheetah" },
    { label = "Cyclone",            model = "cyclone" },
    { label = "Deveste Eight",      model = "deveste" },
    { label = "Emerus",             model = "emerus" },
    { label = "Entity XXR",         model = "entity2" },
    { label = "Entity MT",          model = "entity3" },
    { label = "Entity XF",          model = "entityxf" },
    { label = "FMJ",                model = "fmj" },
    { label = "FMJ MK V",           model = "fmj2" },
    { label = "Furia",              model = "furia" },
    { label = "GP1",                model = "gp1" },
    { label = "Ignus",              model = "ignus" },
    { label = "Infernus",           model = "infernus" },
    { label = "Itali GTB",          model = "italigtb" },
    { label = "Itali GTB Custom",   model = "italigtb2" },
    { label = "Krieger",            model = "krieger" },
    { label = "RE-7B",              model = "le7b" },
    { label = "LM87",               model = "lm87" },
    { label = "Luiva",              model = "luiva" },
    { label = "Nero",               model = "nero" },
    { label = "Nero Custom",        model = "nero2" },
    { label = "Osiris",             model = "osiris" },
    { label = "Penetrator",         model = "penetrator" },
    { label = "811",                model = "pfister811" },
    { label = "X80 Proto",          model = "prototipo" },
    { label = "Reaper",             model = "reaper" },
    { label = "S80RR",              model = "s80" },
    { label = "SC1",                model = "sc1" },
    { label = "Scramjet",           model = "scramjet" },
    { label = "ETR1",               model = "sheava" },
    { label = "Sultan RS",          model = "sultanrs" },
    { label = "Suzume",             model = "suzume" },
    { label = "T20",                model = "t20" },
    { label = "Taipan",             model = "taipan" },
    { label = "Tempesta",           model = "tempesta" },
    { label = "Tezeract",           model = "tezeract" },
    { label = "Thrax",              model = "thrax" },
    { label = "Tigon",              model = "tigon" },
    { label = "Torero XO",          model = "torero2" },
    { label = "Turismo Omaggio",    model = "turismo3" },
    { label = "Turismo R",          model = "turismor" },
    { label = "Tyrant",             model = "tyrant" },
    { label = "Tyrus",              model = "tyrus" },
    { label = "Vacca",              model = "vacca" },
    { label = "Vagner",             model = "vagner" },
    { label = "Vigilante",          model = "vigilante" },
    { label = "Virtue",             model = "virtue" },
    { label = "Visione",            model = "visione" },
    { label = "Voltic",             model = "voltic" },
    { label = "Rocket Voltic",      model = "voltic2" },
    { label = "XA-21",              model = "xa21" },
    { label = "X-treme",            model = "xtreme" },
    { label = "Zeno",               model = "zeno" },
    { label = "Zentorno",           model = "zentorno" },
    { label = "Zorrusso",           model = "zorrusso" },
}

VFW.Staff.Carlist["Motos"] = {
    { label = "Akuma",              model = "akuma" },
    { label = "Avarus",             model = "avarus" },
    { label = "Bagger",             model = "bagger" },
    { label = "Bati 801",           model = "bati" },
    { label = "Bati 801RR",         model = "bati2" },
    { label = "BF400",              model = "bf400" },
    { label = "Carbon RS",          model = "carbonrs" },
    { label = "Chimera",            model = "chimera" },
    { label = "Cliffhanger",        model = "cliffhanger" },
    { label = "Daemon",             model = "daemon" },
    { label = "Daemon Custom",      model = "daemon2" },
    { label = "Deathbike Apocalypse", model = "deathbike" },
    { label = "Deathbike Future Shock", model = "deathbike2" },
    { label = "Deathbike Nightmare", model = "deathbike3" },
    { label = "Defiler",            model = "defiler" },
    { label = "Diabolus",           model = "diablous" },
    { label = "Diabolus Custom",    model = "diablous2" },
    { label = "Double-T",           model = "double" },
    { label = "Enduro",             model = "enduro" },
    { label = "Esskey",             model = "esskey" },
    { label = "Faggio Sport",       model = "faggio" },
    { label = "Faggio",             model = "faggio2" },
    { label = "Faggio Mod",         model = "faggio3" },
    { label = "FCR 1000",           model = "fcr" },
    { label = "FCR 1000 Custom",    model = "fcr2" },
    { label = "Gargoyle",           model = "gargoyle" },
    { label = "Hakuchou",           model = "hakuchou" },
    { label = "Hakuchou Drag",      model = "hakuchou2" },
    { label = "Hexer",              model = "hexer" },
    { label = "Innovation",         model = "innovation" },
    { label = "Lectro",             model = "lectro" },
    { label = "Manchez",            model = "manchez" },
    { label = "Manchez Scout",      model = "manchez2" },
    { label = "Manchez Scout C",    model = "manchez3" },
    { label = "Nemesis",            model = "nemesis" },
    { label = "Nightblade",         model = "nightblade" },
    { label = "Oppressor",          model = "oppressor" },
    { label = "Oppressor Mk II",    model = "oppressor2" },
    { label = "PCJ 600",            model = "pcj" },
    { label = "Powersurge",         model = "powersurge" },
    { label = "Rat Bike",           model = "ratbike" },
    { label = "Reever",             model = "reever" },
    { label = "Rampant Rocket",     model = "rrocket" },
    { label = "Ruffian",            model = "ruffian" },
    { label = "Sanchez",            model = "sanchez" },
    { label = "Sanchez 2",          model = "sanchez2" },
    { label = "Sanctus",            model = "sanctus" },
    { label = "Shinobi",            model = "shinobi" },
    { label = "Shotaro",            model = "shotaro" },
    { label = "Sovereign",          model = "sovereign" },
    { label = "Stryder",            model = "stryder" },
    { label = "Thrust",             model = "thrust" },
    { label = "Vader",              model = "vader" },
    { label = "Vindicator",         model = "vindicator" },
    { label = "Vortex",             model = "vortex" },
    { label = "Wolfsbane",          model = "wolfsbane" },
    { label = "Zombie Bobber",      model = "zombiea" },
    { label = "Zombie Chopper",     model = "zombieb" },
}

VFW.Staff.Carlist["Tout-Terrain"] = {
    { label = "Injection",          model = "bfinjection" },
    { label = "Bifta",              model = "bifta" },
    { label = "Blazer",             model = "blazer" },
    { label = "Blazer Lifeguard",   model = "blazer2" },
    { label = "Hot Rod Blazer",     model = "blazer3" },
    { label = "Street Blazer",      model = "blazer4" },
    { label = "Blazer Aqua",        model = "blazer5" },
    { label = "Bodhi",              model = "bodhi2" },
    { label = "Boor",               model = "boor" },
    { label = "Brawler",            model = "brawler" },
    { label = "Bruiser Apocalypse", model = "bruiser" },
    { label = "Bruiser Future Shock", model = "bruiser2" },
    { label = "Bruiser Nightmare",  model = "bruiser3" },
    { label = "Brutus Apocalypse",  model = "brutus" },
    { label = "Brutus Future Shock", model = "brutus2" },
    { label = "Brutus Nightmare",   model = "brutus3" },
    { label = "Caracara",           model = "caracara" },
    { label = "Caracara 4x4",       model = "caracara2" },
    { label = "Duneloader",         model = "dloader" },
    { label = "Draugur",            model = "draugur" },
    { label = "Drift Walkton L35",  model = "driftl352" },
    { label = "Dubsta 6x6",         model = "dubsta3" },
    { label = "Dune Buggy",         model = "dune" },
    { label = "Space Docker",       model = "dune2" },
    { label = "Dune FAV",           model = "dune3" },
    { label = "Ramp Buggy",         model = "dune4" },
    { label = "Ramp Buggy 2",       model = "dune5" },
    { label = "Freecrawler",        model = "freecrawler" },
    { label = "Hellion",            model = "hellion" },
    { label = "Insurgent Pick-Up",  model = "insurgent" },
    { label = "Insurgent",          model = "insurgent2" },
    { label = "Insurgent Pick-Up Custom", model = "insurgent3" },
    { label = "Kalahari",           model = "kalahari" },
    { label = "Kamacho",            model = "kamacho" },
    { label = "Walton L35",         model = "l35" },
    { label = "Walton L35 Stock",   model = "l352" },
    { label = "Marshall",           model = "marshall" },
    { label = "Menacer",            model = "menacer" },
    { label = "Mesa (Off-Road)",    model = "mesa3" },
    { label = "Monster",            model = "monster" },
    { label = "Sasquatch Apocalypse", model = "monster3" },
    { label = "Sasquatch Future Shock", model = "monster4" },
    { label = "Sasquatch Nightmare", model = "monster5" },
    { label = "MonstroCiti",        model = "monstrociti" },
    { label = "Nightshark",         model = "nightshark" },
    { label = "Outlaw",             model = "outlaw" },
    { label = "Patriot Mil-Spec",   model = "patriot3" },
    { label = "Rancher XL",         model = "rancherxl" },
    { label = "Rancher XL 2",       model = "rancherxl2" },
    { label = "Ratel",              model = "ratel" },
    { label = "RC Bandito",         model = "rcbandito" },
    { label = "Rusty Rebel",        model = "rebel" },
    { label = "Rebel",              model = "rebel2" },
    { label = "Riata",              model = "riata" },
    { label = "Sandking XL",        model = "sandking" },
    { label = "Sandking SWB",       model = "sandking2" },
    { label = "Technical",          model = "technical" },
    { label = "Technical Aqua",     model = "technical2" },
    { label = "Technical Custom",   model = "technical3" },
    { label = "Terminus",           model = "terminus" },
    { label = "Trophy Truck",       model = "trophytruck" },
    { label = "Desert Raid",        model = "trophytruck2" },
    { label = "Vagrant",            model = "vagrant" },
    { label = "Verus",              model = "verus" },
    { label = "Winky",              model = "winky" },
    { label = "Yosemite Rancher",   model = "yosemite3" },
    { label = "Zhaba",              model = "zhaba" },
}

VFW.Staff.Carlist["Quads"] = {
    { label = "YFZ 450 Bay 1",      model = "yfz450bay1" },
    { label = "R1M",                model = "solo450" },
    { label = "XK20 Scrambler",     model = "xk20scrambler" },
    { label = "Raptor 700",         model = "raptor700" },
    { label = "WF YFZ 450 22",      model = "wfyfz45022" },
    { label = "GODz NINJAH 2 Quad", model = "GODzNINJAH2QUAD" },
}

VFW.Staff.Carlist["Vans"] = {
    { label = "Bison",              model = "bison" },
    { label = "Bison 2",            model = "bison2" },
    { label = "Bison 3",            model = "bison3" },
    { label = "Bobcat XL",          model = "bobcatxl" },
    { label = "Boxville",           model = "boxville" },
    { label = "Boxville 2",         model = "boxville2" },
    { label = "Boxville 3",         model = "boxville3" },
    { label = "Boxville 4",         model = "boxville4" },
    { label = "Boxville Blindee",   model = "boxville5" },
    { label = "Boxville LSDS",      model = "boxville6" },
    { label = "Burrito",            model = "burrito" },
    { label = "Bugstars Burrito",   model = "burrito2" },
    { label = "Burrito 3",          model = "burrito3" },
    { label = "Burrito 4",          model = "burrito4" },
    { label = "Burrito 5",          model = "burrito5" },
    { label = "Camper",             model = "camper" },
    { label = "Gang Burrito",       model = "gburrito" },
    { label = "Gang Burrito 2",     model = "gburrito2" },
    { label = "Journey",            model = "journey" },
    { label = "Journey II",         model = "journey2" },
    { label = "Minivan",            model = "minivan" },
    { label = "Minivan Custom",     model = "minivan2" },
    { label = "Paradise",           model = "paradise" },
    { label = "Pony",               model = "pony" },
    { label = "Pony 2",             model = "pony2" },
    { label = "Rumpo",              model = "rumpo" },
    { label = "Rumpo 2",            model = "rumpo2" },
    { label = "Rumpo Custom",       model = "rumpo3" },
    { label = "Speedo",             model = "speedo" },
    { label = "Clown Van",          model = "speedo2" },
    { label = "Speedo Custom",      model = "speedo4" },
    { label = "Speedo Custom 2",    model = "speedo5" },
    { label = "Surfer",             model = "surfer" },
    { label = "Surfer 2",           model = "surfer2" },
    { label = "Surfer Custom",      model = "surfer3" },
    { label = "Taco Van",           model = "taco" },
    { label = "Youga",              model = "youga" },
    { label = "Youga Classic",      model = "youga2" },
    { label = "Youga Classic 4x4",  model = "youga3" },
    { label = "Youga Custom",       model = "youga4" },
}

VFW.Staff.Carlist["Industriel"] = {
    { label = "Dozer",              model = "bulldozer" },
    { label = "Cutter",             model = "cutter" },
    { label = "Dump",               model = "dump" },
    { label = "Flatbed",            model = "flatbed" },
    { label = "Custom Flatbed",     model = "flatbed2" },
    { label = "Guardian",           model = "guardian" },
    { label = "Dock Handler",       model = "handler" },
    { label = "Mixer",              model = "mixer" },
    { label = "Mixer 2",            model = "mixer2" },
    { label = "Rubble",             model = "rubble" },
    { label = "Tipper",             model = "tiptruck" },
    { label = "Tipper 2",           model = "tiptruck2" },
}

VFW.Staff.Carlist["Utilitaires"] = {
    { label = "Airtug",             model = "airtug" },
    { label = "Caddy",              model = "caddy" },
    { label = "Caddy 2",            model = "caddy2" },
    { label = "Caddy 3",            model = "caddy3" },
    { label = "Keitora (Drift)",    model = "dkeitora" },
    { label = "Docktug",            model = "docktug" },
    { label = "Forklift",           model = "forklift" },
    { label = "Keitora",            model = "keitora" },
    { label = "Lawn Mower",         model = "mower" },
    { label = "Ripley",             model = "ripley" },
    { label = "Sadler",             model = "sadler" },
    { label = "Sadler 2",           model = "sadler2" },
    { label = "Scrap Truck",        model = "scrap" },
    { label = "Slamtruck",          model = "slamtruck" },
    { label = "Tow Truck",          model = "towtruck" },
    { label = "Tow Truck 2",        model = "towtruck2" },
    { label = "Tow Truck 3",        model = "towtruck3" },
    { label = "Tow Truck 4",        model = "towtruck4" },
    { label = "Tractor",            model = "tractor" },
    { label = "Fieldmaster",        model = "tractor2" },
    { label = "Fieldmaster 2",      model = "tractor3" },
    { label = "Utility Truck",      model = "utillitruck" },
    { label = "Utility Truck 2",    model = "utillitruck2" },
    { label = "Utility Truck 3",    model = "utillitruck3" },
}

VFW.Staff.Carlist["Commercial"] = {
    { label = "Benson",             model = "benson" },
    { label = "Biff",               model = "biff" },
    { label = "Cerberus Apocalypse", model = "cerberus" },
    { label = "Cerberus Future Shock", model = "cerberus2" },
    { label = "Cerberus Nightmare", model = "cerberus3" },
    { label = "Hauler",             model = "hauler" },
    { label = "Hauler Custom",      model = "hauler2" },
    { label = "Mule",               model = "mule" },
    { label = "Mule 2",             model = "mule2" },
    { label = "Mule 3",             model = "mule3" },
    { label = "Mule Custom",        model = "mule4" },
    { label = "Mule 5",             model = "mule5" },
    { label = "Packer",             model = "packer" },
    { label = "Phantom",            model = "phantom" },
    { label = "Phantom Wedge",      model = "phantom2" },
    { label = "Phantom Custom",     model = "phantom3" },
    { label = "Pounder",            model = "pounder" },
    { label = "Pounder Custom",     model = "pounder2" },
    { label = "Stockade",           model = "stockade" },
    { label = "Stockade 2",         model = "stockade3" },
    { label = "Terrorbyte",         model = "terbyte" },
}

VFW.Staff.Carlist["Velos"] = {
    { label = "BMX",                model = "bmx" },
    { label = "Cruiser",            model = "cruiser" },
    { label = "Fixter",             model = "fixter" },
    { label = "Inductor",           model = "inductor" },
    { label = "Inductor Junk Energy", model = "inductor2" },
    { label = "Scorcher",           model = "scorcher" },
    { label = "Whippet Race Bike",  model = "tribike" },
    { label = "Endurex Race Bike",  model = "tribike2" },
    { label = "Tri-Cycles Race Bike", model = "tribike3" },
}

VFW.Staff.Carlist["Bateaux"] = {
    { label = "Avisa",              model = "avisa" },
    { label = "Dinghy",             model = "dinghy" },
    { label = "Dinghy 2",           model = "dinghy2" },
    { label = "Dinghy 3",           model = "dinghy3" },
    { label = "Dinghy 4",           model = "dinghy4" },
    { label = "Dinghy Weaponized",  model = "dinghy5" },
    { label = "Jetmax",             model = "jetmax" },
    { label = "Kosatka",            model = "kosatka" },
    { label = "Longfin",            model = "longfin" },
    { label = "Marquis",            model = "marquis" },
    { label = "Kurtz 31 Patrol Boat", model = "patrolboat" },
    { label = "Police Predator",    model = "predator" },
    { label = "Seashark",           model = "seashark" },
    { label = "Seashark 2",         model = "seashark2" },
    { label = "Seashark 3",         model = "seashark3" },
    { label = "Speeder",            model = "speeder" },
    { label = "Speeder 2",          model = "speeder2" },
    { label = "Squalo",             model = "squalo" },
    { label = "Submersible",        model = "submersible" },
    { label = "Kraken",             model = "submersible2" },
    { label = "Suntrap",            model = "suntrap" },
    { label = "Toro",               model = "toro" },
    { label = "Toro 2",             model = "toro2" },
    { label = "Tropic",             model = "tropic" },
    { label = "Tropic 2",           model = "tropic2" },
    { label = "Tug",                model = "tug" },
}

VFW.Staff.Carlist["Helicopteres"] = {
    { label = "Akula",              model = "akula" },
    { label = "Annihilator",        model = "annihilator" },
    { label = "Annihilator Stealth", model = "annihilator2" },
    { label = "Buzzard Attack Chopper", model = "buzzard" },
    { label = "Buzzard",            model = "buzzard2" },
    { label = "Cargobob",           model = "cargobob" },
    { label = "Cargobob 2",         model = "cargobob2" },
    { label = "Cargobob 3",         model = "cargobob3" },
    { label = "Cargobob 4",         model = "cargobob4" },
    { label = "Conada",             model = "conada" },
    { label = "Frogger",            model = "frogger" },
    { label = "Frogger 2",          model = "frogger2" },
    { label = "Havok",              model = "havok" },
    { label = "FH-1 Hunter",        model = "hunter" },
    { label = "Maverick",           model = "maverick" },
    { label = "Police Maverick",    model = "polmav" },
    { label = "Savage",             model = "savage" },
    { label = "Sea Sparrow",        model = "seasparrow" },
    { label = "Sparrow",            model = "seasparrow2" },
    { label = "Sparrow 2",          model = "seasparrow3" },
    { label = "Skylift",            model = "skylift" },
    { label = "SuperVolito",        model = "supervolito" },
    { label = "SuperVolito Carbon", model = "supervolito2" },
    { label = "Swift",              model = "swift" },
    { label = "Swift Deluxe",       model = "swift2" },
    { label = "Valkyrie",           model = "valkyrie" },
    { label = "Valkyrie MOD.0",     model = "valkyrie2" },
    { label = "Volatus",            model = "volatus" },
}

VFW.Staff.Carlist["Avions"] = {
    { label = "Alkonost",           model = "alkonost" },
    { label = "Alpha-Z1",           model = "alphaz1" },
    { label = "Avenger",            model = "avenger" },
    { label = "Avenger 2",          model = "avenger2" },
    { label = "Besra",              model = "besra" },
    { label = "Blimp",              model = "blimp" },
    { label = "Xero Blimp",         model = "blimp2" },
    { label = "Blimp 3",            model = "blimp3" },
    { label = "Bombushka",          model = "bombushka" },
    { label = "Cargo Plane",        model = "cargoplane" },
    { label = "Cargo Plane 2",      model = "cargoplane2" },
    { label = "Cuban 800",          model = "cuban800" },
    { label = "Dodo",               model = "dodo" },
    { label = "Duster",             model = "duster" },
    { label = "Howard NX-25",       model = "howard" },
    { label = "Hydra",              model = "hydra" },
    { label = "Jet",                model = "jet" },
    { label = "P-996 LAZER",        model = "lazer" },
    { label = "Luxor",              model = "luxor" },
    { label = "Luxor Deluxe",       model = "luxor2" },
    { label = "Mammatus",           model = "mammatus" },
    { label = "Ultralight",         model = "microlight" },
    { label = "Miljet",             model = "miljet" },
    { label = "Mogul",              model = "mogul" },
    { label = "Molotok",            model = "molotok" },
    { label = "Nimbus",             model = "nimbus" },
    { label = "Nokota",             model = "nokota" },
    { label = "Pyro",               model = "pyro" },
    { label = "Rogue",              model = "rogue" },
    { label = "Seabreeze",          model = "seabreeze" },
    { label = "Shamal",             model = "shamal" },
    { label = "Starling",           model = "starling" },
    { label = "B-11 Strikeforce",   model = "strikeforce" },
    { label = "Mallard",            model = "stunt" },
    { label = "Titan",              model = "titan" },
    { label = "Tula",               model = "tula" },
    { label = "Velum",              model = "velum" },
    { label = "Velum 5-Seater",     model = "velum2" },
    { label = "Vestra",             model = "vestra" },
    { label = "Volatol",            model = "volatol" },
}

VFW.Staff.Carlist["Militaire"] = {
    { label = "APC",                model = "apc" },
    { label = "Barracks",           model = "barracks" },
    { label = "Barracks Semi",      model = "barracks2" },
    { label = "Barracks 3",         model = "barracks3" },
    { label = "Barrage",            model = "barrage" },
    { label = "Chernobog",          model = "chernobog" },
    { label = "Crusader",           model = "crusader" },
    { label = "Half-track",         model = "halftrack" },
    { label = "TM-02 Khanjali",     model = "khanjali" },
    { label = "Invade and Persuade Tank", model = "minitank" },
    { label = "Rhino Tank",         model = "rhino" },
    { label = "Scarab Apocalypse",  model = "scarab" },
    { label = "Scarab Future Shock", model = "scarab2" },
    { label = "Scarab Nightmare",   model = "scarab3" },
    { label = "Thruster",           model = "thruster" },
    { label = "Vetir",              model = "vetir" },
}

VFW.Staff.Carlist["Urgences (Vanilla)"] = {
    { label = "Ambulance",          model = "ambulance" },
    { label = "FIB",                model = "fbi" },
    { label = "FIB 2",              model = "fbi2" },
    { label = "Fire Truck",         model = "firetruk" },
    { label = "Lifeguard",          model = "lguard" },
    { label = "Prison Bus",         model = "pbus" },
    { label = "Police Cruiser",     model = "police" },
    { label = "Police Cruiser 2",   model = "police2" },
    { label = "Police Cruiser 3",   model = "police3" },
    { label = "Unmarked Cruiser",   model = "police4" },
    { label = "Police Bike",        model = "policeb" },
    { label = "Police Rancher",     model = "policeold1" },
    { label = "Police Roadcruiser", model = "policeold2" },
    { label = "Police Transporter", model = "policet" },
    { label = "Park Ranger",        model = "pranger" },
    { label = "Police Riot",        model = "riot" },
    { label = "RCV",                model = "riot2" },
    { label = "Sheriff Cruiser",    model = "sheriff" },
    { label = "Sheriff SUV",        model = "sheriff2" },
}

VFW.Staff.Carlist["Service"] = {
    { label = "Airport Bus",        model = "airbus" },
    { label = "Brickade",           model = "brickade" },
    { label = "Brickade 6x6",       model = "brickade2" },
    { label = "Bus",                model = "bus" },
    { label = "Dashound",           model = "coach" },
    { label = "Festival Bus",       model = "pbus2" },
    { label = "Dune (Rallytruck)",  model = "rallytruck" },
    { label = "Rental Shuttle Bus", model = "rentalbus" },
    { label = "Taxi",               model = "taxi" },
    { label = "Tourbus",            model = "tourbus" },
    { label = "Trashmaster",        model = "trash" },
    { label = "Trashmaster 2",      model = "trash2" },
    { label = "Wastelander",        model = "wastelander" },
}

-- ============================================================
-- VEHICULES CUSTOM / METIER
-- ============================================================

VFW.Staff.Carlist["Vehicules Custom"] = {
    -- LI Speedo Guizoo (fourgon presse)
    { label = "Life Speedo",        model = "LifeSpeedo" },
    -- Resto LTD Guizoo (fourgon retro)
    { label = "Resto LTD",          model = "restopeedo" },
    -- SpeedoMetier (fourgon metier)
    { label = "Speedo Metier",      model = "mspeedo" },

    { label = "Speedo Farm",    model = "nspeedo" },

    { label = "Speedo Bar", model = "barspeedo" },
    -- LI Mav Guizoo (helico presse)
    { label = "News Maverick",      model = "newsmav" },
    { label = "Weazel Maverick",   model = "wzmaverick" },
    -- Depanneuse custom
    { label = "Depanneuse",         model = "tcguardow" },
    -- Towtruck custom
    { label = "Towtruck",           model = "guiztow" },
    -- Taxi custom
    { label = "Vanilla Taxi Baller", model = "dlballer8taxi" },
    { label = "Vanilla Taxi Cinquemila", model = "dlcinqtaxi" },
    { label = "Vanilla Taxi Jugular", model = "dljugulartaxi" },
    { label = "Vanilla Taxi Rhine", model = "dlrhinetaxi" },
}

-- ============================================================
-- VEHICULES METIER (Police, EMS, etc.)
-- ============================================================

VFW.Staff.Carlist["Vehicules Police"] = {
    { label = "Riot",               model = "riot2" },
    -- LSPD
    { label = "LSPD Helico",        model = "policejpheli" },
    { label = "BCPD 10",            model = "bcpd10" },
    { label = "Command",            model = "command" },
    { label = "Buffalo Trafic",     model = "bufsxtrafpol" },
    { label = "Alamo UMK",          model = "umkalamo" },
    { label = "Alamo UMK 4",        model = "trualamo4" },
    { label = "Alamo UMK 3",        model = "trualamo3" },
    { label = "Fugitive",           model = "polfugitivep" },
    { label = "Alamo",              model = "polalamop2" },
    { label = "Buffalo",            model = "polbuffalop" },
    { label = "Buffalo V2",         model = "polbuffalop2" },
    { label = "Caracara",           model = "polcarap" },
    { label = "Scout",              model = "polscoutp" },
    { label = "Speedo",             model = "polspeedop" },
    { label = "Stanier",            model = "polstanierp" },
    { label = "Torence",            model = "poltorencep" },
    { label = "Stalker",            model = "polstalkerp" },
    { label = "Retro",              model = "policebretro" },
    { label = "Scout Trafic",       model = "nscouttrafpol" },
    { label = "Moto Police",        model = "polbikeb" },
    { label = "Moto Police V2",     model = "polbikeb2" },
    -- SASP
    { label = "SASP Buffalo",       model = "saspbuffalop" },
    { label = "SASP Buffalo V2",    model = "saspbuffalop2" },
    { label = "SASP Retro",         model = "saspbretro" },
    { label = "SASP Caracara",      model = "saspcarap" },
    { label = "SASP Felon",         model = "saspfelon10" },
    { label = "SASP Fugitive",      model = "saspfugitivep" },
    { label = "SASP Alamo",         model = "saspalamop2" },
    { label = "SASP Scout",         model = "saspscoutp" },
    { label = "SASP Speedo",        model = "saspspeedop" },
    { label = "SASP Stalker",       model = "saspstalkerp" },
    { label = "SASP Stanier",       model = "saspstanierp" },
    { label = "SASP Torence",       model = "sasptorencep" },
    { label = "SASP SWAT Stockade", model = "saspswatstoc" },
    { label = "SASP Command",       model = "saspcommand" },
    { label = "SASP Warden 7",      model = "saspgwarden7" },
    { label = "SASP Warden 8",      model = "saspgwarden8" },
    { label = "SASP Helico",        model = "saspjpheli" },
    { label = "SASP Maverick",      model = "saspmaverick2" },
    { label = "SASP Coach",         model = "saspcoach2" },
    -- Speciaux
    { label = "Warden 8",           model = "gwarden8" },
    { label = "Warden 7",           model = "gwarden7" },
    { label = "Coach",              model = "coach2" },
    { label = "Maverick",           model = "maverick2" },
    { label = "SWAT Van",           model = "swatvanr2" },
    { label = "SWAT Insurgent",     model = "swatinsur" },
    { label = "SWAT Stockade",      model = "swatstoc" },
    { label = "Halfback",           model = "halfback2" },
    { label = "Roadrunner",         model = "roadrunner3" },
    { label = "Hazard",             model = "hazard2" },
    { label = "USSS SUV",           model = "ussssuv2" },
    { label = "USSS Flag",          model = "usssflag" },
    { label = "Inaugural",          model = "inaugural2" },
    { label = "Det Torencer",      model = "dettorencer" },
}

VFW.Staff.Carlist["Secours"] = {
    { label = "Ambulance",              model = "ambulance" },
    { label = "Alamo (SUV)",            model = "emsalamo" },
    { label = "Ambulance Van",          model = "emsamb" },
    { label = "Ambulance Van 2",        model = "emsamb2" },
    { label = "Ambulance Van 3",        model = "emsamb3" },
    { label = "BF400 (Moto)",           model = "emsbf400" },
    { label = "Buffalo (EMS)",          model = "emsbuff" },
    { label = "Caracara (EMS)",         model = "emscara" },
    { label = "Camion CMD",             model = "emscmd" },
    { label = "Dinghy (Bateau)",        model = "emsdinghy" },
    { label = "Fire Truck",             model = "firetruk" },
    { label = "Fugitive (EMS)",         model = "emsfugitive" },
    { label = "Maverick (Helico)",      model = "emsmav" },
    { label = "Scout (EMS)",            model = "emsscout" },
    { label = "Sandstorm Ambulance",    model = "hvsandbulance" },
    { label = "Speedo Ambulance",       model = "hvemsnspeed" },
    { label = "Declasse Alamo (SAMS)",  model = "hvsamsalamo" },
    { label = "Vapid Aleutian (SAMS)",  model = "hvsamsaleutian" },
    { label = "Dinghy Boat (SAMS)",     model = "hvsamsboat" },
    { label = "Buffalo STX (SAMS)",     model = "hvsamsbuff4" },
    { label = "Canis Terminus (SAMS)",  model = "hvsamsterminus" },
    { label = "Vapid Scout (SAMS)",     model = "hvsamsscout" },
    { label = "Vapid Caracara (SAMS)",  model = "hvsamscara" },
    { label = "Nagasaki Moto (SAMS)",   model = "hvsamsnag" },
    { label = "Conoda Helicopter",      model = "hvconada" },
}

VFW.Staff.Carlist["USSS / GOUV"] = {
    { label = "USSS Stanier",         model = "ussspstanier" },
    { label = "USSS Stanier V2",      model = "ussspstanier2" },
    { label = "USSS Buffalo",         model = "ussspbuffalo" },
    { label = "USSS Granger",         model = "ussspgranger" },
    { label = "USSS Alamo",           model = "ussspalamo" },
    { label = "USSS Scout",           model = "ussspscout" },
    { label = "USSS Torrence",        model = "usssptorrence" },
    { label = "USSS Moto",            model = "ussspbike" },
    { label = "USSS Bomb Squad",      model = "ussspbombs" },
    { label = "USSS SUV",             model = "ussssuv2" },
    { label = "USSS Flag",            model = "usssflag" },
    { label = "Inaugural",            model = "inaugural2" },
    { label = "Det Torencer",        model = "dettorencer" },
}

VFW.Staff.Carlist["Moto MC"] = {
    { label = "BlueStar Lost MC",    model = "bluestar" },
    { label = "Devotee Lost MC", model = "devotee" },
    { label = "Dyne Lost MC",     model = "dyne" },
}

VFW.Staff.Carlist["30 Pack"] = {
    { label = "204s Petro",              model = "204spetro" },
    { label = "720S DD",                 model = "720sdd" },
    { label = "Carsons Prior RS3",       model = "CarsonsPriorRS3" },
    { label = "DB B800",                 model = "DBb800" },
    { label = "Demon UTE",              model = "GODzDEMONUTE" },
    { label = "Hycade MK4 V2",          model = "GODzHYCADEMK4V2" },
    { label = "Hycade R34",             model = "GODzHYCADER34" },
    { label = "KR CRX7 FD",             model = "GODzKRCRX7FD" },
    { label = "Zonda JC",               model = "TCZjc" },
    { label = "GTR WB Mega",            model = "ToraGTRWBMega" },
    { label = "ABF RSQ8",               model = "abfrsq8" },
    { label = "Alley GS400",            model = "amgs400" },
    { label = "GT700",                   model = "brabusgt700" },
    { label = "Camaro 68T",             model = "camaro68t" },
    { label = "Apertos V1",             model = "carboDRCustoM" },
    { label = "Carrera GT",              model = "carreragt" },
    { label = "DDC Emperor",             model = "ddcemperor" },
    { label = "X6 M Larte",             model = "drex6mlarte" },
    { label = "DZ Daytona",             model = "dzdaytona" },
    { label = "F1 90E",                 model = "f190e" },
    { label = "F22 Thawk",              model = "f22thawk" },
    { label = "F450",                    model = "f450" },
    { label = "F8 Tributo",             model = "ff8tributo" },
    { label = "Firebird WZ",            model = "firebirdwz" },
    { label = "Jesko",                   model = "fjesko" },
    { label = "F Magnum",               model = "fmagnum" },
    { label = "Divo",                    model = "gdivo" },
    { label = "Hoonitruck",             model = "gsthoonitruck1" },
    { label = "HPF M8",                 model = "hpfm8" },
    { label = "Lightning Dually 22",     model = "lightningdually22" },
    { label = "Revuelto Beast",          model = "revueltobeast" },
    { label = "S550 Kev",               model = "s550kev" },
    { label = "Vanz WB06",              model = "vanzwb06" },
    { label = "Venu 911",               model = "venuum911" },
    { label = "V-Rod Widow Ape",         model = "vrodwidowape" },
}

VFW.Staff.Carlist["50 Pack"] = {
    { label = "765LT 1016SC",           model = "765LT1016sc" },
    { label = "C8 Widebody LC",          model = "C8WidebodyLC" },
    { label = "GLK",                     model = "GLK" },
    { label = "Lightning WB",           model = "GODz22LIGHTNINGWB" },
    { label = "61 Bus",                 model = "GODz61BUS" },
    { label = "67 GT500",               model = "GODz67ELGT500" },
    { label = "Mistral S",              model = "GODzMISTRALs" },
    { label = "RZR Pro Lifted",          model = "GODzRZRPROLFTD" },
    { label = "Veyron SS WB",           model = "GODzVEYRONSSWB" },
    { label = "Hellcat Magnum 21",       model = "HellcatMagnum21" },
    { label = "Hellstinger WB SC",       model = "HellstingerwbSC" },
    { label = "Hycade Hellcat Durango",  model = "HycadeHellcatDurango" },
    { label = "Shaker Anniversary SC",   model = "ShakerAnniversarySC" },
    { label = "Shaker Anniversary SC 2", model = "ShakerAnniversarySC2" },
    { label = "Shaker Anniversary SC 3", model = "ShakerAnniversarySC3" },
    { label = "A80 Saleem",             model = "a80vygasaleem" },
    { label = "AB 300",                  model = "ab300" },
    { label = "G07",                     model = "bmwg07" },
    { label = "Camaro Drag Machine",     model = "camarodragmachine" },
    { label = "Carsons WB C6",          model = "carsonswbc6" },
    { label = "Daytona SP3",            model = "daytonasp3" },
    { label = "Dually Bshack",           model = "duallybshack" },
    { label = "Escalade Prime",          model = "escaladeprime" },
    { label = "ESR MZO",                model = "esrmzo" },
    { label = "F8 K Spider",            model = "f8kspider" },
    { label = "FBV 60 Pole",            model = "fbv60pole" },
    { label = "Fenrir",                  model = "fenrir" },
    { label = "F Proto ZWB",            model = "fprotozwb" },
    { label = "F Tecnica",              model = "ftecnica" },
    { label = "G63 G800 BO",            model = "g63g800bo" },
    { label = "G Quad C8",              model = "gquadc8" },
    { label = "Firebird GST",           model = "gstbird1" },
    { label = "GT4 Hycade",             model = "gt4hycade" },
    { label = "GT3 RS 23",              model = "ikx3gt3rs23" },
    { label = "HN65",                   model = "ikx3hn65" },
    { label = "SF90 Custom",            model = "ikx3sf90custom" },
    { label = "Jaylock Bent",            model = "jaylockbent" },
    { label = "Keyvany Cullinan",        model = "keyvanycullinan" },
    { label = "Quad Turbo",             model = "laferrariquadturbo" },
    { label = "LBWK Evo",               model = "lbwkevo" },
    { label = "LPI 800-4",              model = "lpi80041" },
    { label = "Lumma X7 Unmarked",       model = "lumma21x7unmarked" },
    { label = "M4 G82",                 model = "m4g82" },
    { label = "M8 HC",                  model = "m8hc" },
    { label = "G63 Mansory",            model = "mansoryg63" },
    { label = "Owl Bel Air",            model = "owlbelair" },
    { label = "Owl Bel Air 2",          model = "owlbelair2" },
    { label = "Prior GT63S",            model = "priorgt63s" },
    { label = "R33 PTNC",               model = "r33ptnc" },
    { label = "R6D",                     model = "r6d" },
    { label = "RR21 Camaro Wide",        model = "rr21camarowide" },
    { label = "RS6 ABT Kit",            model = "rs6abtkit" },
    { label = "UGC 765LT",              model = "ugc765lt" },
    { label = "UGC Lucian Mistral",      model = "ugclucianmistral" },
    { label = "Vantage 23",             model = "vantage23" },
    { label = "Vanz KRC",               model = "vanzkrc" },
}

VFW.Staff.Carlist["Animated Pack"] = {
    { label = "Sierra 21",              model = "21sierra" },
    { label = "Centodieci 2020",        model = "gutti" },
    { label = "Durango SRT",            model = "urango" },
    { label = "E3000",                  model = "E3000" },
    { label = "GTR Tuning",             model = "trslib" },
    { label = "Hommage",               model = "hommage" },
    { label = "Huracan",               model = "hurper" },
    { label = "NN32",                   model = "NN32" },
    { label = "NN 350Z",               model = "NN350z" },
    { label = "T8",                     model = "T8" },
    { label = "A90 E",                 model = "a90e" },
    { label = "ABD Hawk",              model = "abdhawk" },
    { label = "Bullinan",              model = "bullinan" },
    { label = "Bustang",               model = "bustang" },
    { label = "Drevette",              model = "drevette" },
    { label = "D-Tron 22",            model = "dtron22" },
    { label = "Dupra",                 model = "dupra" },
    { label = "Faguar",                model = "faguar" },
    { label = "Foxcoma 2",            model = "foxcoma2" },
    { label = "Itasha BRZ",            model = "ichatsunebrz" },
    { label = "MP4",                    model = "mp4" },
    { label = "NV S74",               model = "nvis74" },
    { label = "Proto Z",               model = "protoz" },
    { label = "Q7",                     model = "q7" },
    { label = "Artura 22",             model = "rtura22" },
    { label = "Rurus",                  model = "rurus" },
    { label = "TR99",                   model = "tr99" },
    { label = "Wald Phantom",          model = "waldphantom" },
    { label = "X6 WZ",                 model = "x6wz" },
}

VFW.Staff.Carlist["Bike Pack"] = {
    { label = "S1000RR 2K23",           model = "ESM1000RR2K23" },
    { label = "Street Glide Bagger",     model = "GODz13HDSGBAGGER" },
    { label = "Street Glide V2",         model = "GODz13HDSGBAGGERv2" },
    { label = "Daytona 675R",            model = "GODzDAYTONA675R" },
    { label = "Dirty Tail 2",           model = "GODzDIRTYTAIL2" },
    { label = "T12 Massimo",            model = "GODzT12" },
    { label = "R1",                      model = "GODzYAMR1" },
    { label = "KTMM",                   model = "KTMM" },
    { label = "CBR1000RR-R",             model = "cbr1000rrr" },
    { label = "Dark Fate",              model = "darkfate" },
    { label = "1299 Superleggera",       model = "ducati1299" },
    { label = "GSX-R S",                model = "es-gsxrs" },
    { label = "GSX-R Stealth",          model = "esgsxrst3alth" },
    { label = "S1000RRR",               model = "esm1000rrr" },
    { label = "F4 RR",                  model = "f4rr" },
    { label = "Super Duke",             model = "ksd" },
    { label = "M1000RR V2",             model = "m1000rrv2" },
    { label = "Pike",                    model = "pike" },
    { label = "RK 2019L",               model = "rk2019l" },
    { label = "RSV4",                    model = "rsv4" },
    { label = "SA90",                    model = "sa90" },
}

VFW.Staff.Carlist["Donk Cars"] = {
    { label = "19 Ram Donk",            model = "19ramdonk" },
    { label = "21 Charger Scat",         model = "21Charscat" },
    { label = "530 XD",                 model = "530xd" },
    { label = "A6",                     model = "a6" },
    { label = "Big Boy Elco",            model = "bigboyelco" },
    { label = "Boon Box",               model = "boonbox" },
    { label = "Brainshack 11",           model = "brainshack11" },
    { label = "Brainshack 12",           model = "brainshack12" },
    { label = "Brainshack 500",          model = "brainshack500" },
    { label = "Bshack 72 Big",          model = "bshack72big" },
    { label = "Bshack 72 Race",          model = "bshack72race" },
    { label = "Demon Hawk",             model = "demonhawkk" },
    { label = "Denali 18 Lift",          model = "denali18lift" },
    { label = "Durango",                 model = "durango" },
    { label = "Elva",                    model = "elva" },
    { label = "Escalade 21",            model = "escalade21" },
    { label = "RO 650",                 model = "ro650" },
    { label = "RO May",                 model = "romay" },
    { label = "RO MT",                  model = "romt" },
    { label = "RO Viper",               model = "rovip" },
    { label = "RO X6",                  model = "rox6" },
    { label = "Shark Cam",              model = "sharkcam" },
    { label = "Shark Durango",           model = "sharkdurango" },
    { label = "SRT Daytona 20",          model = "srtday20" },
    { label = "Stardust",               model = "stardust" },
    { label = "Tahoe LTZ",              model = "tahoeLTZ" },
    { label = "Twin 69",                model = "twin69" },
    { label = "UNK 75",                 model = "unk75" },
    { label = "Vanz Camaro",            model = "vanzcamaro" },
    { label = "Vanz Impala",            model = "vanzimpala" },
    { label = "Vanz M3",                model = "vanzm3" },
    { label = "Vanz Redeye",            model = "vanzredeye" },
    { label = "Vanz Rolls",             model = "vanzrolls" },
    { label = "Vanz Urus",              model = "vanzurus" },
    { label = "Z71 High",               model = "z71high" },
}

VFW.Staff.Carlist["Restaurants"] = {
    { label = "Bean Coffee Van",         model = "hvbean" },
    { label = "Bean Coffee Van 2",       model = "hvbean1" },
    { label = "Burger Shot Van",         model = "hvburger" },
    { label = "Burger Shot Van 2",       model = "hvburger1" },
    { label = "Pizza This Van",          model = "hvpizza" },
    { label = "Pizza This Van 2",        model = "hvpizza1" },
    { label = "UwU Cafe Van",            model = "hvuwu" },
    { label = "UwU Cafe Van 2",          model = "hvuwu1" },
}

VFW.Staff.Carlist["Weazel News"] = {
    { label = "Weazel News Maverick",    model = "newsheli" },
    { label = "Weazel News SuperVolito", model = "newsheli2" },
    { label = "Weazel News Van",         model = "newsvan" },
}

-- ============================================================
-- VEHICULES GABZ (custom packs)
-- ============================================================

VFW.Staff.Carlist["Gabz - A a M"] = {
    { label = "811 S2",                   model = "gb811s2" },
    { label = "Admiral",                  model = "gbadmiral" },
    { label = "Archer Pro II",            model = "gbarcherpro2" },
    { label = "Argento 2F",               model = "gbargento2f" },
    { label = "Argento 7F",               model = "gbargento7f" },
    { label = "Argento 7F Sportback",     model = "gbargento7fs" },
    { label = "Taxi Argento 7F",          model = "gbtaxiargento7f" },
    { label = "Banshee S",                model = "gbbanshees" },
    { label = "Bison HF",                 model = "gbbisonhf" },
    { label = "Bison STX",                model = "gbbisonstx" },
    { label = "Boxboy",                   model = "gbboxboy" },
    { label = "Boxboy Food Truck",        model = "gbboxboyft" },
    { label = "Brioso Fulmine",           model = "gbbriosof" },
    { label = "Grotti Cheetah S",         model = "gbcheetahs" },
    { label = "Club XR",                  model = "gbclubxr" },
    { label = "Comet Classic",            model = "gbcometcl" },
    { label = "Comet Classic Florio",     model = "gbcometclf" },
    { label = "Comet S1 Turbo",           model = "gbcomets1t" },
    { label = "Comet S1 Turbo Florio",    model = "gbcomets1tf" },
    { label = "Comet S2R",                model = "gbcomets2r" },
    { label = "Comet S2RC",               model = "gbcomets2rc" },
    { label = "Cypher GTS",               model = "gbcyphergts" },
    { label = "Deliver-E",                model = "gbdelivere" },
    { label = "Dominator GSX",            model = "gbdominatorgsx" },
    { label = "Echelon",                  model = "gbechelon" },
    { label = "Echelon Sportback",        model = "gbechelons" },
    { label = "Elegy RH2",                model = "gbelegyrh2" },
    { label = "Emerus SB1",               model = "gbemerussb1" },
    { label = "Eon",                      model = "gbeon" },
    { label = "Taxi Eon",                 model = "gbtaxieon" },
    { label = "E-Rotiq",                  model = "gberotiq" },
    { label = "Gresley STX",              model = "gbgresleystx" },
    { label = "Rumpo Esperta",            model = "gbesperta" },
    { label = "e-Surfer",                 model = "gbesurfer" },
    { label = "Hades",                    model = "gbhades" },
    { label = "Harmann",                  model = "gbharmann" },
    { label = "Hedra",                    model = "gbhedra" },
    { label = "Hedra Kombi",              model = "gbhedrakombi" },
    { label = "Hurricane",                model = "gbhurricane" },
    { label = "Impaler LE",               model = "gbimpaler" },
    { label = "Impaler Deluxe",           model = "gbimpalerdlx" },
    { label = "Iris Z",                   model = "gbirisz" },
    { label = "Issi Metro",               model = "gbissimetro" },
    { label = "Komoda GT",                model = "gbkomodagt" },
    { label = "LOD-4",                    model = "gblod4" },
    { label = "Milano GTS",               model = "gbmilano" },
    { label = "Mochi",                    model = "gbmochi" },
    { label = "Mogul RS",                 model = "gbmogulrs" },
    { label = "Mojave",                   model = "gbmojave" },
    { label = "Turismo Mugello",          model = "gbmugello" },
}

VFW.Staff.Carlist["Gabz - N a Z"] = {
    { label = "Neon Cross Turismo",       model = "gbneonct" },
    { label = "Nexus RR",                 model = "gbnexusrr" },
    { label = "Prospero",                 model = "gbprospero" },
    { label = "Raidillon",                model = "gbraidillon" },
    { label = "Retinue Lozspeed",         model = "gbretinueloz" },
    { label = "Romulus",                  model = "gbromulus" },
    { label = "Ronin",                    model = "gbronin" },
    { label = "Rumina",                   model = "gbrumina" },
    { label = "Sapphire",                 model = "gbsapphire" },
    { label = "Schlagen Roadster",        model = "gbschlagenr" },
    { label = "Schlagen SP",              model = "gbschlagensp" },
    { label = "Schrauber",                model = "gbschrauber" },
    { label = "Schwartzer S",             model = "gbschwartzers" },
    { label = "Scout GSX",                model = "gbscoutgsx" },
    { label = "Sentinel GTS-R",           model = "gbsentinelgts" },
    { label = "Sidewinder",               model = "gbsidewinder" },
    { label = "Solace",                   model = "gbsolace" },
    { label = "Solace Vitesse",           model = "gbsolacev" },
    { label = "Stanier LE",               model = "gbstanierle" },
    { label = "Taxi Stanier LE",          model = "gbtaxistanierle" },
    { label = "Starlight",                model = "gbstarlight" },
    { label = "Taxi Starlight",           model = "gbtaxistarlight" },
    { label = "Steed",                    model = "gbsteedvan" },
    { label = "Sultan RSx",               model = "gbsultanrsx" },
    { label = "Tahoma GT",                model = "gbtahomagt" },
    { label = "Tempesta Fuoristrada",     model = "gbtempestafs" },
    { label = "10F Spyder",               model = "gbtenfr" },
    { label = "Terrorizer",               model = "gbterrorizer" },
    { label = "TR3-S",                    model = "gbtr3s" },
    { label = "Turismo 300GT",            model = "gbturismogt" },
    { label = "Turismo 300GT Spider",     model = "gbturismogts" },
    { label = "Vigero Rattler",           model = "gbvigerorat" },
    { label = "Vivant",                   model = "gbvivant" },
    { label = "Vivant GrB",               model = "gbvivantgrb" },
    { label = "Voyager 6x4-T",            model = "gbvoyager" },
    { label = "Zeitgeist",                model = "gbzeitgeist" },
}

VFW.Staff.Carlist["Gabz - PD/EMS"] = {
    { label = "Admiral Police",           model = "gbpoladmiral" },
    { label = "Argento 7F Police",        model = "gbpolargento7f" },
    { label = "Banshee S Police",         model = "gbpolbanshees" },
    { label = "Bison HF Police",          model = "gbpolbisonhf" },
    { label = "Bison STX Ambulance",      model = "gbemsbisonstx" },
    { label = "Bison STX Police",         model = "gbpolbisonstx" },
    { label = "Club XR Police",           model = "gbpolclubxr" },
    { label = "Comet Classic Police",     model = "gbpolcometcl" },
    { label = "Comet S2R Police",         model = "gbpolcomets2r" },
    { label = "Dominator GSX Police",     model = "gbpoldomgsx" },
    { label = "Echelon Police",           model = "gbpolechelon" },
    { label = "Eon Police",               model = "gbpoleon" },
    { label = "Rumpo Esperta EMS",        model = "gbemsesperta" },
    { label = "Rumpo Esperta Police",     model = "gbpolesperta" },
    { label = "Gresley Police",           model = "gbpolgresley" },
    { label = "Hedra Kombi Police",       model = "gbpolhedra" },
    { label = "Impaler Police",           model = "gbpolimpaler" },
    { label = "Mojave Police",            model = "gbpolmojave" },
    { label = "Prospero Police",          model = "gbpolprospero" },
    { label = "Scout GSX Police",         model = "gbpolscoutgsx" },
    { label = "Sentinel GTS-R Police",    model = "gbpolsentinelgts" },
    { label = "Solace Police",            model = "gbpolsolace" },
    { label = "Stanier LE Police",        model = "gbpolstanier" },
    { label = "Starlight Police",         model = "gbpolstarlight" },
    { label = "Steed EMS",                model = "gbemssteed" },
    { label = "Steed Police",             model = "gbpolsteedvan" },
    { label = "Sultan RSx Police",        model = "gbpolsultanrsx" },
    { label = "Tahoma GT Police",         model = "gbpoltahomagt" },
    { label = "Terrorizer Police",        model = "gbpolterrorizer" },
    { label = "Turismo 300GT Police",     model = "gbpolturismogt" },
    { label = "TR3-S Police",             model = "gbpoltr3s" },
    { label = "Voyager Fire Truck",       model = "gbfirevoyager" },
}
