---@meta _
---@diagnostic disable: duplicate-doc-field

VFW.Cardealer = {}
VFW.Benefactor = {}
VFW.AmericanMotors = {}

VFW.Benefactor.Vehicle = {
    { label = "Krieger",                      model = "krieger",       price = 172500 },
    { label = "Schnell",                      model = "schnell",       price = 117300 },
    { label = "stirling GT",                  model = "feltzer3",      price = 61750 },
    { lalbel = "Imperial",                    model = "imperial",      price = 27025 },
    { label = "Imperial Passenger",           model = "imperialpas",   price = 32143 },
    { label = "Imperial EV",                  model = "imperialev",    price = 25875 },
    { label = "Schafter V12",                 model = "schafter3",     price = 60950 },
    { label = "Schafter LWB",                 model = "schafter4",     price = 48300 },
    { label = "Schlagen GT",                  model = "schlagen",      price = 146730 },
    { label = "Schlagen STR",                 model = "schlagenstr",   price = 228975 },
    { label = "Schwarzer",                    model = "schwarzer",     price = 42021 },
    { label = "Spritzer",                     model = "spritzer",      price = 67725 },
    { label = "Streiter Sline",               model = "streiter2",     price = 52440 },
    { label = "Feltzer",                      model = "feltzer2",      price = 43700 },
    { label = "Surano",                       model = "surano",        price = 48875 },
    { label = "Surano Coupe",                 model = "surano3",       price = 56000 },
    { label = "Surano E-motion",              model = "suranoe",       price = 89450 },
    { label = "Scheisser",                    model = "scheisser",     price = 17250 },
    { label = "Schafter",                     model = "schafter2",     price = 32189 },
    { label = "Scharmann",                    model = "scharmann",     price = 65989 },
    { label = "Schrauber",                    model = "gbschrauber",   price = 79440 },
    { label = "Glendale",                     model = "glendale",      price = 11673 },
    { label = "Glendale Custom",              model = "glendale2",     price = 23000 },
    { label = "Glendale Limo",                model = "glendalelimo",  price = 25150 },
    { label = "Schwartzer S",                 model = "gbschwartzers", price = 70600 },
    { label = "Benefactor Harmann",           model = "gbharmann",     price = 86540 },
    { label = "Benefactor Schlagen SP",       model = "gbschlagensp",  price = 97750 },
    { label = "Benefactor Schlagen Roadster", model = "gbschlagenr",   price = 100050 },
    { label = "Dubsta 6x6",                   model = "dubsta3",       price = 123750 },
    { label = "Dubsta",                       model = "dubsta",        price = 36800 },
    { label = "Dubsta Luxury",                model = "dubsta2",       price = 41975 },
    { label = "dubsta 2022",                  model = "dubsta22",      price = 109250 },
    { label = "XLS",                          model = "xls",           price = 34385 },
    { label = "Panto",                        model = "panto",         price = 4428 },
}

VFW.Cardealer.Vehicle = {
    ["Super"] = {
        { label = "Adder",             model = "adder",      price = 212750 },
        { label = "Autarch",           model = "autarch",    price = 171350 },
        { label = "Audace",            model = "audace",     price = 203550 },
        { label = "Aurora Sport",      model = "auroras",    price = 205275 },
        { label = "Auroras Sport RHD", model = "auroras2",   price = 210450 },
        { label = "Celeste",           model = "celeste",    price = 170200 },
        { label = "Champion",          model = "champion",   price = 115000 },
        { label = "Cheetah",           model = "cheetah",    price = 126500 },
        { label = "Emerus",            model = "emerus",     price = 129375 },
        { label = "Entity XXR",        model = "entity2",    price = 217350 },
        { label = "Entity MT",         model = "entity3",    price = 224250 },
        { label = "Entity XF",         model = "entityxf",   price = 195500 },
        { label = "Furia",             model = "furia",      price = 227700 },
        { label = "GP1",               model = "gp1",        price = 232300 },
        { label = "Hurricane",         model = "hurricane",  price = 235750 },
        { label = "Ignus",             model = "ignus",      price = 224250 },
        { label = "Infernus",          model = "infernus",   price = 126500 },
        { label = "Itali GTB",         model = "italigtb",   price = 132250 },
        { label = "Itali GTB Custom",  model = "italigtb2",  price = 143750 },
        { label = "Nero",              model = "nero",       price = 258750 },
        { label = "Nero Custom",       model = "nero2",      price = 270250 },
        { label = "Nero Super Sport",  model = "nerops",     price = 281750 },
        { label = "Osiris",            model = "osiris",     price = 161000 },
        { label = "Osiris R",          model = "osirisr",    price = 166750 },
        { label = "Osiris FR-Works",   model = "osirisfr",   price = 172500 },
        { label = "Pallas",            model = "pallas",     price = 128800 },
        { label = "Penetrator",        model = "penetrator", price = 158700 },
        { label = "811",               model = "pfister811", price = 172500 },
        { label = "X80 Proto",         model = "prototipo",  price = 230000 },
        { label = "R9 GT",             model = "r9gt",       price = 172500 },
        { label = "Reaper",            model = "reaper",     price = 166750 },
        { label = "Reaper Custom",     model = "reagpr",     price = 170200 },
        { label = "SC1",               model = "sc1",        price = 121900 },
        { label = "Severo",            model = "severo",     price = 143750 },
        { label = "ETR1",              model = "sheava",     price = 123050 },
        { label = "Sultan RS",         model = "sultanrs",   price = 69000 },
        { label = "T20",               model = "t20",        price = 154100 },
        { label = "Tigon",             model = "tigon",      price = 148350 },
        { label = "Tempesta",          model = "tempesta",   price = 172500 },
        { label = "Tempesta FR Works", model = "tempestafr", price = 174800 },
        { label = "Tezeract",          model = "tezeract",   price = 189750 },
        { label = "Thrax",             model = "thrax",      price = 287500 },
        { label = "Torero XO",         model = "Torero",     price = 216200 },
        { label = "Turismo R",         model = "turismor",   price = 128800 },
        { label = "Turismo RR",        model = "turismorr",  price = 132250 },
        { label = "Turismo Omaggio",   model = "turismo3",   price = 161000 },
        { label = "Tyrant",            model = "tyrant",     price = 156400 },
        { label = "Tyrus",             model = "tyrus",      price = 146050 },
        { label = "Vacca",             model = "vacca",      price = 136850 },
        { label = "Vagner",            model = "vagner",     price = 201250 },
        { label = "Virtue",            model = "virtue",     price = 185150 },
        { label = "Visione",           model = "visione",    price = 169050 },
        { label = "Voltic",            model = "voltic",     price = 69000 },
        { label = "XA-21",             model = "xa21",       price = 156400 },
        { label = "Banshee 900R",      model = "banshee2",   price = 63250 },
        { label = "Bullet",            model = "bullet",     price = 51750 },
        { label = "Bullet GT",         model = "bulletgt",   price = 55200 },
        { label = "Cyclone",           model = "cyclone",    price = 92000 },
        { label = "Cyclone E-O",       model = "cycloneex0", price = 112000 },
        { label = "FMJ",               model = "fmj",        price = 189750 },
        { label = "Taipan",            model = "taipan",     price = 178250 },
        { label = "Zeno",              model = "zeno",       price = 186875 },
        { label = "Zentorno",          model = "zentorno",   price = 171350 },
        { label = "Zorrusso",          model = "zorrusso",   price = 150650 },
        { label = "Pfister 811 S2",    model = "gb811s2",    price = 125000 },
        { label = "TR3-S",             model = "gbtr3s",     price = 281750 },
        { label = "Prospero",          model = "gbprospero", price = 253000 },
    },
    ["Sport-Classic"] = {
        { label = "Roosevelt",            model = "btype",        price = 32775 },
        { label = "Franken Stange",       model = "btype2",       price = 28750 },
        { label = "Roosevelt Valor",      model = "btype3",       price = 34500 },
        { label = "Casco",                model = "casco",        price = 28750 },
        { label = "Cheetah Classique",    model = "cheetah",      price = 396750 },
        { label = "Cheetah Veloce",       model = "cheetah2",     price = 402500 },
        { label = "GT 500",               model = "gt500",        price = 113850 },
        { label = "Infernus Classique",   model = "infernus",     price = 113850 },
        { label = "JB 700W",              model = "jb700",        price = 109250 },
        { label = "Krieger BPX-32B",      model = "kriegerc",     price = 121750 },
        { label = "Loretta",              model = "loretta",      price = 67505 },
        { label = "Mark 1",               model = "mark1",        price = 11500 },
        { label = "Michelli GT",          model = "michelli",     price = 30475 },
        { label = "Monroe",               model = "monroe",       price = 35650 },
        { label = "Monroe SOTW Edition",  model = "m420",         price = 21850 },
        { label = "Nebula Turbo",         model = "nebula",       price = 9200 },
        { label = "NebulaW",              model = "nebulaw",      price = 14030 },
        { label = "Pigalle",              model = "pigalle",      price = 8683 },
        { label = "Rapid GT Classique",   model = "rapidgt3",     price = 39675 },
        { label = "Rapid GT Sport",       model = "rapidgt4",     price = 47725 },
        { label = "Sancy B4",             model = "sancyb4",      price = 54625 },
        { label = "Savestra",             model = "savestra",     price = 25878 },
        { label = "Shamus",               model = "shamus",       price = 11270 },
        { label = "Stardust",             model = "stardust",     price = 32200 },
        { label = "Stinger",              model = "stinger",      price = 44275 },
        { label = "Stinger GT",           model = "stingergt",    price = 55775 },
        { label = "Swinger",              model = "swinger",      price = 66700 },
        { label = "Swindler",             model = "swindler",     price = 14088 },
        { label = "Torero",               model = "torero",       price = 78200 },
        { label = "Turismo Classique",    model = "turismocs",    price = 120750 },
        { label = "Type 1",               model = "type1",        price = 67045 },
        { label = "Viseris",              model = "viseris",      price = 32775 },
        { label = "190Z",                 model = "z190",         price = 47725 },
        { label = "Zion Classique",       model = "",             price = 38985 },
        { label = "Zionks",               model = "zionks",       price = 40710 },
        { label = "Z-Type",               model = "ztype",        price = 172500 },
        { label = "Turismo 300GT Spider", model = "gbturismogts", price = 132940 },
        { label = "Comet S1 Turbo",       model = "gbcomets1t",   price = 91885 },
    },
    ["Compact"] = {
        { label = "Arias",                  model = "arias",       price = 5750 },
        { label = "Asbo",                   model = "asbo",        price = 4945 },
        { label = "Blista",                 model = "blista",      price = 4658 },
        { label = "Blista CR",              model = "blistacr",    price = 8913 },
        { label = "Blista R/A",             model = "brioso",      price = 6325 },
        { label = "Brioso 300",             model = "brioso2",     price = 7763 },
        { label = "Brioso 300 Large",       model = "brioso3",     price = 11213 },
        { label = "Citi",                   model = "citi",        price = 8625 },
        { label = "Dilettante",             model = "dilettante",  price = 3853 },
        { label = "Garden Shed",            model = "gardenshed",  price = 5750 },
        { label = "Garden Shed Camionette", model = "gardenshed2", price = 14950 },
        { label = "Panetiere",              model = "gardenshed3", price = 9028 },
        { label = "Huesca",                 model = "huesca",      price = 5750 },
        { label = "Blista Kanjo",           model = "kanjo",       price = 10925 },
        { label = "Kanjo SJ",               model = "kanjosj",     price = 15180 },
        { label = "Issi",                   model = "issi2",       price = 6417 },
        { label = "Issi Classique",         model = "issi3",       price = 9775 },
        { label = "Grotti Pincel",          model = "pincel",      price = 14950 },
        { label = "Postlude",               model = "postlude",    price = 11500 },
        { label = "Prairie",                model = "prairie",     price = 4600 },
        { label = "Weevil",                 model = "weevil",      price = 5244 },
        { label = "Zodiac",                 model = "zodiac",      price = 10925 },
        { label = "Vivant",                 model = "gbvivant",    price = 27926 },
    },
    ["SUV"] = {
        { label = "Astron",           model = "astron",      price = 143750 },
        { label = "Baller Gen 1",     model = "baller",      price = 26450 },
        { label = "Baller Gen 2",     model = "baller2",     price = 28175 },
        { label = "Baller LE",        model = "baller3",     price = 41975 },
        { label = "Baller LE LWB",    model = "baller4",     price = 45989 },
        { label = "Baller ST",        model = "baller7",     price = 51750 },
        { label = "Baller ST-D",      model = "baller8",     price = 86250 },
        { label = "Beretta",          model = "beretta",     price = 62100 },
        { label = "Bee Jay XL",       model = "bjxl",        price = 24725 },
        { label = "FQ2",              model = "fq2",         price = 15525 },
        { label = "Habanero",         model = "habanero",    price = 14490 },
        { label = "Huntley S",        model = "huntley",     price = 14375 },
        { label = "I-Wagen",          model = "iwagen",      price = 44563 },
        { label = "Issi Rallye S",    model = "issi8",       price = 31625 },
        { label = "Issi Rallye",      model = "issi8s",      price = 26450 },
        { label = "Jubilee",          model = "jubilee",     price = 91885 },
        { label = "Novak",            model = "Novak",       price = 86250 },
        { label = "Radius",           model = "radi",        price = 11270 },
        { label = "Rebla GTS",        model = "rebla",       price = 113850 },
        { label = "Rocoto",           model = "rocoto",      price = 28750 },
        { label = "Serrano",          model = "serrano",     price = 15008 },
        { label = "Toros",            model = "toros",       price = 40250 },
        { label = "Vivanite",         model = "vivanite",    price = 28175 },
        { label = "Vulcar Starlight", model = "gbstarlight", price = 60250 },
        { label = "LOD 4",            model = "gblod4",      price = 96250 },
    },
    ["Coupe"] = {
        { label = "Cognoscenti Cabrio", model = "cogcabrio", price = 29325 },
        { label = "Exemplar",           model = "exemplar",     price = 57500 },
        { label = "F620",               model = "f620",         price = 44275 },
        { label = "Felon",              model = "felon",        price = 46000 },
        { label = "Felon GT",           model = "felon2",       price = 51750 },
        { label = "FR-36",              model = "fr36",         price = 53475 },
        { label = "Jackal",             model = "Jackal",       price = 41975 },
        { label = "Lancea",             model = "lancea",       price = 43125 },
        { label = "Piaglle Milord",     model = "milord",       price = 15525 },
        { label = "Oracle XS",          model = "oracle",       price = 32660 },
        { label = "Oracle",             model = "oracle2",      price = 29325 },
        { label = "Oracle XS-LE",       model = "oracxsle",     price = 31970 },
        { label = "Sentinel XS",        model = "sentinel",     price = 24725 },
        { label = "Sentinel Sport",     model = "sentinel2",    price = 25875 },
        { label = "Sentinel P",         model = "sentinelp",    price = 32775 },
        { label = "Sentinel P1",        model = "sentinelp1",   price = 33925 },
        { label = "Windsor",            model = "windsor",      price = 43125 },
        { label = "Windsor Drop",       model = "windsor2",     price = 30475 },
        { label = "Zion",               model = "zion",         price = 22989 },
        { label = "Zion Cabrio",        model = "zion2",        price = 24725 },
        { label = "Odessa",             model = "odessa",       price = 12075 },
        { label = "Pique",              model = "pique",        price = 9200 },
        { label = "Zinger",             model = "zinger",       price = 13800 },
    },
    ["Sedans"] = {
        { label = "Altior",                  model = "altior",        price = 28750 },
        { label = "Asea",                    model = "asea",          price = 6325 },
        { label = "Asterope",                model = "asterope",      price = 8050 },
        { label = "Asterope S",              model = "asterope2",     price = 46000 },
        { label = "Cinquemila",              model = "cinquemila",    price = 155250 },
        { label = "Cognoscenti 55",          model = "cog55",         price = 36225 },
        { label = "Cognoscenti",             model = "cognoscenti",   price = 44275 },
        { label = "Deity",                   model = "deity",         price = 84375 },
        { label = "Karin Dilettante DX",     model = "dilettantedx",  price = 23000 },
        { label = "Elegant",                 model = "elegant",       price = 10638 },
        { label = "Ferocid",                 model = "ferocid",       price = 14375 },
        { label = "Ingot",                   model = "ingot",         price = 7475 },
        { label = "Intruder",                model = "intruder",      price = 9660 },
        { label = "Premier",                 model = "premier",       price = 8625 },
        { label = "Primo",                   model = "primo",         price = 14663 },
        { label = "Primo Custom",            model = "primo2",        price = 24725 },
        { label = "Primo ARD",               model = "primoard",      price = 20125 },
        { label = "Rhinehart",               model = "rhinehart",     price = 86250 },
        { label = "Sentinel SG3",            model = "sentinelsg3",   price = 27025 },
        { label = "Sentinel SG32 A",         model = "sentinelsg32",  price = 26163 },
        { label = "Sentinel SG3 A",          model = "sentinelsg3a",  price = 24725 },
        { label = "Sentinel SG3 B (Cabrio)", model = "sentinelsg3b",  price = 27025 },
        { label = "Sentinel SG3 C (Break)",  model = "sentinelsg3c",  price = 25875 },
        { label = "Sentinel SG3 D (Drift)",  model = "sentinelsg3d",  price = 61975 },
        { label = "Declasse Impaler",        model = "gbimpaler",     price = 21480 },
        { label = "Seraph",                  model = "seraph",        price = 13800 },
        { label = "Seraph 3",                model = "seraph3",       price = 25875 },
        { label = "Seraph V10",              model = "seraph10",      price = 28750 },
        { label = "Stafford",                model = "stafford",      price = 23000 },
        { label = "Stanier",                 model = "stanier",       price = 8338 },
        { label = "Stratum",                 model = "stratum",       price = 4974 },
        { label = "Stretch",                 model = "stretch",       price = 48875 },
        { label = "Super Diamond",           model = "superd",        price = 37375 },
        { label = "Bollokan Iris Z",         model = "gbirisz",       price = 27840 },
        { label = "Super Diamond Limousine", model = "superd3",       price = 287500 },
        { label = "Surge",                   model = "surge",         price = 10638 },
        { label = "Tailgater",               model = "tailgater",     price = 29325 },
        { label = "Tailgater S",             model = "tailgater2",    price = 98250 },
        { label = "Washington",              model = "washington",    price = 5290 },
        { label = "Stanier LE",              model = "gbstanierle",   price = 23000 },
        { label = "Dundreary Admiral",       model = "gbadmiral",     price = 21500 },
        { label = "Dundreary Hades",         model = "gbhades",       price = 28600 },
        { label = "Sentinel GTS",            model = "gbsentinelgts", price = 105250 },
    },
    ["Sport"] = {
        { label = "Argento",                  model = "argento",       price = 86250 },
        { label = "Argento 2",                model = "argento2",      price = 97750 },
        { label = "Ariant",                   model = "ariant",        price = 41975 },
        { label = "Asterope RS",              model = "ariant",        price = 74750 },
        { label = "Bestia GTS",               model = "bestiagts",     price = 61525 },
        { label = "Boor Widebody",            model = "boorc",         price = 24150 },
        { label = "Carbonizzare",             model = "carbonizzare",  price = 55775 },
        { label = "Calico GTF",               model = "calico",        price = 71750 },
        { label = "Cypher",                   model = "cypher",        price = 50250 },
        { label = "Cypher CT",                model = "cypherct",      price = 55475 },
        { label = "Comet",                    model = "comet2",        price = 69000 },
        { label = "Comet Retro Custom",       model = "comet3",        price = 80788 },
        { label = "Comet Retro Standard",     model = "comet3s",       price = 81075 },
        { label = "Comet SR",                 model = "comet5",        price = 94875 },
        { label = "Comet S2",                 model = "comet6",        price = 100625 },
        { label = "Comet S2 Cabrio",          model = "comet7",        price = 103500 },
        { label = "Corsita",                  model = "corsita",       price = 176870 },
        { label = "La Coureuse",              model = "coureur",       price = 36800 },
        { label = "8F Drafter",               model = "drafter",       price = 74750 },
        { label = "DD Blitz",                 model = "doubled",       price = 40250 },
        { label = "Elegy Retro Custom",       model = "elegy",         price = 71500 },
        { label = "Elegy RZ Custom",          model = "elegy4",        price = 59800 },
        { label = "Elegy RH7",                model = "elegyrh7",      price = 60950 },
        { label = "Elegy RH72",               model = "elegyrh72",     price = 55200 },
        { label = "Elegy RH8 FR Works",       model = "rh82",          price = 51750 },
        { label = "Elegy UTE",                model = "elegyute",      price = 46000 },
        { label = "Euros",                    model = "euros",         price = 37375 },
        { label = "Elegy RH8",                model = "elegy2",        price = 50600 },
        { label = "Estancia",                 model = "estancia",      price = 120980 },
        { label = "Furore GT",                model = "furoregt",      price = 47725 },
        { label = "Futo",                     model = "futo",          price = 13570 },
        { label = "Futo GTX",                 model = "futo2",         price = 22400 },
        { label = "Growler",                  model = "growler",       price = 86250 },
        { label = "Hachura",                  model = "hachura",       price = 40940 },
        { label = "Hachura Custom",           model = "hachurac",      price = 69575 },
        { label = "Imorgon",                  model = "imorgon",       price = 76000 },
        { label = "Issi Sport",               model = "issi7",         price = 86250 },
        { label = "Itali GTO",                model = "italigto",      price = 258750 },
        { label = "Grotti Milano",            model = "gbmilano",      price = 268750 },
        { label = "Itali GTS",                model = "italigts",      price = 276000 },
        { label = "Itali GTR",                model = "italigtr",      price = 327750 },
        { label = "Itali RSX",                model = "italirsx",      price = 287500 },
        { label = "Oracle V12 SLine",         model = "jd_oraclev12a", price = 43125 },
        { label = "Oracle V12 Break",         model = "jd_oraclev12w", price = 40940 },
        { label = "Oracle V12",               model = "jd_oraclev12",  price = 40250 },
        { label = "Jester",                   model = "jester",        price = 51750 },
        { label = "Jester (Course)",          model = "jester2",       price = 52900 },
        { label = "Dinka Nexus RR",           model = "gbnexusrr",     price = 56870 },
        { label = "Jester Classique",         model = "jester3",       price = 37375 },
        { label = "Jester RR",                model = "jester4",       price = 50025 },
        { label = "Jester RE-RR",             model = "jestgpr",       price = 51750 },
        { label = "Jugular",                  model = "jugular",       price = 55430 },
        { label = "Kawaii",                   model = "kawaii",        price = 27589 },
        { label = "Khamelion",                model = "khamelion",     price = 40940 },
        { label = "Komoda",                   model = "komoda",        price = 51750 },
        { label = "Komoda FR-Works",          model = "komodafr",      price = 58075 },
        { label = "Kuruma",                   model = "kuruma",        price = 25300 },
        { label = "Locust",                   model = "locust",        price = 51750 },
        { label = "Lynx",                     model = "lynx",          price = 43470 },
        { label = "Lynx Custom",              model = "lynxgpr",       price = 47150 },
        { label = "Massacro",                 model = "massacro",      price = 63250 },
        { label = "Massacro (Course)",        model = "massacro2",     price = 64400 },
        { label = "Massacro Volante",         model = "dbvolante",     price = 65780 },
        { label = "Neo",                      model = "neo",           price = 86250 },
        { label = "Neon",                     model = "neon",          price = 66700 },
        { label = "Nexus",                    model = "nexus",         price = 32775 },
        { label = "9F",                       model = "ninef",         price = 32200 },
        { label = "9F Cabrio",                model = "ninef2",        price = 33925 },
        { label = "Omnis E-GT",               model = "omnisegt",      price = 63250 },
        { label = "Omnis",                    model = "omnis",         price = 41400 },
        { label = "Panthere",                 model = "panthere",      price = 51750 },
        { label = "Paradrop",                 model = "paradrop",      price = 79580 },
        { label = "Paragon R",                model = "paragon",       price = 78200 },
        { label = "Paragon FR-Works",         model = "paragonxr",     price = 82800 },
        { label = "Pariah",                   model = "pariah",        price = 143750 },
        { label = "Pentro",                   model = "pentro",        price = 28750 },
        { label = "Pentro 3",                 model = "pentro3",       price = 30475 },
        { label = "Pentro GPR",               model = "pentrogpr",     price = 31050 },
        { label = "Pentro GPR2",              model = "pentrogpr2",    price = 32890 },
        { label = "Penumbra",                 model = "penumbra",      price = 21839 },
        { label = "Penumbra FF",              model = "penumbra2",     price = 39790 },
        { label = "Previon",                  model = "previon",       price = 34558 },
        { label = "300R",                     model = "r300",          price = 34500 },
        { label = "Rapid GT",                 model = "rapidgt",       price = 34500 },
        { label = "Rapid GT Cabrio",          model = "rapidgt2",      price = 36225 },
        { label = "Raptor",                   model = "raptor",        price = 32775 },
        { label = "Revolter",                 model = "revolter",      price = 97750 },
        { label = "Remidor",                  model = "remidor",       price = 17710 },
        { label = "Remus",                    model = "remus",         price = 34385 },
        { label = "Remus VERT",               model = "remusvert",     price = 36225 },
        { label = "Revolution S",             model = "revolutions",   price = 38180 },
        { label = "Roxanne",                  model = "roxanne",       price = 44275 },
        { label = "Elegy RH4",                model = "rh4",           price = 28750 },
        { label = "RT3000",                   model = "rt3000",        price = 32200 },
        { label = "Ruston",                   model = "ruston",        price = 46000 },
        { label = "S230",                     model = "s230",          price = 28750 },
        { label = "Sentinel Classique",       model = "sentinel3",     price = 36225 },
        { label = "Sentinel Classique Large", model = "sentinel4",     price = 37950 },
        { label = "Sentinel S",               model = "sentinels",     price = 40825 },
        { label = "Sentinel SG4D",            model = "sentinelsg4d",  price = 37375 },
        { label = "Seven-70",                 model = "seven70",       price = 86250 },
        { label = "Sheavas",                  model = "sheavas",       price = 48300 },
        { label = "Sigma3",                   model = "sigma3",        price = 46000 },
        { label = "SM722",                    model = "sm722",         price = 49450 },
        { label = "Itali GTO Stinger TT",     model = "italigto",      price = 189750 },
        { label = "Specter",                  model = "specter",       price = 86250 },
        { label = "Specter Custom",           model = "specter2",      price = 88550 },
        { label = "Speedster",                model = "gspeedster",    price = 132250 },
        { label = "Zircoflow Stratum",        model = "stratum",       price = 34339 },
        { label = "Sugoi",                    model = "Sugoi",         price = 28750 },
        { label = "Emperor Ronin",            model = "gbronin",       price = 42580 },
        { label = "Sultan",                   model = "sultan",        price = 47150 },
        { label = "Sultan Classique",         model = "sultan2",       price = 55200 },
        { label = "Sultan Classique Custom",  model = "sultan2c",      price = 63250 },
        { label = "Sultan RS Classique",      model = "sultan3",       price = 64400 },
        { label = "Sunrise",                  model = "sunrise1",      price = 63250 },
        { label = "Super GTS",                model = "supergts",      price = 74750 },
        { label = "10F",                      model = "tenf",          price = 132250 },
        { label = "10F Large",                model = "tenf2",         price = 143750 },
        { label = "Tropos Rallye",            model = "tropos",        price = 39100 },
        { label = "Turismo Custom",           model = "turismo2",      price = 134550 },
        { label = "Turismo CS",               model = "turismocs",     price = 138000 },
        { label = "Vectre",                   model = "vectre",        price = 39675 },
        { label = "Vesper",                   model = "vesper",        price = 70150 },
        { label = "Vincent 2",                model = "vincent2",      price = 50600 },
        { label = "Vincent 3",                model = "vincent3",      price = 47150 },
        { label = "Vorstand",                 model = "vorstand",      price = 36294 },
        { label = "Warrener HKR",             model = "warrener",      price = 21275 },
        { label = "Weevil Ruff-Weld",         model = "weevilf6",      price = 40250 },
        { label = "Zion V10",                 model = "zionv10",       price = 41630 },
        { label = "ZR350 Zinxy",              model = "zinxy",         price = 40250 },
        { label = "ZR",                       model = "zr",            price = 51750 },
        { label = "ZR250",                    model = "zr250",         price = 32775 },
        { label = "ZR350",                    model = "zr350",         price = 37835 },
        { label = "ZR350 Nishukan",           model = "as_zr350",      price = 41400 },
        { label = "ZR380 Custom",             model = "zr380c",        price = 43700 },
        { label = "ZR 380 Sport",             model = "zr380s",        price = 46000 },
        { label = "ZR390",                    model = "zr390",         price = 47150 },
        { label = "GB Comet S2 RC",           model = "gbcomets2rc",   price = 115000 },
        { label = "Banshee S",                model = "gbbanshees",    price = 69000 },
        { label = "Alpha",                    model = "alpha",         price = 28175 },
        { label = "Banshee",                  model = "banshee",       price = 45989 },
        { label = "Banshee AS",               model = "bansheeas",     price = 47150 },
        { label = "Banshee PO",               model = "bansheepo",     price = 48588 },
        { label = "Buffalo",                  model = "buffalo",       price = 34500 },
        { label = "Buffalo S",                model = "buffalo2",      price = 44275 },
        { label = "Contender Custom",         model = "contenderc",    price = 45195 },
        { label = "Coquette",                 model = "coquette",      price = 74750 },
        { label = "Coquette D10",             model = "coquette4",     price = 86250 },
        { label = "Flash GT",                 model = "flashgt",       price = 43125 },
        { label = "Fusillade",                model = "fusilade",      price = 29900 },
        { label = "GB200",                    model = "gb200",         price = 38525 },
        { label = "Howitzer Custom",          model = "howitzer2",     price = 50600 },
        { label = "Raiden",                   model = "raiden",        price = 86250 },
        { label = "Recursion",                model = "recursion",     price = 26450 },
        { label = "RidenZ",                   model = "raidenz",       Price = 90275 },
        { label = "Taranis",                  model = "taranis",       price = 28175 },
        { label = "Torrence",                 model = "torrence",      price = 34489 },
        { label = "Coquette Thunderstruck",   model = "thunderstruck", price = 83375 },
        { label = "Verlierer",                model = "verlierer2",    price = 28750 },
        { label = "V-STR",                    model = "vstr",          price = 63250 },
        { label = "Coil Eon",                 model = "gbeon",         price = 125500 },
        { label = "Sultan RSx",               model = "gbsultanrsx",   price = 42550 },
        { label = "Pfister Neon CT",          model = "gbneonct",      price = 69000 },
        { label = "Mogul RS",                 model = "gbmogulrs",     price = 64400 },
        { label = "BF Club XR",               model = "gbclubxr",      price = 23250 },
        { label = "Solace",                   model = "gbsolace",      price = 84525 },
        { label = "Sapphire",                 model = "gbsapphire",    price = 94875 },
        { label = "10F Spyder",               model = "gbtenfr",       price = 134550 },
        { label = "Comet S2R",                model = "gbcomets2r",    price = 150185 },
        { label = "Solace Vitesse",           model = "gbsolacev",     price = 138000 },
        { label = "Argento 7F",               model = "gbargento7f",   price = 109250 },
    },
    ["Moto"] = {
        { label = "Bati 901",        model = "bati901",    price = 19953 },
        { label = "Akuma",           model = "akuma",      price = 10063 },
        { label = "Akuma Classic",   model = "akumac",     price = 11443 },
        { label = "Bati 801",        model = "bati",       price = 15525 },
        { label = "Bati 801RR",      model = "bati2",      price = 20125 },
        { label = "Bati 701",        model = "bati701",    price = 16100 },
        { label = "Carbon RS",       model = "carbonrs",   price = 14088 },
        { label = "Defiler",         model = "defiler",    price = 8280 },
        { label = "Diablous",        model = "diablous",   price = 12075 },
        { label = "Diablous Custom", model = "diablous2",  price = 10833 },
        { label = "Double T",        model = "double",     price = 11960 },
        { label = "Esskey",          model = "esskey",     price = 9775 },
        { label = "Enduro MK2",      model = "enduromk2",  price = 14950 },
        { label = "Faggio Sport",    model = "faggio",     price = 1478 },
        { label = "Faggio",          model = "faggio2",    price = 1650 },
        { label = "Faggio Mod",      model = "faggio3",    price = 1840 },
        { label = "Fcr 1000",        model = "fcr",        price = 10638 },
        { label = "Fcr 1000 Custom", model = "fcr2",       price = 13513 },
        { label = "Hakuchou",        model = "hakuchou",   price = 21448 },
        { label = "Hakuchou Drag",   model = "hakuchou2",  price = 27025 },
        { label = "Kampfer",         model = "kampfer",    price = 10638 },
        { label = "Kunoichi",        model = "kunoichi",   price = 10638 },
        { label = "kusa",            model = "kusa",       price = 10810 },
        { label = "Lectro",          model = "lectro",     price = 9775 },
        { label = "Nemesis",         model = "nemesis",    price = 9488 },
        { label = "PCJ 600",         model = "pcj",        price = 8625 },
        { label = "Powersurge",      model = "powersurge", price = 13225 },
        { label = "Reever",          model = "reever",     price = 14375 },
        { label = "Ruffian",         model = "ruffian",    price = 9603 },
        { label = "Saltflat 600",    model = "saltflat",   price = 15525 },
        { label = "SG1150",          model = "sg1150",     price = 22989 },
        { label = "Shinobi",         model = "shinobi",    price = 22989 },
        { label = "Stryder",         model = "Stryder",    price = 19021 },
        { label = "TT750",           model = "tt750",      price = 14950 },
        { label = "Thrust",          model = "thrust",     price = 14375 },
        { label = "Vader",           model = "vader",      price = 9373 },
        { label = "Vindicator",      model = "vindicator", price = 14778 },
        { label = "Vortex",          model = "vortex",     price = 10925 },
    },
}

VFW.AmericanMotors.Vehicle = {
    ["Sport-Classic"] = {
        { label = "Admiral",            model = "admiral3",    price = 5290 },
        { label = "Brisket",            model = "brisket",     price = 12075 },
        { label = "Brisket Rally",      model = "brisket2",    price = 21275 },
        { label = "Brisket Gasser",     model = "brisket3",    price = 23000 },
        { label = "Cheburek",           model = "cheburek",    price = 16675 },
        { label = "Clique Deluxe",      model = "clique2",     price = 15525 },
        { label = "Coquette Classique", model = "coquette2",   price = 25300 },
        { label = "Deluxo",             model = "deluxo2",     price = 28750 },
        { label = "Dynasty",            model = "dynasty",     price = 7475 },
        { label = "Fagaloa",            model = "fagaloa",     price = 8683 },
        { label = "Kentish",            model = "kentish",     price = 10350 },
        { label = "Mamba",              model = "mamba",       price = 32200 },
        { label = "Manana",             model = "manana",      price = 8625 },
        { label = "Manana Custom",      model = "manana2",     price = 15238 },
        { label = "Peyote",             model = "peyote",      price = 4583 },
        { label = "Peyote Gasser",      model = "peyote2",     price = 12926 },
        { label = "Peyote Custom",      model = "peyote3",     price = 16721 },
        { label = "Retinue",            model = "retinue",     price = 20125 },
        { label = "Retinue MK2",        model = "retinue2",    price = 44275 },
        { label = "Tornado",            model = "tornado",     price = 2588 },
        { label = "Tornado Cabrio",     model = "tornado2",    price = 2645 },
        { label = "Tornado Custom",     model = "tornado5",    price = 13513 },
        { label = "Tornado Rouillé",    model = "tornado3",    price = 2300 },
        { label = "Tornado Cab Merico", model = "tornado4",    price = 5348 },
        { label = "Tornado Rat Rod",    model = "tornado6",    price = 4139 },
        { label = "Comet Classique",    model = "gbcometcl",   price = 63250 },
        { label = "Komoda GT",          model = "gbkomodagt",  price = 64285 },
        { label = "Turismo 300GT",      model = "gbturismogt", price = 97750 },
    },
    ["Muscles"] = {
        { label = "Dominator GT 2015",         model = "dominatorgt",    price = 30475 },
        { label = "Gauntlet",                  model = "gauntlets",      price = 31648 },
        { label = "Brigham",                   model = "brigham",        price = 19550 },
        { label = "Buccaneer",                 model = "buccaneer",      price = 15583 },
        { label = "Buffalo STX",               model = "buffalo4",       price = 89125 },
        { label = "Buffalo EVX",               model = "buffalo5",       price = 94875 },
        { label = "Buffalo Hellhound",         model = "buffaloh",       price = 92000 },
        { label = "Broadway",                  model = "broadway",       price = 14375 },
        { label = "Chino",                     model = "chino",          price = 9488 },
        { label = "Clique",                    model = "clique",         price = 14433 },
        { label = "Clique Deluxe",             model = "clique2",        price = 15525 },
        { label = "Coquette BlackFin",         model = "coquette3",      price = 51750 },
        { label = "Crowd Runner",              model = "crowdrunner",    price = 132250 },
        { label = "Deviant",                   model = "deviant",        price = 22885 },
        { label = "Dominator",                 model = "dominator",      price = 28175 },
        { label = "Dominator PissWasser",      model = "dominator2",     price = 31625 },
        { label = "Dominator GTX",             model = "dominator3",     price = 52325 },
        { label = "Dominator ASP",             model = "dominator7",     price = 54625 },
        { label = "Dominator GTT",             model = "dominator8",     price = 58650 },
        { label = "Dominator GT Cabrio",       model = "dominator9",     price = 51750 },
        { label = "Dukes",                     model = "dukes",          price = 14950 },
        { label = "Beater Dukes",              model = "dukes3",         price = 20125 },
        { label = "Ellie",                     model = "ellie",          price = 40250 },
        { label = "Esperanto 2D",              model = "esperanto2d",    price = 14375 },
        { label = "Eudora",                    model = "eudora",         price = 15525 },
        { label = "Eudora Convertible",        model = "eudorac",        price = 20125 },
        { label = "Faction",                   model = "faction",        price = 15330 },
        { label = "Gauntlet",                  model = "gauntlet",       price = 56925 },
        { label = "Gauntlet Redwood",          model = "gauntlet2",      price = 24725 },
        { label = "Gauntlet Classique",        model = "gauntlet3",      price = 21793 },
        { label = "Gauntlet Hellfiire",        model = "gauntlet4",      price = 86250 },
        { label = "Gauntlet 4C",               model = "gauntlet4c",     price = 64400 },
        { label = "Gauntlet Classique Custom", model = "gauntlet5",      price = 30475 },
        { label = "Gauntlet AC",               model = "gauntletac",     price = 40733 },
        { label = "Gauntlet CTX",              model = "gauntletctx",    price = 103489 },
        { label = "Greenwood",                 model = "greenwood",      price = 22989 },
        { label = "Hermes",                    model = "hermes",         price = 20125 },
        { label = "Hotknife",                  model = "hotknife",       price = 13225 },
        { label = "Hustler",                   model = "hustler",        price = 18400 },
        { label = "Impaler",                   model = "impaler",        price = 15525 },
        { label = "Impaler LX",                model = "impaler6",       price = 22425 },
        { label = "Vigero Opulent",            model = "jdvigeror",      price = 18975 },
        { label = "Vigero Opulent Drag",       model = "jdvigerord",     price = 54625 },
        { label = "Moonbeam",                  model = "moonbeam",       price = 14375 },
        { label = "Nightshade",                model = "nightshade",     price = 31625 },
        { label = "Paradox",                   model = "paradox",        price = 27025 },
        { label = "Paradox Drag",              model = "paradox2",       price = 40825 },
        { label = "Phoenix",                   model = "phoenix",        price = 8085 },
        { label = "Picador",                   model = "picador",        price = 9775 },
        { label = "Picador Loco",              model = "picadorl",       price = 13294 },
        { label = "Primo Sport",               model = "primo3",         price = 27025 },
        { label = "Rat Demon",                 model = "ratdemon",       price = 63250 },
        { label = "Rat-Loader",                model = "ratloader",      price = 5601 },
        { label = "Rat-Truck",                 model = "ratloader2",     price = 6325 },
        { label = "Razor",                     model = "razor",          price = 22989 },
        { label = "Riva",                      model = "riva",           price = 16675 },
        { label = "Ruiner",                    model = "ruiner",         price = 14088 },
        { label = "Ruiner ZZ-8",               model = "ruiner4",        price = 30475 },
        { label = "Sabre Turbo",               model = "sabregt",        price = 23575 },
        { label = "Savanna SA",                model = "savannasa",      price = 13225 },
        { label = "Slamvan",                   model = "slamvan",        price = 10925 },
        { label = " Slamvan Du LOST",          model = "slamvan2",       price = 12075 },
        { label = "Slamvan Custom",            model = "slamvan3",       price = 14444 },
        { label = "Stallion",                  model = "stalion",        price = 20125 },
        { label = "Tampa",                     model = "tampa",          price = 16675 },
        { label = "Tampa R",                   model = "tampar",         price = 44160 },
        { label = "Tulip",                     model = "tulip",          price = 25875 },
        { label = "Tulip M-100",               model = "tulip2",         price = 21275 },
        { label = "Tulip 3",                   model = "tulip3",         price = 28750 },
        { label = "Vamos",                     model = "vamos",          price = 16675 },
        { label = "Vigero",                    model = "vigero",         price = 20700 },
        { label = "Vigero ZX",                 model = "vigero2",        price = 40825 },
        { label = "Vigero ZX Cabrio",          model = "vigero3",        price = 51750 },
        { label = "Vigero Rumbler",            model = "vigero5",        price = 22828 },
        { label = "Vigero Rumbler Drag",       model = "vigero4",        price = 27025 },
        { label = "Vigero New",                model = "vigeronew",      price = 36225 },
        { label = "Virgo",                     model = "virgo",          price = 11190 },
        { label = "Virgo Classique",           model = "virgo3",         price = 16675 },
        { label = "Vulture",                   model = "vulture",        price = 21275 },
        { label = "Yosemite",                  model = "yosemite",       price = 17250 },
        { label = "Yosemite Drift",            model = "yosemite2",      price = 18975 },
        { label = "Lazeye Gauntlet",           model = "yubbynub",       price = 40250 },
        { label = "Dominator GSX",             model = "gbdominatorgsx", price = 86250 },
        { label = "Declasse Tahoma GT",        model = "gbtahomagt",     price = 23575 },
        { label = "Blade",                     model = "blade",          price = 12650 },
        { label = "Blade V2",                  model = "blade3",         price = 15525 },
        { label = "Buccaneer Custom",          model = "buccaneer2",     price = 20125 },
        { label = "Chino Custom",              model = "chino2",         price = 14950 },
        { label = "Faction Custom",            model = "faction2",       price = 20873 },
        { label = "Faction Custom Donk",       model = "faction3",       price = 15525 },
        { label = "Moonbeam Custom",           model = "moonbeam2",      price = 24725 },
        { label = "Sabre Turbo Custom",        model = "sabregt2",       price = 27025 },
        { label = "Turmalina",                 model = "turmalina",      price = 15640 },
        { label = "Turmalina 2",               model = "turmalina2",     price = 12075 },
        { label = "Voodoo Custom",             model = "voodoo",         price = 21275 },
        { label = "Virgo Classique Custom",    model = "virgo2",         price = 16675 },
        { label = "Voodoo",                    model = "voodoo2",        price = 7475 },
        { label = "Voodoo Coupe",              model = "voodoo5",        price = 15640 },
        { label = "Voodoo Convertible",        model = "voodoo5c",       price = 15525 },
        { label = "Weevil Custom",             model = "weevil",         price = 24725 },
    },
    ["Moto"] = {
        { label = "Acknod Low Rider",   model = "acknodlow",   price = 5000 },
        { label = "Avarus",             model = "avarus",      price = 8625 },
        { label = "Bagger",             model = "bagger",      price = 2214 },
        { label = "BF400",              model = "bf400",       price = 13225 },
        { label = "BF900",              model = "bf900",       price = 22943 },
        { label = "Chimera",            model = "chimera",     price = 10350 },
        { label = "Cliffhanger",        model = "cliffhanger", price = 23825 },
        { label = "Daemon Lost",        model = "daemon",      price = 7475 },
        { label = "Daemon",             model = "daemon2",     price = 2473 },
        { label = "Harley Dyna",        model = "dyna",        price = 12649 },
        { label = "Harley Dyne",        model = "dyne",        price = 13225 },
        { label = "Enduro",             model = "enduro",      price = 7763 },
        { label = "Enforcer",           model = "enforcer",    price = 12938 },
        { label = "Gargoyle",           model = "gargoyle",    price = 15525 },
        { label = "Hexer",              model = "hexer",       price = 5290 },
        { label = "Hexer Custom",       model = "hexerz2",     price = 16675 },
        { label = "Innovation",         model = "innovation",  price = 14375 },
        { label = "LP Bagger",          model = "lpbagger",    price = 10872 },
        { label = "Blackwater",         model = "lpchopper",   price = 41325 },
        { label = "Manchez",            model = "manchez",     price = 9085 },
        { label = "Manchez Scout",      model = "manchez2",    price = 10925 },
        { label = "Manchez Scoot C",    model = "manchez3",    price = 12259 },
        { label = "Nagasaki MC450F",    model = "mc450f",      price = 22989 },
        { label = "NA-25",              model = "na25",        price = 12938 },
        { label = "Cross Bike",         model = "nbike",       price = 13800 },
        { label = "Nightblade",         model = "nightblade",  price = 18375 },
        { label = "RatBike",            model = "ratbike",     price = 2645 },
        { label = "Rampant Rocket",     model = "rrocket",     price = 28750 },
        { label = "Sanchez (Couleurs)", model = "sanchez",     price = 12075 },
        { label = "Sanchez",            model = "sanchez2",    price = 11788 },
        { label = "Sanctus",            model = "sanctus",     price = 20183 },
        { label = "Slave",              model = "slave",       price = 13225 },
        { label = "Acknod Softail",     model = "softail1",    price = 12650 },
        { label = "Sombrero",           model = "sombrero",    price = 9775 },
        { label = "Sovereign",          model = "sovereign",   price = 14375 },
        { label = "Sovereign Custom",   model = "sovereign2",  price = 13800 },
        { label = "Spirit",             model = "spirit",      price = 8970 },
        { label = "Spirit Custom",      model = "spirit1",     price = 10925 },
        { label = "Templar",            model = "tritemplarg", price = 20125 },
        { label = "Trig",               model = "trig",        price = 12075 },
        { label = "Wolfsbane",          model = "wolfsbane",   price = 10925 },
        { label = "ZombieV8",           model = "zombiev8",    price = 11615 },
        { label = "Zombie Bobber",      model = "zombiea",     price = 11903 },
        { label = "Zombie Chopper",     model = "zombieb",     price = 11040 },
        { label = "Carrier",            model = "carrier",     price = 14375 },
        { label = "NightBlade Custom",  model = "nightblade2", price = 20125 },
    },
    ["Tout-Terrain"] = {
        { label = "Baller Raid",               model = "baller7r",    price = 50600 },
        { label = "Baikal",                    model = "baikal",      price = 15525 },
        { label = "Injection",                 model = "bfinjection", price = 9775 },
        { label = "Bifta",                     model = "bifta",       price = 12938 },
        { label = "Bison",                     model = "bison",       price = 21275 },
        { label = "Beejay XL Off Road",        model = "bjxlr",       price = 20125 },
        { label = "Bobcat XL Trail",           model = "bobcatxl3",   price = 20700 },
        { label = "Bobcat XL Crew Cab Dually", model = "bobcatxl4",   price = 22425 },
        { label = "Bodhi",                     model = "bodhi2",      price = 10925 },
        { label = "Boor",                      model = "boor",        price = 23000 },
        { label = "Brawler",                   model = "brawler",     price = 41975 },
        { label = "Caracara 4x4",              model = "caracara2",   price = 55775 },
        { label = "Caracara 2022",             model = "caracaran",   price = 57500 },
        { label = "Cavalcade M",               model = "cavalcadem",  price = 37939 },
        { label = "Blazer",                    model = "blazer",      price = 5319 },
        { label = "Hot Rod Blazer",            model = "blazer3",     price = 7475 },
        { label = "Blazer Street",             model = "blazer4",     price = 9200 },
        { label = "Comet Safari",              model = "comet4",      price = 69000 },
        { label = "Contender",                 model = "contender",   price = 36800 },
        { label = "Contender Classique",       model = "contender8",  price = 34489 },
        { label = "Duneloader",                model = "dloader",     price = 9775 },
        { label = "Draugur",                   model = "draugur",     price = 287500 },
        { label = "Dune Buggy",                model = "dune",        price = 6900 },
        { label = "Everon",                    model = "everon",      price = 86250 },
        { label = "Freecrawler",               model = "freecrawler", price = 30475 },
        { label = "FXT 1",                     model = "fxt1",        price = 28175 },
        { label = "Granger",                   model = "granger",     price = 26450 },
        { label = "Guardian",                  model = "guardian",    price = 40250 },
        { label = "Hellion",                   model = "hellion",     price = 31625 },
        { label = "Hellion S",                 model = "hellion2",    price = 35075 },
        { label = "Kalahari",                  model = "kalahari",    price = 6440 },
        { label = "Kamacho",                   model = "kamacho",     price = 57500 },
        { label = "Walton L35",                model = "l35",         price = 36225 },
        { label = "LandRoamer",                model = "landroamer",  price = 17825 },
        { label = "Big Ol' Bobcat",            model = "lilred",      price = 20125 },
        { label = "Medved",                    model = "medved",      price = 23000 },
        { label = "Mesa",                      model = "mesa",        price = 28750 },
        { label = "Mesa Trail",                model = "mesa3",       price = 32775 },
        { label = "Mesa 4x4",                  model = "mesa4",       price = 41975 },
        { label = "Mesa R",                    model = "mesar",       price = 45989 },
        { label = "Mesa XL",                   model = "mesaxl",      price = 40250 },
        { label = "MonstroCiti",               model = "monstrociti", price = 25300 },
        { label = "Outlaw",                    model = "outlaw",      price = 25875 },
        { label = "Patriot Sport",             model = "patriots",    price = 43125 },
        { label = "Rancher XL",                model = "rancherxl",   price = 15525 },
        { label = "Ratel",                     model = "ratel",       price = 34500 },
        { label = "Rebel Rouillé",             model = "rebel",       price = 9200 },
        { label = "Rebel",                     model = "rebel2",      price = 15525 },
        { label = "Rebel S",                   model = "rebel4",      price = 21275 },
        { label = "Riata",                     model = "riata",       price = 20700 },
        { label = "Sadler 6",                  model = "sadler6",     price = 24150 },
        { label = "Sadler 7",                  model = "sadler7",     price = 18975 },
        { label = "Sadler 8",                  model = "sadler8",     price = 21275 },
        { label = "Sandking XL",               model = "sandking",    price = 37375 },
        { label = "Sandking SWB",              model = "sandking2",   price = 31625 },
        { label = "Sandking XL Trail",         model = "sandkingxl",  price = 27025 },
        { label = "Sandking Dually",           model = "sandstorm",   price = 30475 },
        { label = "Sandstorm",                 model = "sandstorm",   price = 64400 },
        { label = "Sandstorm XL",              model = "sandstormxl", price = 67850 },
        { label = "Slamvan 4X4",               model = "slam4x4",     price = 29900 },
        { label = "SS550",                     model = "ss550",       price = 12075 },
        { label = "Stanier Off Road",          model = "stanier5",    price = 41975 },
        { label = "Prally",                    model = "prally",      price = 40250 },
        { label = "Terminus",                  model = "terminus",    price = 76225 },
        { label = "TrailWilder",               model = "trailw",      price = 32200 },
        { label = "Vagrant",                   model = "vagrant",     price = 57385 },
        { label = "Verus",                     model = "verus",       price = 13225 },
        { label = "Yosemite Rancher",          model = "yosemite3",   price = 25875 },
        { label = "Weevil Outlaw",             model = "weevilo",     price = 14375 },
        { label = "Winky",                     model = "winky",       price = 14375 },
        { label = "Youga Classique 4X4",       model = "winky",       price = 20700 },
        { label = "Bison STX",                 model = "gbbisonstx",  price = 35075 },
        { label = "Bravado Bison HF",          model = "gbbisonhf",   price = 59225 },
        { label = "Karin Mojave",              model = "gbmojave",    price = 51255 },
    },
    ["Van"] = {
        { label = "Benson",                 model = "benson",      price = 29440 },
        { label = "Benson (Cluckin' Bell)", model = "benson2",     price = 38525 },
        { label = "Benson Classic",         model = "benson3",     price = 29440 },
        { label = "Burrito",                model = "burrito3",    price = 17250 },
        { label = "Caddy XL",               model = "caddyxl",     price = 11328 },
        { label = "Camper",                 model = "camper",      price = 14950 },
        { label = "Cerberus 300",           model = "cerberus4",   price = 29440 },
        { label = "Cerberus 200",           model = "cerberus5",   price = 28290 },
        { label = "Burrito LOST",           model = "gburrito",    price = 21275 },
        { label = "Burrito Gang",           model = "gburrito2",   price = 21275 },
        { label = "Journey",                model = "journey",     price = 6325 },
        { label = "Journey 2",              model = "journey2",    price = 7475 },
        { label = "Juggernaut",             model = "juggernaut",  price = 86250 },
        { label = "Lavoro",                 model = "lavoro",      price = 27025 },
        { label = "Minivan",                model = "minivan",     price = 17250 },
        { label = "Mule",                   model = "mule",        price = 26450 },
        { label = "Mule Type2",             model = "mule2",       price = 26450 },
        { label = "Mule Custom",            model = "mule3",       price = 31625 },
        { label = "Paradise",               model = "paradise",    price = 15525 },
        { label = "Pounder",                model = "pounder",     price = 89183 },
        { label = "Pounder Custom",         model = "pounder2",    price = 178250 },
        { label = "Road Killer",            model = "roadkiller",  price = 28750 },
        { label = "Rumpo Box Truck",        model = "rumpobox",    price = 22885 },
        { label = "Surfer",                 model = "surfer",      price = 14490 },
        { label = "Surfer Rouillé",         model = "surfer2",     price = 6900 },
        { label = "weeper",                 model = "sweeper",     price = 9775 },
        { label = "Youga",                  model = "youga",       price = 18975 },
        { label = "Youga Classique",        model = "youga2",      price = 16100 },
        { label = "Cadge",                  model = "cadge",       price = 15698 },
        { label = "Minivan Custom",         model = "minivan2",    price = 19780 },
        { label = "Pony",                   model = "pony",        price = 18975 },
        { label = "Pony Weed",              model = "pony2",       price = 16100 },
        { label = "Speedo",                 model = "speedo",      price = 13225 },
        { label = "Van de Clown",           model = "speedo2",     price = 17883 },
        { label = "Speedo Express",         model = "nspeedo",     price = 37375 },
        { label = "Speedo Liveries",        model = "speedoliv",   price = 18975 },
        { label = "Speedo Passenger",       model = "speedopas",   price = 20125 },
        { label = "Steed 2",                model = "steed2",      price = 12133 },
        { label = "Lemanja Tanajura",       model = "tanajura",    price = 6900 },
        { label = "Remorque",               model = "20fttrailer", price = 23000 },
        { label = "Rumpo Esperta",          model = "gbesperta",   price = 34489 },
    },
    ["Sedans"] = {
        { label = "Emperor",         model = "emperor",    price = 4094 },
        { label = "Emperor Rouillé", model = "emperor2",   price = 2185 },
        { label = "Esperanto",       model = "esperanto",  price = 14950 },
        { label = "Fugitive",        model = "fugitive",   price = 16675 },
        { label = "Greenwood C",     model = "greenwoodc", price = 15813 },
        { label = "Impaler SZ",      model = "impaler5",   price = 30475 },
        { label = "Panaroma",        model = "panorama",   price = 9775 },
        { label = "Regina",          model = "regina",     price = 4198 },
        { label = "Regina 4",        model = "regina4",    price = 5750 },
        { label = "Tahoma",          model = "tahoma",     price = 12018 },
        { label = "Tahoma 2",        model = "tahoma2",    price = 9488 },
        { label = "Tahoma 3",        model = "tahoma3",    price = 20125 },
        { label = "Warrener",        model = "warrener",   price = 10005 },
        { label = "Wombat",          model = "wombat",     price = 17710 },
    },
    ["SUV"] = {
        { label = "Aleutian",            model = "aleutian",     price = 31625 },
        { label = "Alamo 2600LS",        model = "nalamo",       price = 55200 },
        { label = "Cavalcade Gen 1",     model = "cavalcade",    price = 21275 },
        { label = "Cavalcade Gen 2",     model = "cavalcade2",   price = 23000 },
        { label = "Albany Cavalcade XL", model = "cavalcade3",   price = 49439 },
        { label = "Albany Cavalcade XL", model = "dorado",       price = 41389 },
        { label = "Granger-3600-LX",     model = "granger2",     price = 30521 },
        { label = "Gresley",             model = "gresley",      price = 25875 },
        { label = "Gresley Hellhound",   model = "gresleyh",     price = 72500 },
        { label = "Gresley STX",         model = "gbgresleystx", price = 64400 },
        { label = "Huntley S",           model = "huntleys",     price = 31625 },
        { label = "Pointer",             model = "pointer01",    price = 11500 },
        { label = "Executionner",        model = "executioner",  price = 19021 },
        { label = "Executionner2",       model = "executioner2", price = 14375 },
        { label = "Landstalker",         model = "landstalker",  price = 17250 },
        { label = "Landstalker XL",      model = "landstalker2", price = 40135 },
        { label = "Patriot",             model = "patriot",      price = 31050 },
        { label = "Patriot Stretch",     model = "patriot2",     price = 89125 },
        { label = "Seminole",            model = "seminole",     price = 12006 },
        { label = "Seminole Frontier",   model = "seminole2",    price = 20125 },
        { label = "Scout",               model = "scout",        price = 34385 },
        { label = "Scout '20",           model = "nscout",       price = 48300 },
    },
    ["Compact"] = {
        { label = "Brioso Classique",        model = "briosoc1", price = 7475 },
        { label = "Brioso Street Classique", model = "briosoc2", price = 8625 },
        { label = "Brioso Baja Classique",   model = "briosoc3", price = 9775 },
        { label = "Rhapsody",                model = "rhapsody", price = 4543 },
        { label = "Club",                    model = "club",     price = 25525 },
    },
}
