---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- DateTime: 31/01/2026 00:20
---

-- Définition du type de job "concess" pour le builder société
local model = JobModel.new("concess"):setLabel("Concessionnaire")

-- ==================== HELPER NOTIFICATION ====================

-- Fonction helper pour les notifications de type JOB côté client
local function ShowConcessNotification(content, isError, jobName)
    local societyInfo = TriggerServerCallback("core:get:societyInfo", jobName)
    local notifType = isError and 'ROUGE' or 'JOB'

    VFW.ShowNotification({
        type = notifType,
        image = societyInfo.image,
        title = societyInfo.label,
        subtitle = "Information",
        content = content
    })
end

-- ==================== GESTION DES CONCESSIONNAIRES ====================

local CONCESS_LIST = {}
local CONCESS_PEDS = {}
local CONCESS_SHOWCASE_VEHICLES = {} -- { [concessId] = { { entity, rotate }, ... } }
local SHOWCASE_SPIN_SPEED = 18.0

local function showcaseEntity(entry)
    if type(entry) == "table" then return entry.entity end
    return entry
end

local function deleteShowcaseVehicles(vehicles)
    if type(vehicles) ~= "table" then return end
    for _, entry in ipairs(vehicles) do
        local veh = showcaseEntity(entry)
        if veh and DoesEntityExist(veh) then
            DeleteEntity(veh)
        end
    end
end

local SHOWCASE_STATE_TAG = "concess_showcase"

-- Supprime tout véhicule "fantôme" à un point de showcase issu d'une session précédente
-- (cas où onResourceStop n'a pas pu nettoyer, ou crash). On combine deux signaux pour
-- éviter de toucher le véhicule légitime d'un joueur garé à proximité :
--   - state bag tag (fiable tant que le statebag survit)
--   - sinon : même modèle exact + position quasi identique (rayon 0.6m)
local function DeleteOrphanShowcaseAt(point, modelHash)
    local found = GetClosestVehicle(point.x, point.y, point.z, 2.5, modelHash, 70)
    if found == 0 or not DoesEntityExist(found) then
        return
    end

    local taggedShowcase = false
    local state = Entity(found).state
    if state and state[SHOWCASE_STATE_TAG] then
        taggedShowcase = true
    end

    if not taggedShowcase then
        local pos = GetEntityCoords(found)
        local dx = pos.x - point.x
        local dy = pos.y - point.y
        local dz = pos.z - point.z
        if (dx * dx + dy * dy + dz * dz) > (0.6 * 0.6) then
            return
        end
    end

    SetEntityAsMissionEntity(found, true, true)
    DeleteEntity(found)
end

-- Charger les concessionnaires au spawn du joueur
local function LoadConcessionnaires()
    local concessList = TriggerServerCallback("core:concess:getAll")

    if not concessList then
        return
    end

    -- Nettoyer les anciens éléments
    CleanupConcessionnaires()

    for _, concess in ipairs(concessList) do
        CONCESS_LIST[concess.id] = concess
        SetupConcessionnaire(concess)
    end
end

-- Nettoyer tous les éléments (PEDs, markers, etc.)
function CleanupConcessionnaires()
    for id, ped in pairs(CONCESS_PEDS) do
        if DoesEntityExist(ped) then
            DeleteEntity(ped)
        end
        CONCESS_PEDS[id] = nil
    end

    -- Nettoyer les véhicules de showcase
    for id, vehicles in pairs(CONCESS_SHOWCASE_VEHICLES) do
        deleteShowcaseVehicles(vehicles)
        CONCESS_SHOWCASE_VEHICLES[id] = nil
    end

    CONCESS_LIST = {}
end

-- Configurer un concessionnaire
function SetupConcessionnaire(concess)
    if not concess then return end

    local hasCatalog = concess.catalog and type(concess.catalog) == "table" and #concess.catalog > 0
    if hasCatalog then
        -- automatic = true → Toujours PED (mode auto forcé)
        -- automatic = false → PED seulement si aucun employé en service
        if concess.automatic then
            SpawnConcessPed(concess)
        else
            local hasEmployeesOnDuty = TriggerServerCallback("core:concess:areEmployeesOnDuty", concess.job)
            if not hasEmployeesOnDuty then
                SpawnConcessPed(concess)
            end
        end
    end

    SpawnShowcaseVehicles(concess)
end

-- Spawner le PED du concessionnaire
function SpawnConcessPed(concess)
    if CONCESS_PEDS[concess.id] then
        return
    end

    local pedModel = concess.pedModel or "a_m_y_business_01"
    local catalogPoint = concess.catalog[1]

    if not catalogPoint then
        return
    end

    local modelHash = joaat(pedModel)
    VFW.Streaming.RequestModel(modelHash)

    local ped = CreatePed(4, modelHash, catalogPoint.x, catalogPoint.y, catalogPoint.z, catalogPoint.h or 0.0, false, true)

    if DoesEntityExist(ped) then
        SetEntityInvincible(ped, true)
        SetBlockingOfNonTemporaryEvents(ped, true)
        FreezeEntityPosition(ped, true)
        SetPedCanRagdoll(ped, false)
        SetPedDiesWhenInjured(ped, false)

        CONCESS_PEDS[concess.id] = ped
    end

    SetModelAsNoLongerNeeded(modelHash)
end

-- Spawner les véhicules de showcase du concessionnaire
function SpawnShowcaseVehicles(concess)
    if not concess or not concess.id then return end
    if type(concess.showcase) ~= "table" or #concess.showcase == 0 then
        return
    end

    if CONCESS_SHOWCASE_VEHICLES[concess.id] then
        deleteShowcaseVehicles(CONCESS_SHOWCASE_VEHICLES[concess.id])
    end
    CONCESS_SHOWCASE_VEHICLES[concess.id] = {}

    for _, showcasePoint in ipairs(concess.showcase) do
        local modelName = showcasePoint and showcasePoint.model
        if type(modelName) == "string" and modelName ~= "" then
            local modelHash = joaat(modelName)
            if IsModelValid(modelHash) and IsModelAVehicle(modelHash) then
                local loaded = VFW.Streaming.RequestModel(modelHash)
                if loaded then
                    DeleteOrphanShowcaseAt(showcasePoint, modelHash)

                    local x = showcasePoint.x + 0.0
                    local y = showcasePoint.y + 0.0
                    local z = showcasePoint.z + 0.0
                    RequestCollisionAtCoord(x, y, z)
                    local foundGround, groundZ = GetGroundZFor_3dCoord(x, y, z + 2.0, false)
                    if foundGround then z = groundZ end

                    local vehicle = CreateVehicle(modelHash, x, y, z, showcasePoint.h or 0.0, false, false)
                    if DoesEntityExist(vehicle) then
                        SetEntityAsMissionEntity(vehicle, true, true)
                        SetVehicleOnGroundProperly(vehicle)
                        SetEntityInvincible(vehicle, true)
                        FreezeEntityPosition(vehicle, true)
                        SetVehicleDoorsLocked(vehicle, 2)
                        SetVehicleEngineOn(vehicle, false, true, true)
                        SetVehicleUndriveable(vehicle, true)
                        Entity(vehicle).state:set(SHOWCASE_STATE_TAG, true, false)

                        if showcasePoint.color then
                            local r = showcasePoint.color.r or 255
                            local g = showcasePoint.color.g or 255
                            local b = showcasePoint.color.b or 255
                            SetVehicleCustomPrimaryColour(vehicle, r, g, b)
                            SetVehicleCustomSecondaryColour(vehicle, r, g, b)
                        end

                        CONCESS_SHOWCASE_VEHICLES[concess.id][#CONCESS_SHOWCASE_VEHICLES[concess.id] + 1] = {
                            entity = vehicle,
                            rotate = showcasePoint.rotate == true,
                            heading = showcasePoint.h or GetEntityHeading(vehicle) or 0.0,
                        }
                    end
                    SetModelAsNoLongerNeeded(modelHash)
                end
            end
        end
    end
end

-- Variable pour stocker le concessionnaire actuel
local currentConcess = nil
local currentTestVehicle = nil
local currentTestNetId = nil
local currentTestConcessJob = nil


-- Vérifier si le joueur est employé du concessionnaire
local function IsPlayerEmployee(concess)
    local xPlayer = VFW.GetPlayerData()
    if not xPlayer or not xPlayer.job then
        return false
    end
    return xPlayer.job.name == concess.job and xPlayer.job.onDuty
end

-- Cache pour IsPlayerEmployee (re-check toutes les 5 secondes)
local _employeeCache = {}
local _employeeCacheTime = 0

local function IsPlayerEmployeeCached(concess)
    local now = GetGameTimer()
    if now - _employeeCacheTime > 5000 then
        _employeeCache = {}
        _employeeCacheTime = now
    end
    if _employeeCache[concess.job] == nil then
        _employeeCache[concess.job] = IsPlayerEmployee(concess)
    end
    return _employeeCache[concess.job]
end

-- Vérifier si le concessionnaire est en mode automatique (PED actif ou mode auto forcé)
local function IsConcessAutomatic(concess)
    if concess.automatic then
        return true
    end
    -- Si pas en mode auto forcé, vérifier s'il y a des employés en service
    local hasEmployeesOnDuty = TriggerServerCallback("core:concess:areEmployeesOnDuty", concess.job)
    return not hasEmployeesOnDuty
end

-- Animation tablette
local tabletAnimDict = "amb@code_human_in_bus_passenger_idles@female@tablet@base"
local tabletAnim = "base"
local tabletProp = nil

local function PlayTabletAnimation()
    local playerPed = PlayerPedId()

    -- Charger le dictionnaire d'animation
    RequestAnimDict(tabletAnimDict)
    while not HasAnimDictLoaded(tabletAnimDict) do
        Wait(10)
    end

    -- Jouer l'animation
    TaskPlayAnim(playerPed, tabletAnimDict, tabletAnim, 8.0, -8.0, -1, 49, 0, false, false, false)

    -- Créer la tablette prop
    local propModel = `prop_cs_tablet`
    RequestModel(propModel)
    while not HasModelLoaded(propModel) do
    Wait(10)
    end

    local boneIndex = GetPedBoneIndex(playerPed, 28422) -- Main droite
    tabletProp = CreateObject(propModel, 0.0, 0.0, 0.0, false, true, false)
    AttachEntityToEntity(tabletProp, playerPed, boneIndex, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, true, true, false, true, 1, true)

    SetModelAsNoLongerNeeded(propModel)
end

local function StopTabletAnimation()
    local playerPed = PlayerPedId()

    -- Arrêter l'animation
    StopAnimTask(playerPed, tabletAnimDict, tabletAnim, 1.0)

    -- Supprimer la tablette prop
    if tabletProp and DoesEntityExist(tabletProp) then
        DeleteEntity(tabletProp)
        tabletProp = nil
    end
end

-- Fonction pour ouvrir le catalogue du concessionnaire
local function OpenConcessCatalog(concess)
    if not concess then
        return
    end

    currentConcess = concess

    -- Jouer l'animation tablette
    PlayTabletAnimation()

    -- Récupérer les catégories et véhicules depuis le serveur (filtrés par type de concessionnaire)
    local categories = TriggerServerCallback("core:concess:getCategories", concess.concessType)
    local allVehicles = TriggerServerCallback("core:concess:getVehicles", nil, concess.concessType)

    if not categories or #categories == 0 then
        ShowConcessNotification("Aucune catégorie de véhicule disponible", true, concess.job)
        return
    end

    -- Vérifier si le joueur est employé
    local isEmployee = IsPlayerEmployee(concess)
    local isAutomatic = IsConcessAutomatic(concess)

    -- Récupérer le stock si employé
    local stock = {}
    if isEmployee then
        stock = TriggerServerCallback("core:concess:getStock", concess.id) or {}
    end

    -- Formater les catégories pour l'UI
    local formattedCategories = {}
    for _, cat in ipairs(categories) do
        formattedCategories[#formattedCategories + 1] = {
            name = cat,
            label = cat:gsub("^%l", string.upper)
        }
    end

    -- Formater les véhicules pour l'UI
    local formattedVehicles = {}
    for category, vehicles in pairs(allVehicles) do
        formattedVehicles[category] = {}
        for _, vehData in pairs(vehicles) do
            local cdnImage = VFW.CDN_BASE .. "/vehicles/" .. vehData.model .. ".png"
            local fallbackImage = ("https://docs.fivem.net/vehicles/%s.webp"):format(vehData.model)
            formattedVehicles[category][#formattedVehicles[category] + 1] = {
                model = vehData.model,
                name = vehData.name,
                price = vehData.price,
                category = vehData.category,
                speed = math.floor(GetVehicleModelEstimatedMaxSpeed(GetHashKey(vehData.model)) * 3.6),
                seats = GetVehicleModelNumberOfSeats(GetHashKey(vehData.model)),
                image = cdnImage,
                imageFallback = fallbackImage
            }
        end
    end

    local dataSociety = TriggerServerCallback("core:get:societyInfo", concess.job)

    -- Ouvrir l'interface NUI
    VFW.Nui.Focus(true, false)


    SendNUIMessage({
        action = "concessCatalog:open",
        data = {
            concessId = concess.id,
            concessName = dataSociety.jobLabel,
            concessImage = dataSociety.image,
            categories = formattedCategories,
            vehicles = formattedVehicles,
            selectedCategory = categories[1],
            isEmployee = isEmployee,
            isAutomatic = isAutomatic,
            stock = stock
        }
    })
end

-- Fonction pour fermer le catalogue
local function CloseConcessCatalog()
    VFW.Nui.Focus(false, false)
    SendNUIMessage({
        action = "concessCatalog:close"
    })
    currentConcess = nil

    -- Arrêter l'animation tablette
    StopTabletAnimation()
end

-- Mettre à jour le stock dans l'UI
local function UpdateStockUI()
    if not currentConcess then
        return
    end
    local stock = TriggerServerCallback("core:concess:getStock", currentConcess.id) or {}
    SendNUIMessage({
        action = "concessCatalog:updateStock",
        data = stock
    })
end

-- Callback NUI : Fermer le catalogue
RegisterNUICallback("concessCatalog:close", function(_, cb)
    CloseConcessCatalog()
    cb("ok")
end)

-- Callback NUI : Acheter un véhicule (client direct - mode automatique)
RegisterNUICallback("concessCatalog:buy", function(data, cb)
    if not currentConcess or not data.model or not data.price then
        cb({ success = false, message = "Les informations envoyées ne sont pas valides" })
        return
    end

    -- Sauvegarder l'ID avant de fermer
    local concessId = currentConcess.id

    -- Fermer l'UI
    CloseConcessCatalog()

    -- Déclencher l'achat côté serveur avec la méthode de paiement et la couleur choisie
    TriggerServerEvent("core:concess:buyVehicle", concessId, data.model, data.price, data.paymentMethod or "bank", GetMakeNameFromVehicleModel(data.model) .. " " .. GetLabelText(data.model), data.color)

    cb({ success = true })
end)

-- Callback NUI : Acheter pour le stock (employé)
RegisterNUICallback("concessCatalog:buyForStock", function(data, cb)
    if not currentConcess or not data.model or not data.price then
        cb({ success = false, message = "Les informations envoyées ne sont pas valides" })
        return
    end

    -- Déclencher l'achat pour le stock côté serveur
    TriggerServerEvent("core:concess:buyForStock", currentConcess.id, data.model, data.price, data.name)

    cb({ success = true })
end)

-- Callback NUI : Renvoyer un véhicule du stock (employé)
RegisterNUICallback("concessCatalog:returnFromStock", function(data, cb)
    if not currentConcess or not data.model then
        cb({ success = false, message = "Les informations envoyées ne sont pas valides" })
        return
    end

    TriggerServerEvent("core:concess:returnFromStock", currentConcess.id, data.model)

    cb({ success = true })
end)

-- Callback NUI : Démarrer un test
RegisterNUICallback("concessCatalog:startTest", function(data, cb)
    if not currentConcess or not data.model then
        cb({ success = false, message = "Les informations envoyées ne sont pas valides" })
        return
    end

    -- Sauvegarder l'ID avant de fermer (car CloseConcessCatalog met currentConcess à nil)
    local concessId = currentConcess.id

    -- Fermer l'UI temporairement
    CloseConcessCatalog()

    -- Déclencher le test côté serveur (on envoie le model)
    TriggerServerEvent("core:concess:startTest", concessId, data.model)

    cb({ success = true })
end)

-- Callback NUI : Arrêter un test
RegisterNUICallback("concessCatalog:stopTest", function(data, cb)
    if not currentConcess or not data.model then
        cb({ success = false, message = "Les informations envoyées ne sont pas valides" })
        return
    end

    -- Sauvegarder l'ID et la référence
    local concessId = currentConcess.id
    local concessRef = currentConcess

    -- Déclencher l'arrêt du test côté serveur
    TriggerServerEvent("core:concess:stopTest", concessId, data.model)

    -- Mettre à jour l'UI après un court délai pour s'assurer que le serveur a traité
    SetTimeout(200, function()
        if currentConcess and currentConcess.id == concessId then
            UpdateStockUI()
        end
    end)

    cb({ success = true })
end)

-- Callback NUI : Récupérer les joueurs proches (avec noms RP depuis le serveur)
RegisterNUICallback("concessCatalog:getNearbyPlayers", function(_, cb)
    local nearbyPlayerIds = {}
    local playerPed = PlayerPedId()
    local playerCoords = GetEntityCoords(playerPed)
    local maxDistance = 10.0

    -- Récupérer les IDs serveur des joueurs proches
    for _, playerId in ipairs(GetActivePlayers()) do
        if playerId ~= PlayerId() then
            local targetPed = GetPlayerPed(playerId)
            if DoesEntityExist(targetPed) then
                local targetCoords = GetEntityCoords(targetPed)
                local distance = #(playerCoords - targetCoords)

                if distance <= maxDistance then
                    local serverId = GetPlayerServerId(playerId)
                    nearbyPlayerIds[#nearbyPlayerIds + 1] = serverId
                end
            end
        end
    end

    -- Demander les noms RP au serveur
    local nearbyPlayers = TriggerServerCallback("core:concess:getNearbyPlayersNames", nearbyPlayerIds)
    cb(nearbyPlayers or {})
end)

-- Callback NUI : Vendre depuis le stock
RegisterNUICallback("concessCatalog:sellFromStock", function(data, cb)
    if not currentConcess or not data.model or not data.targetPlayerId then
        cb({ success = false, message = "Les informations envoyées ne sont pas valides" })
        return
    end

    -- Sauvegarder l'ID avant de fermer
    local concessId = currentConcess.id

    -- Fermer l'UI
    CloseConcessCatalog()

    -- Déclencher la vente côté serveur avec l'ID du joueur cible, la couleur et la remise
    TriggerServerEvent("core:concess:sellFromStock", concessId, data.model, data.targetPlayerId, GetMakeNameFromVehicleModel(data.model) .. " " .. GetLabelText(data.model), data.color, data.discountPercent)

    cb({ success = true })
end)

-- Cache des poids de coffre (kg) par modèle, alimenté par vehicleStorage:getStorageValues
local trunkWeightCache = {}

-- Callback NUI : Prévisualiser un véhicule
-- Récupère le poids de stockage du coffre (trunk_weight) depuis la config
-- vehicle_storage_config (callback existant `vehicleStorage:getStorageValues`).
RegisterNUICallback("concessCatalog:preview", function(data, cb)
    local model = data and data.model
    if type(model) ~= 'string' or model == '' then
        cb({ weight = 0 })
        return
    end

    if trunkWeightCache[model] ~= nil then
        local cached = trunkWeightCache[model]
        SendNUIMessage({
            action = "concessCatalog:vehicleWeight",
            data = { model = model, weight = cached }
        })
        cb({ model = model, weight = cached })
        return
    end

    CreateThread(function()
        local hash = GetHashKey(model)
        local values = TriggerServerCallback("vehicleStorage:getStorageValues", model, hash) or {}
        local trunkWeight = math.floor(tonumber(values.trunk_weight) or 0)

        trunkWeightCache[model] = trunkWeight
        SendNUIMessage({
            action = "concessCatalog:vehicleWeight",
            data = { model = model, weight = trunkWeight }
        })
        cb({ model = model, weight = trunkWeight })
    end)
end)

-- Callback NUI : Récupérer les logs
RegisterNUICallback("concessCatalog:getLogs", function(data, cb)
    if not data.concessId then
        cb({})
        return
    end

    local logs = TriggerServerCallback("core:concess:getLogs", data.concessId)
    cb(logs or {})
end)

-- Event : Stock mis à jour
RegisterNetEvent("concess:stockUpdated", function(concessId)
    if currentConcess and currentConcess.id == concessId then
        UpdateStockUI()
    end
end)

-- Fonction pour vérifier si un point de spawn est libre
local function IsSpawnPointFree(point, radius)
    radius = radius or 3.0
    local vehicle = GetClosestVehicle(point.x, point.y, point.z, radius, 0, 70)
    return vehicle == 0 or not DoesEntityExist(vehicle)
end

-- Fonction pour trouver un point de spawn libre
local function FindFreeSpawnPoint(concess)
    local spawnPoints = concess.spawn or {}

    -- Essayer d'abord les points de spawn dédiés
    for _, point in ipairs(spawnPoints) do
        if point and point.x and point.y and point.z then
            if IsSpawnPointFree(point) then
                return point
            end
        end
    end

    -- Si aucun spawn dédié libre, essayer les points du catalogue
    local catalogPoints = concess.catalog or {}
    for _, point in ipairs(catalogPoints) do
        if point and point.x and point.y and point.z then
            if IsSpawnPointFree(point) then
                return point
            end
        end
    end

    return nil
end

-- Event : Véhicule de test spawné côté serveur
RegisterNetEvent("concess:testVehicleSpawned", function(netId, plate, concessId)
    local concess = CONCESS_LIST[concessId]
    if not concess then
        ShowConcessNotification("Erreur: concessionnaire introuvable.", true)
        return
    end

    -- Stocker le job pour les notifications futures
    currentTestConcessJob = concess.job

    -- Attendre que le véhicule soit synchronisé côté client
    local attempts = 0
    local vehicle = nil

    while attempts < 50 do
        vehicle = NetworkGetEntityFromNetworkId(netId)
        if vehicle and DoesEntityExist(vehicle) then
            break
        end
        Wait(100)
        attempts = attempts + 1
    end

    if not vehicle or not DoesEntityExist(vehicle) then
        ShowConcessNotification("Erreur lors de la synchronisation du véhicule.", true, concess.job)
        return
    end

    -- Configurer le véhicule côté client
    SetVehicleOnGroundProperly(vehicle)
    SetVehicleDoorsLocked(vehicle, 0)
    SetVehicleDoorsLockedForAllPlayers(vehicle, false)
    SetVehicleDoorsLockedForNonScriptPlayers(vehicle, false)
    SetVehicleNeedsToBeHotwired(vehicle, false)
    SetVehicleIsStolen(vehicle, false)

    currentTestVehicle = vehicle
    currentTestNetId = netId

    ShowConcessNotification("Véhicule de test sorti.", false, concess.job)
end)

-- Event : Véhicule de test supprimé côté serveur
RegisterNetEvent("concess:testVehicleDeleted", function()
    if currentTestVehicle and DoesEntityExist(currentTestVehicle) then
        -- Sortir le joueur du véhicule si dedans
        local playerPed = PlayerPedId()
        if GetVehiclePedIsIn(playerPed, false) == currentTestVehicle then
            TaskLeaveVehicle(playerPed, currentTestVehicle, 0)
            Wait(1500)
        end
    end

    currentTestVehicle = nil
    currentTestNetId = nil

    ShowConcessNotification("Véhicule de test rangé.", false, currentTestConcessJob)
    currentTestConcessJob = nil
end)

-- Event : Test expiré (véhicule supprimé côté serveur)
RegisterNetEvent("concess:testExpired", function()
    if currentTestVehicle and DoesEntityExist(currentTestVehicle) then
        -- Sortir le joueur du véhicule si dedans
        local playerPed = PlayerPedId()
        if GetVehiclePedIsIn(playerPed, false) == currentTestVehicle then
            TaskLeaveVehicle(playerPed, currentTestVehicle, 0)
            Wait(1500)
        end
    end

    currentTestVehicle = nil
    currentTestNetId = nil

    ShowConcessNotification("Temps de test écoulé. Le véhicule a été récupéré.", true, currentTestConcessJob)
    currentTestConcessJob = nil
end)

-- Thread pour afficher les markers des points catalogue (seulement en mode manuel, sans PED)
CreateThread(function()
    while true do
        local sleep = 1000

        -- Vérifier si on a des concessionnaires chargés
        local hasConcess = false
        for _ in pairs(CONCESS_LIST) do
            hasConcess = true
            break
        end

        if hasConcess then
            local playerCoords = GetEntityCoords(PlayerPedId())

            for id, concess in pairs(CONCESS_LIST) do
                local hasPed = CONCESS_PEDS[id] and DoesEntityExist(CONCESS_PEDS[id])

                -- Cache coords du PED une fois par concess (frozen entity)
                local pedCoords
                if hasPed then
                    pedCoords = GetEntityCoords(CONCESS_PEDS[id])
                end

                if concess and concess.catalog and type(concess.catalog) == "table" and #concess.catalog > 0 then
                    for _, point in ipairs(concess.catalog) do
                        if point and point.x and point.y and point.z then
                            if not point._vec then
                                point._vec = vector3(point.x, point.y, point.z)
                            end

                            local distance = #(playerCoords - point._vec)

                            if distance < 5.0 then
                                sleep = 0
                                local canInteract = false

                                -- Mode avec PED : interaction avec le PED
                                if hasPed then
                                    local distanceToPed = #(playerCoords - pedCoords)

                                    if distanceToPed < 2.5 then
                                        VFW.ShowHelpNotification("Appuyez sur [E] pour ouvrir le catalogue")
                                        canInteract = true
                                    end
                                else
                                    -- Mode sans PED (manuel avec employés en service)
                                    local isEmployee = IsPlayerEmployeeCached(concess)

                                    -- Afficher le marker uniquement pour les clients externes
                                    -- Les employés utilisent le menu job
                                    if not isEmployee then
                                        DrawMarker(
                                                25,
                                                point.x, point.y, point.z,
                                                0.0, 0.0, 0.0,
                                                0.0, 0.0, 0.0,
                                                1.0, 1.0, 0.5,
                                                0, 200, 100, 150,
                                                false, true, 2, false,
                                                nil, nil, false
                                        )

                                        if distance < 1.5 then
                                            VFW.ShowHelpNotification("Appuyez sur [E] pour ouvrir le catalogue")
                                            canInteract = true
                                        end
                                    end
                                end

                                -- Gestion de la touche E
                                if canInteract and VFW.Interact.JustPressed(0, 38) then
                                    OpenConcessCatalog(concess)
                                end
                            end
                        end
                    end
                end
            end
        end

        Wait(sleep)
    end
end)


-- Event pour ouvrir le catalogue depuis le menu job (mode manuel)
RegisterNetEvent("concess:openCatalogFromMenu", function()
    local xPlayer = VFW.GetPlayerData()
    if not xPlayer or not xPlayer.job then return end

    for _, concess in pairs(CONCESS_LIST) do
        if concess.job == xPlayer.job.name then
            OpenConcessCatalog(concess)
            return
        end
    end

    local mine = TriggerServerCallback("core:concess:getMine")
    if mine and mine.id then
        OpenConcessCatalog(mine)
    end
end)

-- Rafraîchir les concessionnaires quand un employé se met en/hors service
RegisterNetEvent("concess:refreshEmployeeStatus", function(jobName)
    for id, concess in pairs(CONCESS_LIST) do
        if concess.job == jobName then
            -- automatic = true → toujours PED, pas besoin de refresh
            -- automatic = false → mode dynamique, vérifier le statut
            if not concess.automatic then
                local hasEmployeesOnDuty = TriggerServerCallback("core:concess:areEmployeesOnDuty", concess.job)

                if hasEmployeesOnDuty then
                    -- Employés en service → supprimer le PED
                    if CONCESS_PEDS[id] and DoesEntityExist(CONCESS_PEDS[id]) then
                        DeleteEntity(CONCESS_PEDS[id])
                        CONCESS_PEDS[id] = nil
                    end
                else
                    -- Aucun employé → spawner le PED
                    SpawnConcessPed(concess)
                end
            end
        end
    end
end)

-- Événements de mise à jour des concessionnaires
RegisterNetEvent("concess:created", function(concess)
    CONCESS_LIST[concess.id] = concess
    SetupConcessionnaire(concess)
end)

RegisterNetEvent("concess:updated", function(concess)
    if CONCESS_PEDS[concess.id] and DoesEntityExist(CONCESS_PEDS[concess.id]) then
        DeleteEntity(CONCESS_PEDS[concess.id])
        CONCESS_PEDS[concess.id] = nil
    end

    CONCESS_LIST[concess.id] = concess
    SetupConcessionnaire(concess)
end)

RegisterNetEvent("concess:deleted", function(id)
    if CONCESS_PEDS[id] and DoesEntityExist(CONCESS_PEDS[id]) then
        DeleteEntity(CONCESS_PEDS[id])
        CONCESS_PEDS[id] = nil
    end

    -- Nettoyer les véhicules de showcase
    if CONCESS_SHOWCASE_VEHICLES[id] then
        deleteShowcaseVehicles(CONCESS_SHOWCASE_VEHICLES[id])
        CONCESS_SHOWCASE_VEHICLES[id] = nil
    end

    CONCESS_LIST[id] = nil
end)

-- Charger au spawn du joueur
RegisterNetEvent("vfw:playerLoaded", function()
    Wait(2000)
    LoadConcessionnaires()
end)

-- Recharger si la ressource redémarre
AddEventHandler("onResourceStart", function(resourceName)
    if GetCurrentResourceName() == resourceName then
        if VFW.IsPlayerLoaded() then
            Wait(1000)
            LoadConcessionnaires()
        end
    end
end)

CreateThread(function()
    Wait(5000)
    local count = 0
    for _ in pairs(CONCESS_LIST) do
        count = count + 1
    end
    if count == 0 then
        LoadConcessionnaires()
    end
end)

CreateThread(function()
    while true do
        Wait(10000)
        for id, concess in pairs(CONCESS_LIST) do
            local points = concess and concess.showcase
            if type(points) == "table" and #points > 0 then
                local vehicles = CONCESS_SHOWCASE_VEHICLES[id]
                local needsRespawn = type(vehicles) ~= "table" or #vehicles == 0
                if not needsRespawn then
                    for _, entry in ipairs(vehicles) do
                        local veh = showcaseEntity(entry)
                        if not veh or not DoesEntityExist(veh) then
                            needsRespawn = true
                            break
                        end
                    end
                end
                if needsRespawn then
                    SpawnShowcaseVehicles(concess)
                end
            elseif CONCESS_SHOWCASE_VEHICLES[id] then
                deleteShowcaseVehicles(CONCESS_SHOWCASE_VEHICLES[id])
                CONCESS_SHOWCASE_VEHICLES[id] = nil
            end
        end
    end
end)

CreateThread(function()
    while true do
        local spinning = false
        for _, vehicles in pairs(CONCESS_SHOWCASE_VEHICLES) do
            for _, entry in ipairs(vehicles) do
                if type(entry) == "table" and entry.rotate then
                    local veh = entry.entity
                    if veh and DoesEntityExist(veh) then
                        spinning = true
                        entry.heading = (entry.heading or 0.0) + SHOWCASE_SPIN_SPEED * GetFrameTime()
                        if entry.heading >= 360.0 then entry.heading = entry.heading - 360.0 end
                        SetEntityHeading(veh, entry.heading)
                    end
                end
            end
        end
        Wait(spinning and 0 or 500)
    end
end)

-- Affiche un blip GPS temporaire sur la position du véhicule fraîchement acheté.
-- Le blip disparait soit après 60s, soit dès que le joueur s'approche à moins de 10m.
local concessGpsBlips = {}

local function clearConcessGpsBlip(plate)
    local blip = concessGpsBlips[plate]
    if blip and DoesBlipExist(blip) then
        SetBlipRoute(blip, false)
        RemoveBlip(blip)
    end
    concessGpsBlips[plate] = nil
end

RegisterNetEvent("core:concess:showVehicleGps", function(x, y, z, plate)
    if not x or not y or not z then return end

    -- Si un blip existait déjà pour cette plaque (re-achat rapide), on nettoie
    clearConcessGpsBlip(plate)

    local blip = AddBlipForCoord(x + 0.0, y + 0.0, z + 0.0)
    SetBlipSprite(blip, 326)
    SetBlipColour(blip, 5)
    SetBlipScale(blip, 0.9)
    SetBlipDisplay(blip, 4)
    SetBlipAsShortRange(blip, false)
    SetBlipRoute(blip, true)
    SetBlipRouteColour(blip, 5)
    BeginTextCommandSetBlipName("STRING")
    AddTextComponentSubstringPlayerName(("Véhicule acheté (%s)"):format(plate or ""))
    EndTextCommandSetBlipName(blip)

    concessGpsBlips[plate] = blip

    CreateThread(function()
        local target = vector3(x + 0.0, y + 0.0, z + 0.0)
        local deadline = GetGameTimer() + 60000
        while concessGpsBlips[plate] == blip and GetGameTimer() < deadline do
            local ped = PlayerPedId()
            if ped and DoesEntityExist(ped) then
                if #(GetEntityCoords(ped) - target) < 10.0 then
                    break
                end
            end
            Wait(1000)
        end
        clearConcessGpsBlip(plate)
    end)
end)

-- Nettoyer à la déconnexion
AddEventHandler("onResourceStop", function(resourceName)
    if GetCurrentResourceName() == resourceName then
        CleanupConcessionnaires()
        -- Réinitialiser les variables de test (le véhicule est géré côté serveur)
        currentTestVehicle = nil
        currentTestNetId = nil
        for plate in pairs(concessGpsBlips) do
            clearConcessGpsBlip(plate)
        end
    end
end)
